#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

rm -f blockbench.deb

wget -O ~/blockbench.deb "https://apt.raspbian-addons.org/debian/pool/blockbench_3.9.3_arm64.deb" || error "Failed to download deb file!"

"${DIRECTORY}/pkg-install" "$HOME/blockbench.deb" "$(dirname "$0")" || exit 1

rm -f blockbench.deb
