#!/bin/bash

if [ $arch == 32 ];then
  url_arch=armv7l
elif [ $arch == 64 ];then
  url_arch=aarch64
else
  error "Failed to detect OS CPU architecture! Something is very wrong."
fi

PAGE_SIZE="$(getconf PAGE_SIZE)"
if [[ "$PAGE_SIZE" == "16384" ]]; then
  #switch to 4K pagesize kernel
  if [ -f /boot/config.txt ]; then
    text="Raspberry Pi 5 PiOS images ship by default with a 16K PageSize Linux Kernel.
This kernel causes incompatibilities with some software including MuseScore https://github.com/raspberrypi/bookworm-feedback/issues/107

Would you like to automatically switch to a 4K PageSize Linux Kernel?"
    userinput_func "$text" "No, keep 16K PageSize Kernel and Exit" "Yes, switch to 4K PageSize Kernel"
    if [ "$output" == "No, keep 16K PageSize Kernel and Exit" ]; then
      error "User error: Your current running kernel is built with 16K PageSize and is incompatible with MuseScore. You must switch to a 4K PageSize kernel (and chose to not do so automatically) before installing MuseScore."
    fi
    echo "" | sudo tee --append /boot/config.txt >/dev/null
    echo "[pi5]" | sudo tee --append /boot/config.txt >/dev/null
    echo "kernel=kernel8.img" | sudo tee --append /boot/config.txt >/dev/null
    echo -e "The 4K PageSize Kernel has been enabled by adding 'kernel=kernel8.img' to /boot/config.txt\nPlease reboot now and install the MuseScore app again."
    sleep infinity
  else
    error "User error (reporting allowed): Your current running kernel is built with 16K PageSize and is incompatible with MuseScore. Changing kernels automatically cannot be done since no /boot/config.txt file was found."
  fi
fi

if package_installed musescore ;then
  status "First removing musescore package with APT..."
  sudo apt purge musescore -y --autoremove || exit 1
fi

enable_module fuse || exit 1

wget -O "/tmp/MuseScore.AppImage" "https://github.com/Pi-Apps-Coders/files/releases/download/large-files/MuseScore-4.1.1.233220526-${url_arch}.AppImage" || exit 1

chmod +x "/tmp/MuseScore.AppImage"

#Use built-in install procedure
sudo /tmp/MuseScore.AppImage install || error "MuseScore.AppImage failed to run its own installation procedure. Please review errors above."
#this moves itself to /usr/local/bin/MuseScore.AppImage

#make terminal command
sudo rm -f /usr/local/bin/mscore
sudo ln -s /usr/local/bin/MuseScore.AppImage /usr/local/bin/mscore

#change menu button label to 'MuseScore 4'
sudo sed -i 's/^Name=.*/Name=MuseScore 4/g' /usr/local/share/applications/org.musescore.MuseScore4portable.desktop
true #in case sed fails
