#!/bin/bash

#Allow packages required by this app to be uninstalled
purge_packages || exit 1

sudo rm -f /usr/local/bin/mscore

#Use built-in uninstall procedure
if [ -f /usr/local/bin/MuseScore.AppImage ];then
  echo y | sudo /usr/local/bin/MuseScore.AppImage uninstall || error "MuseScore.AppImage failed to run its own installation procedure. Please review errors above."
fi
true
