#!/bin/bash

sudo rm -rf "/usr/local/bin/pacman_sdl" "/usr/local/share/pacman_sdl" "/usr/local/share/applications/pacman_sdl.desktop" "/usr/local/share/doc/pacman_sdl"

sudo update-desktop-database -q

purge_packages || exit 1
