#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

rm -rf ~/MacOSBigSurThemeConverter || error "Failed to first remove ~/MacOSBigSurThemeConverter folder"
git clone https://github.com/techcoder20/MacOSBigSurThemeConverter.git || error "failed to download github repository!"

#Making install script executable
sudo chmod +x ~/MacOSBigSurThemeConverter/install.sh || error "Failed to make install script executable"

#Running Install script
~/MacOSBigSurThemeConverter/install.sh || error "Failed to run install script"



