#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

#Running uninstall script
if [ -f ~/.local/share/MacOSBigSurThemeConverter/uninstall.sh ];then
  chmod +x ~/.local/share/MacOSBigSurThemeConverter/uninstall.sh
  ~/.local/share/MacOSBigSurThemeConverter/uninstall.sh || error "The script ~/.local/share/MacOSBigSurThemeConverter/uninstall.sh exited with failure!"
else
  echo "WARNING: could not find script ~/.local/share/MacOSBigSurThemeConverter/uninstall.sh"
fi

exit 0
