#!/bin/bash
#Running uninstall script
if [ -f ~/.local/share/MacOSBigSurThemeConverter/uninstall.sh ];then
  chmod +x ~/.local/share/MacOSBigSurThemeConverter/uninstall.sh
  ~/.local/share/MacOSBigSurThemeConverter/uninstall.sh || error "The script ~/.local/share/MacOSBigSurThemeConverter/uninstall.sh exited with failure!"
else
  echo "WARNING: could not find script ~/.local/share/MacOSBigSurThemeConverter/uninstall.sh"
fi

exit 0
