#!/bin/bash

function error {
  echo -e "\e[31m$1\e[39m"
  exit 1
}

# Get dependencies
DIRECTORY="$(dirname "$(dirname "$(dirname "$0")")")"
"${DIRECTORY}/pkg-install" "yad systemd-container xserver-xephyr expect" "$(dirname "$0")" || exit 1

wget -O - https://raw.githubusercontent.com/Botspot/Pi-Power-Tools/master/update | bash
