#!/bin/bash
# Get dependencies
install_packages yad systemd-container xserver-xephyr expect || exit 1
wget -O - https://raw.githubusercontent.com/Botspot/Pi-Power-Tools/master/update | bash
if [ "${PIPESTATUS[0]}" != 0 ];then
  error "PPT script download failed"
elif [ "${PIPESTATUS[1]}" != 0 ];then
  error "PPT script execution failed"
fi
