#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

cd $HOME
rm -f WhatsApp-linux-armv7l.tar.xz
wget https://github.com/cycool29/whatsapp-for-linux/releases/download/rpi-v1.0/WhatsApp-linux-armv7l.tar.xz || error 'Failed to download!'
tar -xf WhatsApp-linux-armv7l.tar.xz || error "Failed to extract!"
rm WhatsApp-linux-armv7l.tar.xz
mv "WhatsAppWeb-linux-armv7l" WhatsApp

#create menu shortcut
wget https://github.com/cycool29/whatsapp-for-linux/releases/download/rpi-v1.0/whatsapp.desktop 
sed -i "s@HOME@$HOME@g" whatsapp.desktop 
sudo cp whatsapp.desktop .local/share/applications 
sudo cp whatsapp.desktop $HOME/Desktop
