#!/bin/bash

#Bot automatically updates this when I make a new release.
version=2023.1.1
#Buster version
version2=2022.5.1

#Install Depends
install_packages apt-transport-https dirmngr gnupg ffmpeg mono-devel unzip zip || exit 1

mkdir -p ~/LineRider
cd ~/LineRider || error "Could not move to folder"

if [[ $(get_codename) == "buster" ]]; then
  use_version="$version2"
else
  use_version="$version"
fi

#Download LRA-Community-Edition build from repo
status "Downloading LineRider... "
wget -O linerider.zip https://github.com/Sussy-OS/LRA-Community-Edition/releases/download/${use_version}/LineRider.game.auto-release.${use_version}-LR.zip || error "Could not wget LineRider from GitHub!"

#Install
unzip linerider.zip || error "Could not unzip the files"
rm linerider.zip

#Add system ffmpeg to expected location
mkdir -p ~/Documents/LRA/ffmpeg/linux
cp $(command -v ffmpeg) ~/Documents/LRA/ffmpeg/linux/ffmpeg

#Menu shortcut
echo "[Desktop Entry]
Name=LineRider
Comment=An Open Source spiritual successor to the flash game Line Rider
Icon=$(dirname "$0")/icon-64.png
Exec=mono $HOME/LineRider/linerider.exe
Path=$HOME/LineRider/
Type=Application
Terminal=false
Categories=Game;" > ~/.local/share/applications/LineRider.desktop
