#!/bin/bash

purge_packages || exit 1
sudo rm -rf /opt/LineRider/ /usr/local/share/applications/LineRider.desktop ~/.local/share/applications/LineRider.desktop /usr/local/bin/linerider || error "Could not remove LineRider files!"

if [ -d ~/Documents/LRA ];then
  warning "To remove all LineRider maps and data, run this command: rm -rf ~/Documents/LRA"
fi
