#!/bin/bash

purge_packages || exit 1
echo "Removing directories..."
rm -rf ~/Screensavers ~/.screensavers ~/.local/share/applications/windows-screensavers.desktop
#Stop existing screensaver.service
if [ -f /etc/systemd/system/screensaver.service ]; then
  echo "Removing systemd service..."
  sudo systemctl stop screensaver
  sudo systemctl disable screensaver
  sudo rm /etc/systemd/system/screensaver.service
fi

echo "Reloading systemd daemon..."
sudo systemctl daemon-reload
