#!/bin/bash

# Download
mkdir $HOME/.Deskreen || error 'Failed to create "$HOME/.Deskreen"!'
cd $HOME/.Deskreen || error 'Failed to cd into .Deskreen!'
wget https://raw.githubusercontent.com/Pi-Apps-Coders/files/main/Deskreen-1.0.1-armv7l.AppImage.zip || error 'Failed to download "Deskreen-1.0.1-armv7l.AppImage.zip" from Mirror!'
unzip -o Deskreen-1.0.1-armv7l.AppImage.zip || error 'Failed to unzip Deskreen-1.0.1-armv7l.AppImage.zip!'

# Install
chmod +x $HOME/.Deskreen/Deskreen-1.0.1-armv7l.AppImage || error 'Failed to make Deskreen-1.0.1-armv7l.AppImage executable!'
echo "#!/bin/bash
$HOME/.Deskreen/Deskreen-1.0.1-armv7l.AppImage --no-sandbox" | sudo tee /usr/local/bin/deskreen &>/dev/null || error 'Failed to create /usr/local/bin/deskreen!'
sudo chmod +x /usr/local/bin/deskreen || error 'Failed to make "/usr/local/bin/deskreen" executable!'
echo "[Desktop Entry]
Name=Deskreen
Comment=Deskreen allows you to use any device on your local network as a secondary screen, through a web browser.
GenericName=Screen sharing app
Exec=deskreen
Icon=${DIRECTORY}/apps/Deskreen/icon-64.png
StartupNotify=true
Terminal=false
Type=Application
Categories=Utility;" > $HOME/.local/share/applications/deskreen.desktop || error 'Failed to create menu shortcut!'

# Cleanup
rm -f $HOME/.Deskreen/Deskreen-1.0.1-armv7l.AppImage.zip || sudo rm -f $HOME/.Deskreen/Deskreen-1.0.1-armv7l.AppImage.zip || error 'Failed to remove $HOME/.Deskreen/Deskreen-1.0.1-armv7l.AppImage.zip'
