#!/bin/bash

purge_packages || exit 1
rm -rf .Deskreen || sudo rm -rf .Deskreen
rm -rf $HOME/.local/share/applications/deskreen.desktop || sudo rm -rf $HOME/.local/share/applications/deskreen.desktop
rm -rf /usr/local/bin/deskreen || sudo rm -rf /usr/local/bin/deskreen 
