#!/bin/bash

purge_packages || exit 1

rm -f ~/.local/share/applications/deskreen.desktop || sudo rm -rf ~/.local/share/applications/deskreen.desktop
rm -f $HOME/.Deskreen/Deskreen-1.0.1-armv7l.AppImage || sudo rm -f $HOME/.Deskreen/Deskreen-1.0.1-armv7l.AppImage
sudo rm -f /usr/local/bin/deskreen
