#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

# Get dependencies
"${DIRECTORY}/pkg-install" "yad" "$(dirname "$0")" || exit 1

rm -rf ~/autostar || error "Failed to first remove autostar folder from $HOME!"
echo "Downloading autostar..."
git clone https://github.com/Botspot/autostar || error "Failed to clone AutoStar repository!"

echo "Running AutoStar setup script..."
~/autostar/main.sh setup || error "AutoStar setup script failed!"

