#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

echo -e "\e[30m\e[107mClick Yes to uninstall WACUP\e[0m"

BOX86_NOBANNER=1 wine ~/'.wine/drive_c/Program Files/WACUP/UninstWACUP.exe'
