#!/bin/bash
echo -e "\e[30m\e[107mClick Yes to uninstall WACUP\e[0m"

BOX86_NOBANNER=1 wine ~/'.wine/drive_c/Program Files/WACUP/UninstWACUP.exe'

while ps aux | grep -v grep | grep wine | grep -q 'WACUP' ;do
  sleep 1
done
