#!/bin/bash
cd ~
mkdir speedtest
wget https://install.speedtest.net/app/cli/ookla-speedtest-1.0.0-armhf-linux.tgz -O ~/speedtest.tgz || error 'Failed to download!'
cd speedtest
tar -xvzf ~/speedtest.tgz || error "failed to extract files!"
rm ~/speedtest.tgz
printf "Creating shortcut..."
echo "[Desktop Entry]
Type=Application
Name=Run Speedtest
Comment=CLI internet speed test
Exec=bash -c $HOME'/speedtest/speedtest;echo -e "\Close this window to exit.";sleep infinity'
Icon=$HOME/pi-apps/apps/SpeedTest-CLI/icon-64.png
Categories=Network;WebBrowser;
Path=$HOME/speedtest
Terminal=true
StartupNotify=false" > ~/.local/share/applications/speedtest.desktop || error "failed to create menu shortcut!"
echo "done"
echo -n "creating /usr/local/bin/speedtest so you can launch from terminal..."
echo "#!/bin/bash
$HOME/speedtest/speedtest \"\$@\"" | sudo tee /usr/local/bin/speedtest >/dev/null
sudo chmod +x /usr/local/bin/speedtest
echo "done"

