#!/bin/bash

purge_packages || exit 1

sudo rm -rf ~/.local/share/applications/speedtest.desktop /usr/share/applications/speedtest.desktop || error "failed to remove menu shortcut!"
sudo rm -rf /usr/local/bin/speedtest ~/speedtest