#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

rm ~/.local/share/applications/speedtest.desktop || error "failed to remove menu shortcut!"
cd ~ 
rm -rf ~/speedtest
