#!/bin/bash

# Install Flatpak
install_packages flatpak || exit 1

# Add the Flathub repository
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo || error 'Failed to add the Flathub repository!'
