#!/bin/bash

version=2.28.0

case "$arch" in
"64") install_packages https://github.com/fastfetch-cli/fastfetch/releases/download/${version}/fastfetch-linux-aarch64.deb || exit 1 ;;
"32") install_packages https://github.com/fastfetch-cli/fastfetch/releases/download/${version}/fastfetch-linux-armv7l.deb || exit 1 ;;
*) error "Failed to detect OS CPU architecture! Something is very wrong." ;;
esac

fastfetch
true
