#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}
install_packages https://github.com/ryanfortner/ryanfortner/releases/download/1002/freetube_0.15.1_armv7l.deb || error "Failed to download/install freetube.deb!"
