#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

#Downloading Deb File For FreeTube
rm -f ~/freetube.deb
wget https://github.com/FreeTubeApp/FreeTube/releases/download/v0.13.0-beta/freetube_0.13.0_arm64.deb -O ~/freetube.deb || error "Failed to download freetube.deb!"

#Installing FreeTube
sudo apt install -y --fix-missing ~/freetube.deb || error "APT failed to install freetube.deb!"

#Removing Deb File
rm -f ~/freetube.deb
