#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}


#Uninstalling FreeTube
sudo apt -y purge freetube || error "Failed to uninstall lightpad"
sudo apt -y autoremove
