#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

echo "downloading discord-electron..."
curl -s https://api.github.com/repos/$1/releases/latest \
| grep "browser_download_url.*armv7l.deb" \
| cut -d : -f 2,3 \
| tr -d \" \
| wget -qi - | error "Failed to download latest release!"
sudo apt -f -y install ./electron-discord-webapp_*_armhf.deb
