#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

version='1.6.1'

echo "Downloading Webcord..."
rm -f ~/webcord_${version}_armhf.deb
wget https://github.com/SpacingBat3/WebCord/releases/download/v${version}/webcord_${version}_armhf.deb

echo "Installing Webcord..."
"${DIRECTORY}/pkg-install" "$HOME/webcord_${version}_armhf.deb" "$(dirname "$0")" || error "Failed to install webcord deb!"

rm -f ~/webcord_${version}_armhf.deb
