#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

gio trash ~/discord-electron > /dev/null
rm -f ~/.local/share/applications/discord.desktop > /dev/null

echo "downloading discord-electron..."
curl -s https://api.github.com/repos/SpacingBat3/electron-discord-webapp/releases/latest \
| grep "browser_download_url.*armv7l.deb" \
| cut -d : -f 2,3 \
| tr -d \" \
| wget -qi - | error "Failed to download latest release!"
sudo apt-get -f -y install ./electron-discord-webapp_*_armhf.deb
