#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

sudo rm -rf /usr/share/discord-linux-armv7l/
sudo rm -f ~/Desktop/discord.desktop
sudo rm -f ~/.local/share/applications/discord.desktop
