#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

killall webcord &>/dev/null && echo "Closing Discord before uninstalling..."

purge_packages || exit 1

exit 0
