#!/bin/bash
purge_packages || exit 1

rm -rf $HOME/.local/share/applications/oomox.desktop $HOME/oomox /usr/local/bin/oomox-gui || sudo rm -rf $HOME/.local/share/applications/oomox.desktop $HOME/oomox /usr/local/bin/oomox-gui 
