#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

wget -O ~/blockpi.deb https://github.com/alienzhangyw/BlockPi/releases/download/v1.2.0/blockpi_1.2.0_armv7l.deb || error 'Failed to download deb file!'

"${DIRECTORY}/pkg-install" "$HOME/blockpi.deb" "$(dirname "$0")" || error "Failed to install blockpi.deb"

rm -f ~/blockpi.deb
