#!/bin/bash

for i in python3-sense-emu sense-hat sense-emu-tools python3-picamera ;do
  if ! package_available $i ;then
    error "User error: The $i package is not available on your system. :( Consider switching to Raspberry Pi OS."
  fi
done

version=1.2.1
install_packages python3-pip https://github.com/alienzhangyw/BlockPi/releases/download/v${version}/blockpi_${version}_armv7l.deb || exit 1
