#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

install_packages "https://apt.raspbian-addons.org/debian/pool/alacritty_0.9.0_arm64.deb"
rm -rf alacritty_0.9.0_arm64.deb || sudo rm -rf alacritty_0.9.0_arm64.deb || error 'Failed to delete alacritty_0.9.0_arm64.deb!'
