#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

purge_packages || exit 1
sudo rm -rf /usr/local/bin/alacritty || error 'Failed to remove symbolic link!'
