#!/bin/bash

cd /tmp
install_packages python3 python3-pyqt5 python3-distutils ffmpeg imagemagick unoconv || exit 1
git_clone https://github.com/ilstam/FF-Multi-Converter || exit 1

cd FF-Multi-Converter || error 'Failed to cd into "FF-Multi-Converter" directory!'
errors="$(sudo python3 setup.py install 2>&1)" || error "Failed to install FF Multi Converter!\nErrors:\n$errors"
sudo rm -rf FF-Multi-Converter
