#!/bin/bash

sudo $HOME/FF-Multi-Converter/uninstall.sh
sudo rm -rf $HOME/FF-Multi-Converter || error 'Failed to remove "FF-Multi-Converter" directory!'

rm -f $HOME/.local/share/applications/ffmulticonverter.desktop

purge_packages || exit 1
