#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

wget https://sonic-pi.net/files/releases/v3.2.2/sonic-pi_3.2.2_4_armhf.deb || error "Failed to download deb file!"

"${DIRECTORY}/pkg-install" "libconfig9 xcompmgr ./sonic-pi_3.2.2_4_armhf.deb" "$(dirname "$0")" || exit 1

rm -f sonic-pi_3.2.2_4_armhf.deb

exit 0
