#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

cd $HOME

wget https://github.com/ksharindam/quartz-browser-qt5/releases/download/v2.3.7/Quartz_Browser-armhf.AppImage -O Quartz_Browser.AppImage

mv -f Quartz_Browser.AppImage /usr/local/bin &> /dev/null || sudo mv -f Quartz_Browser.AppImage /usr/local/bin

echo "[Desktop Entry]
Type=Application
Name=Quartz Browser
Comment=Light weight web browser
Categories=Network;WebBrowser
Exec=/usr/local/bin/Quartz_Browser.AppImage
Icon=$(dirname "$0")/icon-64.png
StartupWMClass=Quartz-Browser" > $HOME/.local/share/applications/quartz-browser.desktop
