#!/bin/bash

version=3.2.3

install_packages https://github.com/Jai-JAP/hyper-arm-builds/releases/download/v${version}/hyper_${version}_arm64.deb || exit 1

status "Moving Menu entry to Accessories..."
sudo sed -i 's/Categories=TerminalEmulator;/Categories=Utility;/' /usr/share/applications/hyper.desktop || error "Failed to fix desktop file!"
