#!/bin/bash
wget 'https://github.com/koendv/openscad-raspberrypi/releases/download/v1.7/OpenSCAD-2021.09.13-armhf.AppImage' -O ~/OpenSCAD.AppImage || error "Failed to download appimage!"

chmod +x ~/OpenSCAD.AppImage || error "Failed to mark as executable!"

enable_module fuse || exit 1

echo "[Desktop Entry]
Name=OpenSCAD
GenericName=The Programmers Solid 3D CAD Modeller
Comment=OpenSCAD is a software for creating 3D CAD objects.
Exec=$HOME/OpenSCAD.AppImage
Icon=$(dirname $0)/icon-64.png
Terminal=false
Type=Application
MimeType=application/x-openscad;
Categories=Graphics;3DGraphics;Engineering;
Keywords=3d;solid;geometry;csg;model;stl;
StartupNotify=true" > ~/.local/share/applications/OpenSCAD.desktop || error "Failed to create menu button!"
