#!/bin/bash
wget https://raw.githubusercontent.com/RichardMidnight/pi-safe/main/pisafe -O pisafe || error "Failed to download!"

bash pisafe install -y || error "failed to install PiSafe!"
rm -f ~/pisafe
exit 0
