#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

wget https://raw.githubusercontent.com/RichardMidnight/pi-safe/main/pisafe -O pisafe || error "Failed to download!"

bash pisafe install -y || error "failed to install PiSafe!"
rm -f ~/pisafe
exit 0
