#!/bin/bash


mkdir -p ~/.love_games/friday_night_funkin_rewritten && cd ~/.love_games/friday_night_funkin_rewritten || error 'Failed to Create & Enter Directory!'
wget https://github.com/HTV04/funkin-rewritten/releases/download/v1.1.0-beta.2/funkin-rewritten-lovefile.zip || error 'Failed Download the zip!'
unzip funkin-rewritten-lovefile.zip || error 'Failed to Extract the zip!'
rm -f funkin-rewritten-lovefile.zip || error 'Failed to Remove the zip!'

# Create the .desktop file in ~/.local/share/applications
mkdir -p ~/.local/share/applications

echo "[Desktop Entry]
Type=Application
Exec=love $HOME/.love_games/friday_night_funkin_rewritten/funkin-rewritten.love
Hidden=false
NoDisplay=false
Name=Friday Night Funkin' Rewritten
Icon=$(dirname "$0")/icon-64.png
Categories=Game" > ~/.local/share/applications/fnfr.desktop

# Install some packages that are necessary to run this app - no need for "error", as the install_packages function already handles errors.

install_packages love || exit 1
