#!/bin/bash
sudo wget https://ryanfortner.github.io/box64-debs/box64.list -O /etc/apt/sources.list.d/box64.list
if [ $? != 0 ];then
  sudo rm -f /etc/apt/sources.list.d/box64.list
  error "Failed to add box64.list file!"
fi

sudo rm -f /usr/share/keyrings/box64-debs-archive-keyring.gpg
curl -fsSL https://ryanfortner.github.io/box64-debs/KEY.gpg | sudo gpg --dearmor -o /usr/share/keyrings/box64-debs-archive-keyring.gpg

if [ $? != 0 ];then
  sudo rm -f /etc/apt/sources.list.d/box64.list
  error "Failed to add KEY.gpg to APT keyring!"
fi

install_packages box64 || exit 1
