#!/bin/bash

if dpkg -l box64 &>/dev/null ;then
  sudo apt purge -y --allow-change-held-packages box64
fi

sudo wget https://raw.githubusercontent.com/ryanfortner/box64-debs/4a4bf6e7933b237de75712810240ab301a50f0a8/box64.list -O /etc/apt/sources.list.d/box64.list
if [ $? != 0 ];then
  sudo rm -f /etc/apt/sources.list.d/box64.list
  error "Failed to add box64.list file!"
fi

sudo rm -f /usr/share/keyrings/box64-debs-archive-keyring.gpg
curl -fsSL https://ryanfortner.github.io/box64-debs/KEY.gpg | sudo gpg --dearmor -o /usr/share/keyrings/box64-debs-archive-keyring.gpg

if [ $? != 0 ];then
  sudo rm -f /etc/apt/sources.list.d/box64.list
  error "Failed to add KEY.gpg to APT keyring!"
fi

# obtain SOC_ID
get_model
if [[ "$SOC_ID" == "tegra-x1" ]] || [[ "$SOC_ID" == "tegra-x2" ]]; then
  install_packages box64-tegrax1 || exit 1
elif [[ "$SOC_ID" == "rk3399" ]]; then
  install_packages box64-rk3399 || exit 1
elif [[ "$SOC_ID" == "bcm2711" ]]; then
  install_packages box64-rpi4arm64 || exit 1
elif cat /proc/cpuinfo | grep -q aes; then
  warning "There is no box64 pre-build for your device $SOC_ID $model"
  warning "Installing the generic arm box64 build as a fallback (crypto extensions enabled)"
  install_packages box64-generic-arm || exit 1
else
  warning "There is no box64 pre-build for your device $SOC_ID $model"
  warning "Installing the RPI4 tuned box64 build as a fallback (no crypto extensions enabled)"
  install_packages box64-rpi4arm64 || exit 1
fi
