#!/bin/bash
purge_packages || exit 1

sudo rm -f /etc/apt/sources.list.d/box64.list || error "Failed to remove repo!"

sudo apt-key del "DF9A 1B85 23C3 2EEE FF2A  6CDA 7759 FA1D 9FEC AC9E" || error "Failed to remove GPG key!"
