#!/bin/bash

purge_packages || exit 1

#remove deprecated files
sudo rm -f /etc/apt/sources.list.d/home:stevenpusser.list /etc/apt/trusted.gpg.d/home_stevenpusser.gpg

rm_external_repo "stevenpusser"
