#!/bin/bash

cd /tmp
wget -O renoise-arm64.tar.gz "https://files.renoise.com/demo/Renoise_3_4_1_Demo_Linux_arm64.tar.gz" || exit 1
status "Extracting Renoise..."
tar -xf renoise-arm64.tar.gz || error "Failed to extract Renoise!"
cd Renoise_3_4_1_Demo_Linux_arm64 || error "Failed to cd into 'Renoise_3_4_1_Demo_Linux_arm64'!"
status_green "Done!"
status "Installing Renoise..."
chmod +x install.sh || error "Failed to set 'install.sh' as execuable!"
sudo ./install.sh || error "Failed to install Renoise with 'install.sh'!"
status_green "Done!"
status "Cleaning up..."
cd ../
rm -rf Renoise_3_4_1_Demo_Linux_arm64 renoise-arm64.tar.gz
status_green "Done!"
