#!/bin/bash

cd /tmp
wget "https://raw.githubusercontent.com/Crilum/stuff/main/install.sh" || error "Failed to download 'install.sh'!"
chmod +x install.sh || error "Failed to make 'install.sh' executable!"
sudo ./install.sh -u
if [ "$?" == "1" ]; then
  status "Uninstall finished!"
elif [ "$?" == "0" ]; then
  error "Failed to uninstall Renoise with 'install.sh -u'"
else
  warning "Unknown status code... Renoise may or may not have uninstalled successfully."
fi
