#!/bin/bash

#Remove any qemu packages first to prevent conflicting packages
apt_lock_wait
sudo apt purge -y --autoremove 'qemu*' sgabios || true

install_packages https://github.com/ryanfortner/qemu-arm-builds/releases/download/6.1.50/qemu-6.1.50-arm64.deb || exit 1
