#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

cd $HOME
#remove 5.2.90 deb if present
rm -f ./qemu-5.2.90-armhf.deb
#remove 5.2.92 deb if present
rm -f ./qemu-5.2.92-armhf.deb
#Download QEMU
wget https://archive.org/download/macos_921_qemu_rpi/qemu-5.2.92-armhf.deb || error 'Failed to Download QEMU!'
#Install QEMU
sudo apt install -fy ./qemu-5.2.92-armhf.deb || error 'Failed to install QEMU!'
rm -f qemu-5.2.92-armhf.deb
