#!/bin/bash

#Remove any qemu packages first to prevent conflicting packages
apt_lock_wait
sudo apt purge -yqq --autoremove qemu* sgabios &>/dev/null

install_packages https://github.com/ryanfortner/qemu-arm-builds/releases/download/6.1.50/qemu-6.1.50-armhf.deb || exit 1
