#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}


git clone https://github.com/open-sorcerer64/stacer-on-pi.git || error 'failed to clone repository'

cd $HOME/stacer-on-pi

"${DIRECTORY}/pkg-install" "libqt5charts5 $HOME/stacer-on-pi/fonts-inter.deb $HOME/stacer-on-pi/stacer.deb" "$(dirname "$0")" || error 'Failed to install Stacer.'

sudo rm -rf  $HOME/stacer-on-pi || exit 1 
