#!/bin/bash

#$1 is an action, like install
#$2 is app name, like Arduino

DIRECTORY="$(readlink -f "$(dirname "$0")")"

function error {
  echo -e "\e[91m$1\e[39m"
  exit 1
}

if [ -z "$1" ];then
  error "You need to specify an operation, and in most cases, which app to operate on."
fi

set -a #make all functions in the api available to apps
source "${DIRECTORY}/api" || error "failed to source ${DIRECTORY}/api"

#remove old mcpi repositories - this runonce is here so that terminal-only users will still receive the fix.
(runonce <<"EOF"
  if [ -f /etc/apt/sources.list.d/mcpi-revival.list ] && cat /etc/apt/sources.list.d/mcpi-revival.list | grep -qF 'https://mcpirevival.tk/mcpi-packages' ;then
    echo 'deb [trusted=yes] https://mcpi-revival.github.io/mcpi-packages/ buster main' | sudo tee /etc/apt/sources.list.d/mcpi-revival.list
  elif [ -f /etc/apt/sources.list.d/mcpi-revival.list ] && cat /etc/apt/sources.list.d/mcpi-revival.list | grep -qF 'https://mcpi-revival.github.io/mcpi-packages/debs' ;then
    echo 'deb [trusted=yes] https://mcpi-revival.github.io/mcpi-packages/ buster main' | sudo tee /etc/apt/sources.list.d/mcpi-revival.list
  fi
  if [ -f /etc/apt/sources.list.d/Alvarito050506_mcpi-devs.list ];then
    sudo rm -f /etc/apt/sources.list.d/Alvarito050506_mcpi-devs.list
  fi
  
  if dpkg -l box86-no-binfmt-restart &>/dev/null ;then
    sudo apt purge -y box86-no-binfmt-restart
    sudo apt update
    sudo apt install -y box86
  fi
EOF
) &>/dev/null

#check for internet connection
errors="$(command wget --spider https://github.com 2>&1)"
if [ $? != 0 ];then
  error "No internet connection! (github.com failed to respond)\nErrors:\n$errors"
fi

#Silently re-download repo if github repository is over 3 months out of date
{
command -v curl >/dev/null || sudo apt install -y curl
upstream_git_date="$(curl https://api.github.com/repos/Botspot/pi-apps/commits/master 2>&1 | grep '"date":' | tail -n 1 | sed 's/"date"://g' | xargs date +%s -d 2>/dev/null)"
current_git_date="$(cd "$DIRECTORY"; git show -s --format=%ct)"

if [[ "$upstream_git_date" =~ ^[0-9]+$ ]] && ([ -z "$current_git_date" ] || [ "$upstream_git_date" -gt $(($current_git_date + 7776000)) ]);then
  yad --window-icon="${DIRECTORY}/icons/logo.png" --width=500 --no-buttons --center --title="Auto-updating Pi-Apps" \
    --text="Your Pi-Apps installation is somehow 3 months out-of-date."$'\n'"Reinstalling Pi-Apps and saving the old version to ${DIRECTORY}-3-months-old..." &
  yadpid=$!
  
  clear
  echo -e "\nYour Pi-Apps installation is somehow 3 months out-of-date.\nReinstalling Pi-Apps and saving the old version to ${DIRECTORY}-3-months-old...\n\n" 1>&2
  cd $HOME
  rm -rf ~/pi-apps-forced-update
  command -v git >/dev/null || sudo apt install -y git
  git clone "$(cat "${DIRECTORY}/etc/git_url")" pi-apps-forced-update 1>&2 && \
  cp -af "${DIRECTORY}/data" ~/pi-apps-forced-update && \
  mv -f "$DIRECTORY" "${DIRECTORY}-3-months-old" && \
  mv -f ~/pi-apps-forced-update "${DIRECTORY}"
  sleep 10
  
  kill $yadpid 2>/dev/null
  
  #run new manage script in background
  "{DIRECTORY}/manage" "$@"
  exit $?
fi
}

mkdir -p "${DIRECTORY}/data/status" "${DIRECTORY}/data/update-status" "${DIRECTORY}/logs"

#remove week-old logfiles
find "${DIRECTORY}/logs" -type f -mtime +7 -exec rm -f {} \; &>/dev/null &

#check if hardware and OS is supported
if is_supported_system >/dev/null;then
  supported=yes
else
  supported=no
fi

if [ "$1" == 'multi-uninstall' ] || [ "$1" == 'multi-install' ];then
  
  if [ "$1" == 'multi-uninstall' ];then
    action=uninstall
  elif [ "$1" == 'multi-install' ];then
    action=install
  fi
  
  app_list="$2" #newline-separated list of apps to install/uninstall
  
  #if trying to install an already-installed app, or trying to uninstall and already-uninstalled app, ask for confirmation
  IFS=$'\n'
  for app in $app_list ;do
    if [ "$(app_status "${app}")" == "${action}ed" ];then
      yad --text="<b>$app</b> is already ${action}ed. Are you sure you want to $action it again?" \
        --text-align=center --center --title='Quick question' --window-icon="${DIRECTORY}/icons/logo.png" \
        --button=No!"${DIRECTORY}/icons/exit.png":1 --button=Yes!"${DIRECTORY}/icons/check.png":0
      
      if [ $? != 0 ];then
        #user clicked No, so remove the app from list
        app_list="$(echo "$app_list" | grep -vx "$app")"
      fi
    fi
  done
  
  #Check if any apps are updatable and ask user if they really want to INSTALL an outdated version. (This is skipped if uninstalling apps)
  if [ "$action" == install ];then
    
    #check for updates in background, so if user chooses "Yes", the updater will be guaranteed to have the app listed
    "${DIRECTORY}/updater" set-status &>/dev/null &
    
    for app in $app_list ;do
      #determine the filename for the app's script to be run
      if [ $action == install ];then
        script_name_cpu="$(script_name_cpu "$app")"
      fi
      #if the app-script doesn't match version in update folder
      if [ -f "${DIRECTORY}/update/pi-apps/apps/${app}/${script_name_cpu}" ] && ! diff "${DIRECTORY}/update/pi-apps/apps/${app}/${script_name_cpu}" "${DIRECTORY}/apps/${app}/${script_name_cpu}" -q >/dev/null ;then
        yad --text="Hold up..."$'\n'"<b>$app</b>'s $script_name_cpu script does not match the online version. Either you are about to install an outdated version, or you've made changes to the script yourself."$'\n\n'"Would you like to update $app before installing it?" \
          --text-align=center --center --title='Quick question' --window-icon="${DIRECTORY}/icons/logo.png" --width=400 \
          --button=No!"${DIRECTORY}/icons/forward.png":1 --button=Yes!"${DIRECTORY}/icons/download.png":0
        
        if [ $? == 0 ];then
          #if user clicked Yes, run the updater and avoid launching a second terminal
          use_terminal=0 "${DIRECTORY}/updater" gui fast
          
          #now that the api script was potentially updated, source it again to get new functions
          source "${DIRECTORY}/api" || error "failed to source ${DIRECTORY}/api"
        fi
      fi
    done
  fi
  
  #install/uninstall one app at a time. If it fails then add the app to the list of failed apps
  failed_apps=''
  for app in $app_list ;do
    
    "${DIRECTORY}/manage" $action "$app"
    if [ $? != 0 ];then
      #this app failed to install - add it to the list of failed apps
      failed_apps="$failed_apps
$app"
    fi
  done
  failed_apps="${failed_apps:1}" #remove first blank newline
  
  #diagnose every failed app's logfile
  for app in $(echo "$failed_apps") ;do
    logfile="$(get_logfile "$app")"
    #given the app's logfile, categorize the error and set the error_type variable
    diagnosis="$(log_diagnose "$logfile")"
    
    error_type="$(echo "$diagnosis" | head -n1)" #first line of diagnosis is the type of error
    error_caption="$(echo "$diagnosis" | tail -n +2)" #subsequent lines of diagnosis are caption(s)
    
    #set the window-text
    if [ "$error_type" == unknown ];then
      text="<b>${app^}</b> failed to $action for an <b>unknown</b> reason."
    else
      text="<b>${app^}</b> failed to $action because Pi-Apps encountered $([[ "$error_type" == [aeiou]* ]] && echo an || echo a) <b>$error_type</b> error."
    fi
    
    #if the error_type is NOT system, internet, or package, AND the app exists in the official Pi-Apps repository, AND the app-script has not been modified, AND the system setup is supported, AND the app is not a package-app, then enable the "Send report button"
    if [ "$(app_type "$app")" == package ];then
      text+=$'\n'"Error report cannot be sent because this \"app\" is really just a shortcut to $action a Debian package. It's not a problem that Pi-Apps can fix."
    elif [[ "$error_type" =~ ^(system|internet|package)$ ]];then
      text+=$'\n'"Error report cannot be sent because this is not an issue with Pi-Apps."
    elif ! list_apps online | grep -q "$app" ;then
      text+=$'\n'"Error report cannot be sent because this app is not in the official repository."
    elif [ "$action" == install ] && [ "$(app_type "$app")" == standard ] && [ "$(sha256sum "${DIRECTORY}/apps/${app}/$(script_name_cpu "$app")" | awk '{print $1}')" != "$(sha256sum "${DIRECTORY}/update/pi-apps/apps/${app}/$(script_name_cpu "$app")" | awk '{print $1}')" ];then
      text+=$'\n'"Error report cannot be sent because this app is not the official version."
    elif [ "$action" == uninstall ] && [ "$(app_type "$app")" == standard ] && [ "$(sha256sum "${DIRECTORY}/apps/${app}/uninstall" | awk '{print $1}')" != "$(sha256sum "${DIRECTORY}/update/pi-apps/apps/${app}/uninstall" | awk '{print $1}')" ];then
      text+=$'\n'"Error report cannot be sent because this app does not match the official version."
    elif [ "$supported" == no ];then
      text+=$'\n'"Error report cannot be sent because your system is unsupported."
    else
      #if all of the above checks evaluate to FALSE, then display the "Send report" button.
      send_button=(--button='Send report'!"${DIRECTORY}/icons/upload.png":2)
    fi
    
    #display support links, depending on if this was a package-app or a script-app
    if [ "$(app_type "$app")" == package ];then
      text+=$'\n'"As this is an APT error, consider Googling the errors or asking for help in the <a href=\"https://forums.raspberrypi.com\">Raspberry Pi Forums</a>."
    else
      text+=$'\n'"Support is available on <a href=\"https://discord.gg/RXSTvaUvuu\">Discord</a> and <a href=\"https://github.com/Botspot/pi-apps/issues/new/choose\">Github</a>."
    fi
    
    #if the error_caption is empty, display logfile instead
    if [ -z "$error_caption" ];then
      text+=$'\n'"You can view the $(echo "$action" | sed 's/install/installation/g') output below."
      error_caption="$(cat "$logfile")"
    else
      text+=$'\n'"Below, Pi-Apps explains what went wrong and how you can fix it."
    fi
    
    echo "$error_caption" | yad "${yadflags[@]}" --text-info --width=700 --height=300 --title="Error occured when ${action}ing $app" \
      --image="${DIRECTORY}/icons/error.png" --image-on-top \
      --text="$text" --fontname=12 \
      --button='View log'!"${DIRECTORY}/icons/log-file.png"!"Review the output from when <b>$app</b> tried to $action.":"bash -c 'view_file "\""$logfile"\""'" \
      "${send_button[@]}" \
      --button=Close:1
    button=$?
    
    if [ $button == 2 ];then
      #send error log
      send_error_report "$logfile"
    fi
  done
  
  if [ ! -z "$failed_apps" ];then
    exit 1
  fi
  
elif [ "$1" == 'install-if-not-installed' ];then
  
  #if not installed
  if [ "$(app_status "$2")" != installed ];then
    #install it
    "${DIRECTORY}/manage" install "$2" || exit 1
  fi
  
elif [ "$1" == 'install' ] || [ "$1" == 'uninstall' ];then
  #for this operation, a program name must be specified.
  app="$2"
  if [ -z "$app" ];then
    error "For this operation, you must specify which app to operate on."
  elif [ ! -d "${DIRECTORY}/apps/$app" ];then
    error "${DIRECTORY}/apps/$app does not exist!"
  fi
  
  if [ "$1" == install ];then
    mode=install
  else
    mode=uninstall
  fi
  
  #ensure not a disabled app
  if [ "$mode" == install ] && [ "$(app_status "${app}")" == 'disabled' ];then
    warning "Not installing the $app app. IT IS DISABLED."
    exit 0
  fi
  
  #display warning if hardware and os is unsupported
  if [ "$supported" == no ];then
    warning "YOUR SYSTEM IS UNSUPPORTED:\n$(is_supported_system)"
    sleep 1
    echo -e "\e[103m\e[30mThe ability to send error reports has been disabled.\e[39m\e[49m"
    sleep 1
    echo -e "\e[103m\e[30mWaiting 10 seconds... (To cancel, press Ctrl+C or close this terminal)\e[39m\e[49m"
    sleep 10
  fi
  
  #determine path for log file to be created
  logfile="${DIRECTORY}/logs/${mode}-incomplete-${app}.log"
  if [ -f "$logfile" ] || [ -f "$(echo "$logfile" | sed 's+-incomplete-+-success-+g')" ] || [ -f "$(echo "$logfile" | sed 's+-incomplete-+-fail-+g')" ];then
    #append a number to logfile's file-extension if the original filename already exists
    i=1
    while true;do
      #if variable $i is 2, then example newlogfile value: /path/to/install-Discord.log2
      newlogfile="$logfile$i"
      if [ ! -f "$newlogfile" ] && [ ! -f "$(echo "$newlogfile" | sed 's+/-incomplete-+-success-+g')" ] && [ ! -f "$(echo "$newlogfile" | sed 's+-incomplete-+-fail-+g')" ];then
        logfile="${newlogfile}"
        break
      fi
      i=$((i+1))
    done
  fi
  
  #analytics
  bitly_link "$app" "$mode" &
  
  #if this app has scripts, determine which script to run
  if [ "$(app_type "$app")" == standard ];then
    if [ "$mode" == install ];then
      scriptname="$(script_name_cpu "$app")" #will be install, install-32, or install-64
      [ -z "$scriptname" ] && error "It appears $app does not have an install-${arch} script suitable for your ${arch}-bit OS."
    else #uninstall mode
      scriptname=uninstall
    fi
    appscript=("${DIRECTORY}/apps/${app}/${scriptname}")
    chmod u+x "$appscript" &>/dev/null
  #if this app just lists a package-name, set the appscript to install that package
  else
    appscript=(bash -c -o pipefail "apt_lock_wait ; sudo -E apt $(echo "$action" | sed 's/uninstall/purge --autoremove/g') -yf $(cat "${DIRECTORY}/apps/$app/packages") 2>&1 | less_apt")
  fi
  
  status "${mode^}ing \e[1m${app}\e[0m\e[96m..." | tee -a "$logfile"
  echo
  cd $HOME
  if [[ "$3" == "update" ]]; then
    script_input="update"
  else
    script_input=""
  fi
  nice "${appscript[@]}" "$script_input" &> >(tee -a "$logfile")
  exitcode="${PIPESTATUS[0]}"
  
  #if app succeeded
  if [ $exitcode == 0 ];then
    status_green "\n${mode^}ed ${app} successfully." | tee -a "$logfile"
    echo "${mode}ed" > "${DIRECTORY}/data/status/${app}"
    
    format_logfile "$logfile" #remove escape sequences from logfile
    mv "$logfile" "$(echo "$logfile" | sed 's+-incomplete-+-success-+g')" #rename logfile to indicate it was successful
    
  else #if app failed to install/uninstall

    #remove dummy deb if app failed to install (to avoid dummy debs being left on a users install for broken apps)
    package_name="$(app_to_pkgname "$app")"
    if [[ ${mode} == "install" ]] && [[ "$(app_type "$app")" == standard ]] && package_installed "$package_name"; then
      if [[ "$script_input" == "update" ]]; then
        #if install failed as part of an update, don't autoremove the packages, only purge the dummy deb
        output="$(sudo -E apt purge -y $package_name 2>&1 | less_apt | tee /dev/stderr)"
        if [ $? != 0 ];then
          echo "$output" | tee -a "$logfile"
          warning "Failed to purge dummy deb ($package_name)" 2>&1 | tee -a "$logfile"
        else
          echo "$output" | tee -a "$logfile"
        fi
        unset output
      else
        #install and not update failed, run purge_packages
        purge_packages | tee -a "$logfile"
      fi
    fi
    unset package_name

    echo -e "\n\e[91mFailed to ${mode} ${app}!\e[39m
\e[40m\e[93m\e[5m◢◣\e[25m\e[39m\e[49m\e[93mNeed help? Copy the \e[1mENTIRE\e[0m\e[49m\e[93m terminal output or take a screenshot.
Please ask on Github: \e[94m\e[4mhttps://github.com/Botspot/pi-apps/issues/new/choose\e[24m\e[93m
Or on Discord: \e[94m\e[4mhttps://discord.gg/RXSTvaUvuu\e[0m" | tee -a "$logfile"
    
    #set the app's status to 'corrupted' if the diagnostics determine the error is NOT internet or system or package, AND if the app is a script-type app
    if ! [[ "$(log_diagnose "$logfile" | head -n1)" =~ ^(system|internet|package)$ ]] && [ "$(app_type "$app")" == standard ];then
      echo "corrupted" > "${DIRECTORY}/data/status/${app}"
    fi
    
    format_logfile "$logfile" #remove escape sequences from logfile
    mv "$logfile" "$(echo "$logfile" | sed 's+-incomplete-+-fail-+g')" #rename logfile to indicate it was unsuccessful
  fi
 
  #if the app is a package, set its status to whatever dpkg thinks it is
  if [ "$(app_type "$app")" == package ];then
    refresh_pkgapp_status "$app"
  fi
  
  #exit the manage script with the same exit-code of the app's script
  exit $exitcode
  
elif [ "$1" == 'update' ];then
  #UPDATE
  #for this operation, a program name must be specified.
  app="$2"
  if [ -z "$app" ];then
    error "For this operation, you must specify which app to operate on."
  fi
  
  #detect which installation script exists and get the hash for that one
  scriptname="$(script_name_cpu "$app")"
  [ $? == 1 ] && exit 1
  
  status "Updating \e[1m${app}\e[0m\e[96m..."
  echo
  
  #HIDDEN FEATURE - if $3 equals nofetch, then don't download github repo. Useful for updating multiple apps at maximum speed
  if [ "$3" == 'nofetch' ] && [ -d "${DIRECTORY}/update" ];then
    true
  else
    rm -rf "${DIRECTORY}/update" && mkdir "${DIRECTORY}/update" && cd "${DIRECTORY}/update" || error "failed to enter the update directory!"
    git clone --depth=1 "$(cat "${DIRECTORY}/etc/git_url")" || error "failed to clone repository!"
  fi
  
  echo
  
  newinstallhash="$(sha1sum "${DIRECTORY}/update/pi-apps/apps/${app}/${scriptname}" 2>/dev/null | awk '{print $1}')"
  oldinstallhash="$(sha1sum "${DIRECTORY}/apps/${app}/${scriptname}" 2>/dev/null | awk '{print $1}')"
  
  #echo -e "newinstallhash: $newinstallhash\noldinstallhash: $oldinstallhash"
  #echo -e "newhash: $newhash\noldhash: $oldhash"
  
  if diff -r "${DIRECTORY}/apps/${app}" "${DIRECTORY}/update/pi-apps/apps/${app}" -q >/dev/null;then
    status_green "$app is identical to the online version. Nothing to do!"
    echo
    exit 0
  fi
  #else
  status_green "$app is not identical to the online version."
  installback=no
  
  echo
  
  #if install script was changed                                                    #if installed already
  if [ "$newinstallhash" != "$oldinstallhash" ] && [ "$(app_status "${app}")" == 'installed' ];then
    installback=yes
    status "$app's install script has been updated. Reinstalling $app..."
    #uninstall it using a recursive script instance
    #report to the app uninstall script that this is an uninstall for the purpose of updating by passing "update"
    "${DIRECTORY}/manage" uninstall "$app" "update"
    
    #fix edge case: if app is installed but uninstall script doesn't exist somehow, then pretend app was uninstalled so that the reinstall later will happen noninteractively
    if [ "$(app_status "$app")" == installed ];then
      echo 'uninstalled' > "${DIRECTORY}/data/status/${app}"
    fi
  fi
  
  #move old program to trash
  gio trash "${DIRECTORY}/apps/${app}" 2>/dev/null
  #failsafe
  [ -d "${DIRECTORY}/apps/${app}" ] && rm -rf "${DIRECTORY}/apps/${app}"
  
  #copy new version from update/ to apps/
  cp -rf "${DIRECTORY}/update/pi-apps/apps/${app}" "${DIRECTORY}/apps/${app}"
  
  if [ "$installback" == 'yes' ];then
    #install it using a recursive script instance
    "${DIRECTORY}/manage" install "$app"
    if [ $? != 0 ]; then
      failed=true
    fi
  fi
  
  if [ "$failed" == 'true' ]; then
    echo -e "\e[91mFailed to update ${app}.\e[0m"
  else
    status_green "${app} was updated successfully."
  fi
  echo
  
elif [ "$1" == 'check-all' ];then
  
  #CHECK-ALL
  #for this operation, a program name cannot be specified.
  
  #hidden flags
  installedonly=0
  if [ "$2" == 'installedonly' ];then
    # If $2 is 'installedonly', then only check for updates for those apps that are installed
    installedonly=1
  fi #end of checking for hidden flags
  
  echo -n "Checking for online changes... " 1>&2
  
  #if the updater script exists in update folder, then just git pull to save time
  if [ -f "${DIRECTORY}/update/pi-apps/updater" ];then
    cd "${DIRECTORY}/update/pi-apps"
    git pull -q 1>&2 || rm -rf "${DIRECTORY}/update"
  fi | grep -v "Already up to date." 1>&2
  
  #re-check and if updater script does not exist then do a git clone
  if [ ! -f "${DIRECTORY}/update/pi-apps/updater" ];then
    rm -rf "${DIRECTORY}/update"
    mkdir -p "${DIRECTORY}/update" && cd "${DIRECTORY}/update" || error "failed to enter the update directory!"
    git clone --depth=1 "$(cat "${DIRECTORY}/etc/git_url")" -q 1>&2 || error "failed to clone repository to the update directory!"
  fi
  
  echo "Done" 1>&2
  
  if [ $installedonly == 1 ];then
    #installedonly flag enabled. Remove apps that are uninstalled, disabled, or corrupted
    applist="$(list_apps installed)"
  else
    #installedonly flag disabled, so use entire combined list of apps, both local and online
    applist="$(list_apps all)"
  fi
  
  #echo "App list: $applist" 1>&2
  
  updatable=''
  IFS=$'\n'
  for app in $applist
  do
    echo -en "Scanning apps... $app\e[0K\r" 1>&2
    
    if [ ! -d "${DIRECTORY}/apps/${app}" ];then
      #add to updatable list
      updatable="${updatable}
${app}"
      
    elif [ ! -d "${DIRECTORY}/update/pi-apps/apps/${app}" ];then
      #app only exists locally
      true
      
    elif ! diff -r "${DIRECTORY}/apps/${app}" "${DIRECTORY}/update/pi-apps/apps/${app}" -q >/dev/null ;then
      #if app hashes don't match, add to updatable list
      updatable="${updatable}
${app}"
    fi
  done 
  
  #remove initial newline character
  updatable="${updatable:1}"
  
  echo -e "Scanning apps... Done\e[0K" 1>&2
  
  echo "${updatable}"
elif [ "$1" == 'update-all' ];then

  echo

  #UPDATE-ALL
  #for this operation, a program name cannot be specified.
  IFS=$'\n'
  updatable="$("${DIRECTORY}/manage" check-all)"
  echo "Updatable: ${updatable}EOU"
  for updateapp in $updatable
  do
    status "updating $updateapp"
    #update it using a recursive script instance
    echo "${DIRECTORY}/manage update $updateapp"
    "${DIRECTORY}/manage" update "$updateapp" || exit 1
  done
  status_green "Operation completed successfully!"
else
  error "Invalid argument. Allowed values: 'install', 'multi-install', 'install-if-not-installed', 'uninstall', 'multi-uninstall', 'update','update-all', or 'check-all'."
fi
