#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

cd $HOME

#remove old deb (if exists)
rm -f gh*linux_arm64.deb
#download
wget -O gh.deb https://github.com/cli/cli/releases/download/v1.12.1/gh_1.12.1_linux_arm64.deb || error 'Failed to download github-cli!'
#install
sudo apt -fy install ./gh.deb || error "Failed to install gh!"
#clean up
rm -f gh.deb
