#!/bin/bash

install_packages https://github.com/ryanfortner/linux-wifi-hotspot-arm/releases/download/v4.4.0/linux-wifi-hotspot_4.4.0_arm64.deb || exit 1

#Raspberry Pi  WiFi module may be disabled by the panel, and if it is, this program will fail. When launching, first unblock wifi.
if [ -f /usr/sbin/rfkill ] && ! grep -q rfkill /usr/share/applications/wihotspot.desktop ;then
  sudo sed -i "s+^Exec=sh -c '+Exec=sh -c '/usr/sbin/rfkill unblock wifi; +" /usr/share/applications/wihotspot.desktop
fi