#!/bin/bash

#Allow packages required by this app to be uninstalled
purge_packages || exit 1

# Uninstall Linux Wifi Hotspot
sudo rm -rf /usr/share/pixmaps/wihotspot.png /usr/share/icons/hicolor/48x48/apps/wihotspot.png \
/usr/share/icons/hicolor/64x64/apps/wihotspot.png /usr/share/icons/hicolor/256x256/apps/wihotspot.png \
/usr/share/icons/hicolor/512x512/apps/wihotspot.png /usr/share/icons/hicolor/scalable/apps/wihotspot.svg \
/usr/share/applications/wihotspot.desktop /usr/share/polkit-1/rules.d/90-org.opensuse.policykit.wihotspot.rules \
/usr/share/polkit-1/actions/org.opensuse.policykit.wihotspot.policy /usr/bin/wihotspot /usr/bin/wihotspot-gui \
/etc/create_ap.conf /usr/lib/systemd/system/create_ap.service /lib/systemd/system/create_ap.service /usr/share/bash-completion/completions/create_ap \
/usr/share/doc/create_ap/README.md /usr/bin/create_ap

# remove /usr/lib/systemd/system if empty, older debian/ubuntu versions do not use this location and having it present causes issues with other programs
[ ! "$(ls -A /usr/lib/systemd/system)" ] && sudo rm -rf /usr/lib/systemd/system

exit 0
