#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

sudo rm -rf "${HOME}/Teams" "${HOME}/.local/share/applications/Teams.desktop" "${HOME}/Desktop/Teams.desktop" 2> /dev/null

exit 0
