#!/bin/bash

if ! grep -q </proc/device-tree/compatible 'bcm2712\|bcm2711\|bcm2837\|bcm2836\|bcm2835'; then
  error "User error (reporting allowed): Sorry. PiKISS is only available for Raspberry Pi boards."
fi

status "\nPiKISS\n======\n\nInstalling at ${HOME}/piKiss. Please wait...\n"
install_packages dialog || exit 1
git_clone -b master https://github.com/jmcerrejon/PiKISS.git piKiss || exit 1

echo -e "[Desktop Entry]\nName=PiKISS\nComment=A bunch of scripts with menu to make your life easier\nExec=${HOME}/piKiss/piKiss.sh\nIcon=${HOME}/piKiss/icons/pikiss_32.png\nTerminal=true\nType=Application\nCategories=ConsoleOnly;Utility;System;\nPath=${HOME}/piKiss/" > ~/.local/share/applications/pikiss.desktop

status_green "PiKISS installed!
=================

To run: Menu -> System Tools -> PiKiss
To run in a terminal: ~/piKiss/piKiss.sh"
