#!/bin/bash

if ! package_installed geany; then
  error "User error: Geany is not installed, these themes are useless to you."
fi

#get theme files
git_clone --depth 1 https://github.com/geany/geany-themes || exit 1

#copy theme files
mkdir -p ~/.config/geany/colorschemes
cp -a ~/geany-themes/colorschemes/. ~/.config/geany/colorschemes || error "Failed to copy colorschemes to $HOME/.config/geany/colorschemes"

#Make geany use spyder-dark color scheme
if [ -f ~/.config/geany/geany.conf ] && [ ! -z "$(cat ~/.config/geany/geany.conf)" ];then
  sed -i 's/color_scheme=.*/color_scheme=spyder-dark.conf/g' ~/.config/geany/geany.conf
  sed -i 's/^color_scheme=$/color_scheme=spyder-dark.conf/g' ~/.config/geany/geany.conf
else
  echo -e '[geany]\ncolor_scheme=spyder-dark.conf' > ~/.config/geany/geany.conf
fi

#clean up
if pidof geany -q; then
  
  echo -e "\nThis script was unable to change Geany's config file, because Geany is already running.\nPlease close Geany."
  
  while pidof geany -q;do
    sleep 1
    echo -n '.'
  done
  echo
  
  #Make geany use spyder-dark color scheme
  if [ -f ~/.config/geany/geany.conf ] && [ ! -z "$(cat ~/.config/geany/geany.conf)" ];then
    sed -i 's/color_scheme=.*/color_scheme=spyder-dark.conf/g' ~/.config/geany/geany.conf
    sed -i 's/^color_scheme=$/color_scheme=spyder-dark.conf/g' ~/.config/geany/geany.conf
  else
    echo -e '[geany]\ncolor_scheme=spyder-dark.conf' > ~/.config/geany/geany.conf
  fi
  
fi

#tell user where to change theme
status "Added $(ls  ~/geany-themes/colorschemes/ | wc -l) themes.\nYou can change theme by navigate to View → Editor → Change Color Scheme in Geany."

rm -rf ~/geany-themes
