#!/bin/bash

#remove all downloaded themes from .config (file list recorded during install)
IFS=$'\n'
for file in $(cat /usr/share/geany/colorschemes/pi-apps-installed-themes.txt ; echo pi-apps-installed-themes.txt) ;do
  sudo rm -f "/usr/share/geany/colorschemes/$file"
done

#clear geany's color_scheme entry
sed -i 's/color_scheme=.*/color_scheme=/g' ~/.config/geany/geany.conf
sudo sed -i 's/color_scheme=.*/color_scheme=/g' /root/.config/geany/geany.conf || true
