#!/bin/bash
# Get dependencies
install_packages xcompmgr tint2 gtk2-engines-murrine || exit 1
if [ ! -d ~/Windows-10 ];then 
  git_clone https://github.com/Botspot/Windows-10 || error "failed to download github repository!"
fi

if [ ! -f ~/Windows-10/install ];then
  error "Windows 10 install script missing!"
fi

setsid ~/Windows-10/install &
