#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

if [ ! -f ~/Windows-10/uninstall ];then
  error "Windows 10 uninstall script missing!"
fi

setsid ~/Windows-10/uninstall &

"${DIRECTORY}/purge-installed" "$(dirname "$0")" || exit 1
