#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
echo -e "\\e[91m$1\\e[39m"
exit 1
}
echo "Starting Installation..."
sleep 5
echo "Checking Network..."
wget_error=$(wget --spider github.com >/dev/null 1>&2)
if [ "$?" ! = 0 ]; then
error "Internet Connection failed! Please Connect to a network!!"
fi
echo "Installing Dependencies..."
sudo apt update && sudo apt install openjfx nautilus android-tools-adb android-tools-fastboot openjdk-11-jdk -y || exit 1

echo "Downloading MiUnlockTool..."
git clone https://github.com/francescotescari/XiaoMiToolV2 -b linux || error "Failed to clone git repository!"
cd XiaoMiToolV2
echo "Build Unlock Tool..."
./gradlew build || error "Failed to build XiaoMiToolV2!"

echo "Writing launch desktop file..."
echo "[Desktop Entry]
Name=Mi Unlock Tool
GenericName=Unlock Tool
Comment=Mi Unlock Tool helps you to unlock your Xiaomi Phone without risk or data loss.
Exec=gksudo -k -u root /home/pi/XiaoMiToolV2/gradlew run
Icon=$(dirname "$0")/icon-64.png
Terminal=false
Type=Application
Categories=System" > ~/.local/share/applications/MiUnlocktool.desktop

echo "Writing Execution file..."
echo "#!/bin/sh
if [ ! -f /bin/bash ]; then
shell='sh -c'
else
shell='bash -c'
fi

"$shell" /home/pi/XiaoMiToolV2/gradlew run
 " | sudo tee /usr/bin/unlocktool.sh
sudo chmod +x /usr/bin/unlocktool.sh

echo "Installation Finished without errors! Enjoy!"
echo
exit 0
