#!/bin/bash
install_packages openjfx adb android-tools-fastboot openjdk-11-jdk || exit 1

git_clone https://github.com/francescotescari/XiaoMiToolV2 -b linux || exit 1
cd XiaoMiToolV2
echo "Building XiaoMi Tool..."
./gradlew build || error "Failed to build XiaoMiToolV2!"

echo "Creating menu shortcut..."
echo "[Desktop Entry]
Name=Mi Unlock Tool
GenericName=Unlock Tool
Comment=Mi Unlock Tool helps you to unlock your Xiaomi Phone without risk or data loss.
Exec=gksudo -k -u root /home/pi/XiaoMiToolV2/gradlew run
Icon=$(dirname "$0")/icon-64.png
Terminal=false
Type=Application
Categories=System" > ~/.local/share/applications/MiUnlocktool.desktop

echo "Writing Execution file..."
echo "#!/bin/sh
if [ ! -f /bin/bash ]; then
shell='sh -c'
else
shell='bash -c'
fi

"$shell" /home/pi/XiaoMiToolV2/gradlew run
 " | sudo tee /usr/bin/unlocktool.sh
sudo chmod +x /usr/bin/unlocktool.sh

