#!/bin/bash

### Make directory ~/Unciv if not available
mkdir -p $HOME/Unciv || error "Failed to create folder $HOME/Unciv"

### Add LICENSE from Github if doesn't exist
if [[ ! -f ~/Unciv/LICENSE ]]; then
  wget -O ~/Unciv/LICENSE https://raw.githubusercontent.com/yairm210/Unciv/master/LICENSE || error 'Failed to download license!'
fi

### install openjdk-8-jre
# the 'default jre' (OpenJDK-11-jre) package takes too much RAM and runs very sloppy in Raspberry Pi 3B+
# so, we will OpenJDK 8 JRE installation cause thats the minimal Java version Unciv needs
# openjdk-8-jre very smoothly without any problems
install_packages openjdk-8-jre || exit 1

### Download Unciv.jar
wget -O "$HOME/Unciv/Unciv.jar" https://github.com/yairm210/Unciv/releases/download/3.18.10-patch1/Unciv.jar || exit 1

### Make Unciv.sh
# This is necessary because some special characters are supported in Desktop Entry Files.
# Without running Unciv.jar from ~/Unciv, the Game Data will be saved in ~ by default (not ~/Unciv).
# see https://github.com/yairm210/Unciv/blob/master/desktop/linuxFilesForJar/Unciv.sh
echo "\
cd $HOME/Unciv
$(echo /usr/lib/jvm/java-8-openjdk-*/bin/java) -jar ./Unciv.jar" \
> ~/Unciv/Unciv.sh || error "Failed to write $HOME/Unciv/Unciv.sh!"

chmod +x $HOME/Unciv/Unciv.sh || error "Failed to make $HOME/Unciv/Unciv.sh executable!"

### Make Desktop entry
echo "\
[Desktop Entry]
Comment=Open-source Android/Desktop remake of Civ V
Exec=$HOME/Unciv/Unciv.sh
GenericName=4X Game
Icon=$(dirname "$0")/icon-64.png
Name=Unciv
NoDisplay=false
StartupNotify=true
Terminal=false
Type=Application
Categories=Game" \
> ~/.local/share/applications/unciv.desktop || error 'Failed to make menu button for Unciv!'
