#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

#if your app installs any packages, keep this command here so those packages will be removed.
"${DIRECTORY}/purge-installed" "$(dirname "$0")" || exit 1

if [ -d ~/RPIDoom3Installer ];then
  cd ~/RPIDoom3Installer || "Failed to Change directory"
  echo "Running uninstall script..."
  ./uninstall.sh || error "Failed to execute uninstall script :("
else
  echo "WARNING: Doing nothing as ~/RPIDoom3Installer folder does not exist!"
fi

exit 0
