#!/bin/bash

purge_packages || error "Dependencies failed to uninstall"
if [ -d ~/RPIDoom3Installer ];then
  cd ~/RPIDoom3Installer || "Failed to Change directory"
  echo "Running uninstall script..."
  ./uninstall.sh || error "Failed to execute uninstall script :("
else
  echo "WARNING: Doing nothing as ~/RPIDoom3Installer folder does not exist!"
fi

exit 0
