#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

sudo apt purge firefox -y
sudo rm -f /etc/apt/preferences.d/99bionic-updates
sudo rm -f /etc/apt/sources.list.d/firefox-ubuntu.list
sudo apt-key del "3B4FE6ACC0B21F32" || error "Failed to delete the key!"

