#!/bin/bash

version=6.3.0-1

function check-armhf() {
	ARMHF="$(dpkg --print-foreign-architectures | grep "armhf")"
}

#add armhf architecture (multiarch)
check-armhf
if [[ "$ARMHF" == *"armhf"* ]]; then
  echo "armhf arcitecture already added..."
else
  sudo dpkg --add-architecture armhf
  check-armhf
  if [[ "$ARMHF" != *"armhf"* ]]; then
    error "armhf architecture should be added by now, but it isn't!"
  fi
fi

unset rpi_arm_userspace
# only install the libraspberrypi0 arm32 package if the user already has the libraspberrypi0 arm64 package installed
if package_installed libraspberrypi0 ; then
  rpi_arm_userspace="libraspberrypi0:armhf"
fi

install_packages https://download.anydesk.com/rpi/anydesk_${version}_armhf.deb libgles-dev:armhf libegl-dev:armhf libpolkit-gobject-1-0:armhf $rpi_arm_userspace patchelf || exit 1

#make anydesk search armhf libs first
sudo patchelf --set-rpath /usr/lib/arm-linux-gnueabihf /usr/bin/anydesk

#libraspberrypi0:armhf provides libs with so.0, but anydesk wants libs that end in .so
#fix it

sudo patchelf --replace-needed libbcm_host.so libbcm_host.so.0 /usr/bin/anydesk
sudo patchelf --replace-needed libvcos.so libvcos.so.0 /usr/bin/anydesk
sudo patchelf --replace-needed libvchiq_arm.so libvchiq_arm.so.0 /usr/bin/anydesk

# Solve error: "anydesk: error while loading shared libraries: libbrcmGLESv2.so: cannot open shared object file: No such file or directory"

sudo patchelf --replace-needed libbrcmGLESv2.so libGLESv2.so /usr/bin/anydesk
sudo patchelf --replace-needed libbrcmEGL.so libEGL.so /usr/bin/anydesk
