#!/bin/bash

purge_packages || exit 1

if [ "$arch" == 64 ];then
  # remove armhf architecture if no packages from it are currently installed
  apt list --installed | awk '$3 == "armhf" { print }' | grep -q installed || sudo dpkg --remove-architecture armhf
fi

#remove symlinked libraries
if [ -L /usr/lib/libbrcmGLESv2.so ];then
  sudo rm -f /usr/lib/libbrcmGLESv2.so
fi
if [ -L /usr/lib/libbrcmEGL.so ];then
  sudo rm -f /usr/lib/libbrcmEGL.so
fi
true
