#!/bin/bash
purge_packages || exit 1

#remove symlinked libraries
if [ -L /usr/lib/libbrcmGLESv2.so ];then
  sudo rm -f /usr/lib/libbrcmGLESv2.so
fi
if [ -L /usr/lib/libbrcmEGL.so ];then
  sudo rm -f /usr/lib/libbrcmEGL.so
fi
true
