#!/bin/bash

install_packages https://github.com/Pi-Apps-Coders/files/raw/main/tetris-cli_2.0_arm64.deb || exit 1

sudo tee /usr/local/bin/tetris-cli > /dev/null << 'EOF'
#!/bin/bash
exec /usr/games/tetris/tetris "$@"
EOF

sudo chmod +x /usr/local/bin/tetris-cli
