#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

purge_packages
sudo rm -rf /usr/bin/antimicrox || error 'Failed to remove AntiMicroX!'
rm -rf $HOME/antimicrox || sudo rm -rf $HOME/antimicrox
