#!/bin/bash

version=20220310
version2=0.4.0
wget -O ~/Cura.AppImage https://github.com/smartavionics/Cura/releases/download/${version}/Cura-mb-master-aarch64-${version}.AppImage || error "Failed to download!"

chmod +x ~/Cura.AppImage

#ensure libfuse2 is installed to avoid "error loading libfuse.so.2" error
install_packages libfuse2 libgles-dev || exit 1

#get stl-thumb package - non-fatal as it's not crucial to Cura's function
(install_packages "https://github.com/unlimitedbacon/stl-thumb/releases/download/v${version2}/stl-thumb_${version2}_arm64.deb") || warning "Failed to install stl-thumb package, but continuing as it's not crucial to Cura's operation."

if [ -z "$(cat ~/.config/mimeapps.list | grep -F 'cura.desktop')" ];then
  echo "Associating the STL mimetype for Cura..."
  echo "[Added Associations]
model/stl=cura.desktop;" >> ~/.config/mimeapps.list
fi

enable_module fuse || exit 1

echo "[Desktop Entry]
Name=Ultimaker Cura
GenericName=3D Printing Software
Comment=Cura converts 3D models into paths for a 3D printer. It prepares your print for maximum accuracy, minimum printing time and good reliability with many extra features that make your print come out great.
Exec=$HOME/Cura.AppImage %f
Icon=$(dirname $0)/icon-64.png
Terminal=false
Type=Application
MimeType=application/sla;application/vnd.ms-3mfdocument;application/prs.wavefront-obj;image/bmp;image/gif;image/jpeg;image/png;model/x3d+xml;
Categories=Graphics;Education;Development;Science;
Keywords=3D;Printing;
StartupNotify=true" > ~/.local/share/applications/cura.desktop || error "Failed to create menu button!"

