#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}
rm -f ~/.local/share/applications/cura.desktop
rm -f ~/Cura-mb-master-armhf-20200902.AppImage
rm -rf  ~/.cache/cura
#gio trash ~/.config/cura
