#!/bin/bash

function error {
  echo -e "\e[31m$1\e[39m"
  exit 1
}

DIRECTORY="$(dirname "$(dirname "$(dirname "$0")")")"
rm -f ~/.local/share/applications/cura.desktop
rm -f ~/Cura-mb-master-armhf-20200902.AppImage
rm -rf  ~/.cache/cura
#gio trash ~/.config/cura
