#!/bin/bash
rm -f Snapdrop-linux-armv7l.zip

wget https://github.com/ryanfortner/snapdrop-rpi/raw/master/Snapdrop-linux-armv7l.zip || error "Failed to download archive!"
unzip Snapdrop-linux-armv7l.zip || error "Failed to extract archive!"
rm -f Snapdrop-linux-armv7l.zip

# Desktop entry
echo "[Desktop Entry]
Name=Snapdrop
GenericName=Local File Sharing
Comment=Snapdrop: local file sharing in your browser. Inspired by Apple's Airdrop.
Exec=$HOME/snapdrop/Snapdrop
Icon=$(dirname "$0")/icon-64.png
Terminal=true
StartupNotify=true
Categories=Network;
Type=Application" > ~/.local/share/applications/snapdrop.desktop || error "Failed to create desktop shortcut!"
