#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

# Get dependencies
"${DIRECTORY}/pkg-install" "libsfml-dev libsdl2-dev libxdo-dev" "$(dirname "$0")" || exit 1

#Download
cd ~
wget https://github.com/mobilegmYT/bongocat-osu/releases/download/1.5.3/bongocat-armv7l-1.5.3.zip

#Install
unzip bongocat-armv7l-1.5.3.zip
rm bongocat-armv7l-1.5.3.zip
mv bongocat-armv7l-1.5.3 bongocam
chmod +x ~/bongocam/bongo

#Desktop shortcut
echo "[Desktop Entry]
Name=Bongo Cam
Comment=Cute bongo cat app
Icon=$(dirname "$0")/icon-64.png
Exec=$HOME/bongocam/bongo
Path=$HOME/bongocam/
Type=Application
Encoding=UTF-8
Terminal=false
Categories=AudioVideo" > ~/.local/share/applications/bongocam.desktop