#!/bin/bash
# Get dependencies
install_packages libsfml-dev libsdl2-dev libxdo-dev || exit 1
#Download
rm -rf ~/bongocat-armv7l-* ~/bongocam
wget -O ~/bongocat.zip https://github.com/mobilegmYT/bongocat-osu/releases/download/1.5.3/bongocat-armv7l-1.5.3.zip

#Install
unzip ~/bongocat.zip
rm ~/bongocat.zip
mv ~/bongocat-armv7l-* ~/bongocam
chmod +x ~/bongocam/bongo

#Desktop shortcut
echo "[Desktop Entry]
Name=Bongo Cam
Comment=Cute bongo cat app
Icon=$(dirname "$0")/icon-64.png
Exec=$HOME/bongocam/bongo
Path=$HOME/bongocam/
Type=Application
Encoding=UTF-8
Terminal=false
Categories=AudioVideo;" > ~/.local/share/applications/bongocam.desktop
