#!/bin/bash

#Allow packages required by this app to be uninstalled
purge_packages || exit 1

sudo rm -rf /opt/librewolf /usr/share/applications/librewolf.desktop /usr/share/icons/hicolor/*/apps/librewolf.png
