#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

version='1.21.0'
wget https://github.com/chunky-milk/minbrowser-arm-builds/releases/download/${version}/min_${version}_arm64.deb || error "Failed to download Min deb file!"
sudo apt install -yf ./min_${version}_arm64.deb || error "Failed to install min deb file!"
rm -f ./min_${version}_arm64.deb
