#!/bin/bash

install_packages firefox-esr https://github.com/browsh-org/browsh/releases/download/v1.6.4/browsh_1.6.4_linux_armv7.deb || exit 1

echo "[Desktop Entry]
Version=1.1
Type=Application
Name=Browsh
Comment=The modern text-based terminal browser.
Icon=$(dirname "$0")/icon-64.png
Exec=browsh
Terminal=true
Categories=Network;" > ~/.local/share/applications/browsh.desktop
