#!/bin/bash

#Dependencies
install_packages build-essential cmake git libcurl4-openssl-dev libssl-dev libfreetype6-dev libglew-dev libnotify-dev libogg-dev libopus-dev libopusfile-dev libpnglite-dev libsdl2-dev libsqlite3-dev libwavpack-dev python google-mock || exit 1

#Clone the Repository
cd /tmp
git_clone https://github.com/ddnet/ddnet --recursive || exit 1

#Build
cd ddnet || exit 1
mkdir build
cd build || exit 1
cmake .. || error 'Failed at cmake!'
make -j$(nproc) || error 'Failed at make!'
sudo make install || error "Failed to install"
