#!/bin/bash

version=16.6

#Dependencies
if package_is_new_enough rustc 1.48.0 ;then
  #if rustc is 1.48.0 or newer, install dependencies and rustc (rustc may or may not be already installed)
  install_packages build-essential cargo cmake git libcurl4-openssl-dev libssl-dev libfreetype6-dev libglew-dev libnotify-dev libogg-dev libopus-dev libopusfile-dev libpnglite-dev libsdl2-dev libsqlite3-dev libwavpack-dev python3 google-mock libx264-dev libavfilter-dev libavdevice-dev libavformat-dev libavcodec-dev libavutil-dev rustc || exit 1
elif package_installed rustc ;then
  #if a too old version of rustc is already installed, exit with error
  error "User error: DDNet cannot install because your operating system has too old of a version of Rust installed. You can try removing the rustc package, then installing DDNet again."
elif package_is_new_enough rustc-mozilla 1.48.0 ;then
  #rustc is not new enough, but it is not installed either and rustc-mozilla is available
  #install dependencies and rustc-mozilla
  install_packages build-essential cargo cmake git libcurl4-openssl-dev libssl-dev libfreetype6-dev libglew-dev libnotify-dev libogg-dev libopus-dev libopusfile-dev libpnglite-dev libsdl2-dev libsqlite3-dev libwavpack-dev python3 google-mock libx264-dev libavfilter-dev libavdevice-dev libavformat-dev libavcodec-dev libavutil-dev rustc-mozilla || exit 1
else
  error "User error: DDNet cannot install because your operating system has too old of a version of Rust available. Please update to a newer OS, then install DDNet again."
fi

package_available glslang-tools
if [[ $? == "0" ]]; then
  install_packages glslang-tools libvulkan-dev || error "Failed to install dependencies"
  vulkan=1
else
  vulkan=0
fi

#Clone the Repository
cd /tmp
git_clone https://github.com/ddnet/ddnet --recursive -b $version --depth=1 || exit 1

#Build
cd ddnet || exit 1
mkdir build
cd build || exit 1
if [[ $vulkan == 1 ]]; then
  cmake .. || error 'Failed at cmake!'
else
  cmake .. -DVULKAN=OFF || error 'Failed at cmake!'
fi
make -j$(nproc) || error 'Failed at make!'
sudo make install || error "Failed to install"
sudo update-icon-caches /usr/local/share/icons/*
