#!/bin/bash

version=1.0.230

install_packages https://github.com/Eugeny/tabby/releases/download/v${version}/tabby-${version}-linux-armv7l.deb || exit 1

status "Moving Menu entry to Accessories..."
sudo sed -i 's/Categories=.*/Categories=Utility;/' /usr/share/applications/tabby.desktop || error "Failed to fix desktop file!"
