#!/bin/bash
# install falkon if its availabe in apt (debian/ubuntu have this but rpiOS/raspbian does not)
package_available falkon
if [[ $? == "0" ]]; then
  install_packages falkon || error "Could not install falkon"
else
  install_packages "http://ftp.debian.org/debian/pool/main/q/qtwebengine-opensource-src/libqt5webenginecore5_5.11.3+dfsg-2+deb10u1_armhf.deb" "http://ftp.debian.org/debian/pool/main/q/qtwebengine-opensource-src/libqt5webenginewidgets5_5.11.3+dfsg-2+deb10u1_armhf.deb" "http://ftp.debian.org/debian/pool/main/f/falkon/falkon_3.0.0-3_armhf.deb" || error "Could not install falkon"
fi

