#!/bin/bash
if [ -d ~/raspi-email-checker ];then
  gio trash ~/raspi-email-checker
  echo -e "\\e[33mWARNING: Moved the raspi-email-checker folder to trash instead of deleting.
The checkmail.py script inside may contain a password!\\e[39m"
fi

rm -f ~/.config/autostart/checkmail.desktop

purge_packages || error "Dependencies failed to uninstall"
