#!/bin/bash

version=5.4.4

wget -O Geekbench.tar.gz https://cdn.geekbench.com/Geekbench-${version}-LinuxARMPreview.tar.gz
tar -xf Geekbench.tar.gz || error "Failed to extract files!"
sudo mv -f ./Geekbench-${version}-LinuxARMPreview /opt/geekbench || error "Failed to move source folder to /opt!"

# Create symbolic link
sudo ln -sf /opt/geekbench/geekbench_aarch64 /usr/local/bin/geekbench || error "Failed to create symbolic link to /usr/local/bin!"
