#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

rm -rf ~/eDEX-UI-RPi ~/.local/share/applications/appimagekit-edex-ui.desktop ~/.local/share/applications/appimagekit-edex-ui-3.desktop
exit 0
