#!/bin/bash

if [ "$1" == "update" ]; then
purge_packages || exit 1
sudo rm /usr/local/bin/xmrig
status "Not removing the 'xmrig' folder because uninstall run from updater."
else
purge_packages || exit 1
sudo rm -rf $HOME/xmrig || error 'Failed to remove $HOME/xmrig dir!'
sudo rm /usr/local/bin/xmrig
fi
