#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

# Get dependencies
"${DIRECTORY}/pkg-install" "libsquashfuse0 squashfuse fuse" "$(dirname "$0")" || error "Failed to install libsquashfuse0 squashfuse fuse"
sudo apt install snapd || error "APT failed to install snapd"

sudo systemctl enable --now snapd.socket || error "Unable to enable snapd.socket"
sudo snap install core || error "Unable to install core"

sudo ln -s /var/lib/snapd/snap /snap
sudo snap install snap-store || error "Unable to install snap store"
sudo rm -rf /usr/share/applications/snap
ln -s /var/lib/snapd/desktop/applications /usr/share/applications/snap || sudo ln -s /var/lib/snapd/desktop/applications /usr/share/applications/snap || error "Failed to create symlink for Snap app shortcuts!"


