#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

sudo snap remove snap-store || error "Unable to uninstall snap store"

rm -f /usr/share/applications/snap


echo -e "\e[93mNote: To prevent removing user data, uninstalling the Snap Store app does not uninstall the snapd package! To completely remove everything snap-related, run this command:

sudo apt purge snapd\e[39m
"
sleep 3
echo "Waiting 30 seconds..."
sleep 30
