#!/bin/bash
sudo rm -rf /var/snap/snap-store /usr/share/applications/snapd-temporary
if command -v snap >/dev/null ;then
  sudo snap remove snap-store || error "The snap command failed to uninstall snap-store\nPerhaps running this command would fix it?\nsudo apt install --reinstall snapd\noutput from running snap changes:\n$(snap changes 2>&1)"

echo -e "\e[93mNote: To prevent removing user data, uninstalling the Snap Store app does not uninstall the snapd package!\nTo completely remove everything snap-related, run this command:

sudo apt purge snapd\e[39m
"
  
else
  echo "Warning: attempting to uninstall snap store but the snap command is not found. This script is exiting with 'success', as obviously nothing is installed."
fi
