#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

sudo snap remove snap-store || error "Unable to uninstall snap store"
"${DIRECTORY}/purge-installed" "$(dirname "$0")" || exit 1

if ! [ -d /snap ];then
  rm -f /usr/share/applications/snap
fi
