#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

rm -f ~/turbowarp.deb
wget -O ~/turbowarp.deb https://github.com/TurboWarp/desktop/releases/download/v0.3.1/TurboWarp-linux-arm64-0.3.1.deb || error "Failed to download deb!"

sudo apt install -yf ~/turbowarp.deb || error "Failed to install turbowarp.deb!"

rm -f ~/turbowarp.deb

#Move TurboWarp desktop file from Education category to Programming category
sed -i 's/Categories=Education;/Categories=Application;Development;/g' /usr/share/applications/turbowarp-desktop.desktop

