#!/bin/bash

case $(get_codename) in
bionic|focal|jammy|kinetic)
  apt_lock_wait
  sudo add-apt-repository ppa:phoerious/keepassxc -y
  install_packages keepassxc || exit 1
  ;;
bullseye)
  install_packages https://github.com/Pi-Apps-Coders/files/raw/main/keepassxc_2.6.6-1_armhf.deb || exit 1
  ;;
*)
  install_packages https://github.com/ryanfortner/ryanfortner/releases/download/1002/keepassxc_2.6.6-5_armhf.deb || exit 1
  ;;
esac
