#!/bin/bash

if [ "$(get_codename)" == "bullseye" ]; then
    #install bullseye version
    install_packages https://github.com/Pi-Apps-Coders/files/raw/main/keepassxc_2.6.6-1_arm64.deb || exit 1
else 
    #install buster version
    install_packages https://github.com/ryanfortner/ryanfortner/releases/download/1002/keepassxc_2.6.6-5_arm64.deb || exit 1
fi