#!/bin/bash

#Allow packages required by this app to be uninstalled
purge_packages || exit 1

sudo rm -f /usr/share/applications/feather.desktop /opt/feather.AppImage /usr/share/icons/hicolor/64x64/apps/feather.png
