#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

rm -rf ~/.wine
sudo rm -rf /usr/local/bin/wine
sudo rm /usr/local/bin/winecfg
sudo rm /usr/local/bin/wineserver
rm -rf ~/wine

rm ~/.local/share/applications/wine-config.desktop || error 'Failed to remove winecfg menu shortcut!'
rm ~/.local/share/applications/winetricks.desktop || error 'Failed to remove winetricks menu shortcut!'
rm ~/.local/share/applications/wine-explorer.desktop || error 'Failed to remove wine desktop menu shortcut!'

#if your app installs any packages, keep this command here so those packages will be removed.
"${DIRECTORY}/purge-installed" "$(dirname "$0")" || exit 1
