#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

rm -rf ~/.wine
sudo rm -rf /usr/local/bin/wine
sudo rm /usr/local/bin/winecfg
sudo rm /usr/local/bin/wineserver
rm -rf ~/wine

rm ~/.local/share/applications/winecfg.desktop || error 'Failed to remove winecfg menu shortcut'

#if your app installs any packages, keep this command here so those packages will be removed.
"${DIRECTORY}/purge-installed" "$(dirname "$0")" || exit 1
