#!/bin/bash

version='1.0.0.79'

# install box86
"${DIRECTORY}/manage" install-if-not-installed Box86 || error "Box86 failed to install somehow!"
# install box64
"${DIRECTORY}/manage" install-if-not-installed Box64 || error "Box64 failed to install somehow!"

# add additional packages not already installed by box86/box64
install_packages libnss3:armhf libnm0:armhf libdbus-glib-1-2:armhf libnspr4:armhf libgudev-1.0-0:armhf libxtst6:armhf libsm6:armhf libice6:armhf libusb-1.0-0:armhf libnss3 libnm0 libdbus-glib-1-2 libudev1 libnspr4 libgudev-1.0-0 libxtst6 libsm6 libice6 libusb-1.0-0 libibus-1.0-dev || exit 1

# perform an apt upgrade to make sure the latest version of box64 and box86 are installed
echo "Upgrading Box86 and Box64 if necessary:"
apt_update
apt_lock_wait
sudo apt install --only-upgrade box86-* box64-* -y

if package_installed steam-devices ; then
  echo "Removing steam-devices package because it conflicts with steam-launcher..."
  apt_lock_wait
  sudo apt purge -y steam-devices
fi

if package_installed steamlink ; then
  echo "Removing steamlink package because it conflicts with steam-launcher..."
  apt_lock_wait
  sudo apt purge -y steamlink
fi

#get steam deb and unpack it to make a few changes
wget -O /tmp/steam.deb "https://repo.steampowered.com/steam/archive/stable/steam-launcher_${version}_all.deb"
dpkg-deb -x /tmp/steam.deb /tmp/steam-deb
dpkg-deb -e /tmp/steam.deb /tmp/steam-deb/DEBIAN
rm -f /tmp/steam.deb

#fix terminal dependency to include all terminals
sed -i 's/xterm | gnome-terminal | konsole/x-terminal-emulator/g' /tmp/steam-deb/DEBIAN/control

#bump version to ensure a double reinstall will install this customized deb
sed -i 's/\(Version:.*$\)/\1-pi-apps/' /tmp/steam-deb/DEBIAN/control

#remove steam apt repository - prevent it from updating with apt upgrade
rm -rf /tmp/steam-deb/usr/share/keyrings /tmp/steam-deb/etc #remove the folders as there is nothing else in there
rm -f /tmp/steam-deb/DEBIAN/conffiles #this file only mentions the 2 repo files which we just deleted

#remove steam command symlink and replace it with runner script
rm -f /tmp/steam-deb/usr/bin/steam

echo '#!/bin/bash
export STEAMOS=1
export STEAM_RUNTIME=1
export DBUS_FATAL_WARNINGS=0
[ -z "$BOX64_LOG" ] && export BOX64_LOG=1
[ -z "$BOX86_LOG" ] && export BOX86_LOG=1 
BOX64_EMULATED_LIBS=libmpg123.so.0 /usr/lib/steam/bin_steam.sh -no-cef-sandbox steam://open/minigameslist "$@"
rm -f ~/Desktop/steam.desktop' > /tmp/steam-deb/usr/bin/steam
chmod +x /tmp/steam-deb/usr/bin/steam

#package it back into a deb
dpkg-deb -b /tmp/steam-deb /tmp/steam.deb || error "Failed to package the steam deb!"
rm -rf /tmp/steam-deb

#install the customized steam-launcher deb
install_packages /tmp/steam.deb || exit 1

rm -f /tmp/steam.deb $HOME/Desktop/steam.desktop
sudo rm -f /usr/local/bin/steam /usr/local/share/applications/steam.desktop #remove old command wrapper and app-launcher wrappers
sudo rm -f /etc/apt/sources.list.d/steam-stable.list /etc/apt/sources.list.d/steam-beta.list
