#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

"${DIRECTORY}/pkg-install" "libappindicator1 libnm0" "$(dirname "$0")" || exit 1

if dpkg -l steam-devices ;then
  echo "Removing steam-devices package because it conflicts with steam-launcher..."
  sudo apt purge -y steam-devices
fi

"${DIRECTORY}/manage" install-if-not-installed Box86 || error "Box86 failed to install somehow!"

echo "Downloading steam.deb"
wget https://steamcdn-a.akamaihd.net/client/installer/steam.deb || error "Failed to download steam.deb!"

sudo dpkg -i ~/steam.deb || error "dpkg failed to install steam.deb!"

rm ~/steam.deb

echo "Editing steam script to run on Raspberry Pi..."
sudo sed -i 's/set -e/set -e\nexport STEAMOS=1\nexport STEAM_RUNTIME=1/' /usr/lib/steam/bin_steam.sh

echo "Creating a Steam config file so it will launch in Small Mode..."
mkdir -p ~/.local/share/Steam/config
wget https://raw.githubusercontent.com/Botspot/Steam-RPi/main/DialogConfig.vdf -O ~/.local/share/Steam/config/DialogConfig.vdf

exit 0
