#!/bin/bash

purge_packages || exit 1
sudo dpkg -r steam-launcher || error "Failed to uninstall steam-launcher

sudo rm -f /lib/udev/rules.d/60-steam-*.rules || error "Failed to remove /lib/udev/rules.d/60-steam-*.rules"
sudo rm -rf /usr/local/bin/steam /usr/local/share/applications/steam.desktop ~/.steam ~/.local/share/Steam /usr/share/applications/steam.desktop ~/steam || error "Failed to remove steam files and folders"
