#!/bin/bash
sudo rm -f /etc/apt/sources.list.d/vscodium.list /etc/apt/trusted.gpg.d/vscodium.gpg

version=1.65.2

install_packages "https://github.com/VSCodium/vscodium/releases/download/${version}/codium_$(wget -qO- https://github.com/VSCodium/vscodium/releases/tag/${version} | grep 'arm64.deb"' | grep -o "_.*_" | tr -d '_')_arm64.deb" || exit 1

