#!/bin/bash
sudo rm -f /etc/apt/sources.list.d/vscodium.list /etc/apt/trusted.gpg.d/vscodium.gpg

version=1.91.1.24193

install_packages "https://github.com/VSCodium/vscodium/releases/download/${version}/codium_${version}_armhf.deb" || exit 1

