#!/bin/bash
sudo rm -f /etc/apt/sources.list.d/vscodium.list /etc/apt/trusted.gpg.d/vscodium.gpg

version=1.63.2

install_packages "https://github.com/VSCodium/vscodium/releases/download/$(curl -s https://github.com/VSCodium/vscodium/releases/tag/${version} | grep "armhf.deb<" | awk -F '[<>]' '{print $3}')" || exit 1

