#!/bin/bash
sudo rm -f /etc/apt/sources.list.d/vscodium.list /etc/apt/trusted.gpg.d/vscodium.gpg

version=1.121.03429

install_packages "https://github.com/VSCodium/vscodium/releases/download/${version}/codium_${version}_arm64.deb" || exit 1

