#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

sudo apt purge codium -y
sudo rm /etc/apt/trusted.gpg.d/vscodium.gpg
sudo rm /etc/apt/sources.list.d/vscodium.list