#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

rm -f ~/freecad.deb

#download file
wget -O ~/freecad.deb https://github.com/ryanfortner/freecad-rpi/releases/download/v0.19.2/freecad_0.19.2_armhf.deb || error "Failed to download freecad.deb"

#install freecad
"${DIRECTORY}/pkg-install" "$HOME/freecad.deb" "$(dirname "$0")" || error "apt failed to install freecad.deb"
rm -f ~/freecad.deb
