#!/bin/bash

#Allow packages required by this app to be uninstalled
purge_packages || exit 1

# Remove AppImage itself and all additions.
status -n 'Removing AppImage and links... '
sudo rm -f /opt/FreeCAD.AppImage /usr/local/bin/FreeCAD /usr/share/applications/org.freecad.FreeCAD.desktop /usr/share/pixmaps/org.freecad.FreeCAD.svg /usr/share/pixmaps/org.freecad.FreeCAD.png /usr/share/mime/packages/freecad.xml || error 'Unable to execute sudo rm -f <files>'
status_green Executed

# Clear mimetype association.
mimeapps_list_file="$HOME/.config/mimeapps.list"
if [ -f "$mimeapps_list_file" ]; then
  sed -i '#application/x-extension-fcstd=org\.freecad\.FreeCAD\.desktop;#d' "$mimeapps_list_file" || error 'Unable to remove mimetype association!'
fi
