#!/bin/bash

#etcher debs compiled by Itai Nelken.

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

rm -f ~/etcher.deb

wget -O ~/etcher.deb https://github.com/Itai-Nelken/Etcher-arm-32-64/releases/download/v1.5.120/balena-etcher_1.5.120_arm64.deb || error "Failed to download etcher deb file!"

sudo apt install -fy ~/etcher.deb || error "failed to install deb file!"
rm -f ~/etcher.deb

exit 0
