#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

rm -f ./balena-etcher-1.5.109_arm64.deb

wget https://github.com/Itai-Nelken/Etcher-arm-32-64/blob/main/balena-etcher-1.5.109_arm64.deb || error "Failed to download!"

sudo apt install -y --fix-broken ./balena-etcher-1.5.109_arm64.deb  || error "failed to install deb file!"
rm -f ./balena-etcher-1.5.109_arm64.deb
exit 0
