#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

rm -f ./etcher*armv7l.deb

wget https://github.com/Itai-Nelken/Etcher-arm-32-64/releases/download/v1.5.117/balena-etcher-electron_1.5.117+39ccbbee_armhf.deb -O ~/etcher-v1.5.117_armv7l.deb || error "Failed to download!"

sudo apt install -fy ~/etcher-v1.5.117_armv7l.deb  || error "failed to install deb file!"
rm -f ~/etcher-v1.5.117_armv7l.deb
exit 0
