#!/bin/bash

#etcher debs compiled by Itai Nelken.

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

rm -f ~/etcher-v1.5.112_arm64.deb

wget https://github.com/Itai-Nelken/Etcher-arm-32-64/releases/download/v1.5.113/balena-etcher-electron_1.5.113+1dc56aed_arm64.deb -O ~/etcher-v1.5.113_arm64.deb || error "Failed to download!"

sudo apt install -y --fix-broken ~/etcher-v1.5.113_arm64.deb || error "failed to install deb file!"
rm -f ~/etcher-v1.5.113_arm64.deb
exit 0
