#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

rm -f ./etcher_1.5.109_armhf.deb

wget https://github.com/Itai-Nelken/Etcher-arm-32-64/raw/main/etcher_1.5.109_armhf.deb -O ~/etcher.deb || error "Failed to download!"

sudo apt install -y --fix-broken ~/etcher.deb  || error "failed to install deb file!"
rm -f ~/etcher.deb
exit 0
