#!/bin/bash

function error {
  echo -e "\e[31m$1\e[39m"
  exit 1
}

# Get dependencies
DIRECTORY="$(dirname "$(dirname "$(dirname "$0")")")"

rm -f ./balena-etcher-electron_1.5.63_Raspbian_Buster_armhf.deb

wget https://github.com/futurejones/balena-etcher-arm/releases/download/v1.5.63/balena-etcher-electron_1.5.63_Raspbian_Buster_armhf.deb

sudo apt install -y ./balena-etcher-electron_1.5.63_Raspbian_Buster_armhf.deb  || error "failed to install deb file!"
rm -f ./balena-etcher-electron_1.5.63_Raspbian_Buster_armhf.deb || error "failed to remove deb file!"