#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}
# Old deb file name, commented out
# sudo apt purge -y balena-etcher-electron
sudo apt purge -y balena-etcher -y || error "Failed to purge deb!"
rm -f ~/etcher.deb &>/dev/null
exit 0
