#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

sudo apt purge -y balena-etcher-electron  || error "failed to purge the deb file!"
rm -f ./etcher_1.5.109_armhf.deb
exit 0
