#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

"${DIRECTORY}/purge-installed" "$(dirname "$0")" || exit 1

if command -v obs >/dev/null ;then
  "${DIRECTORY}/api" apt_lock_wait
  sudo apt -y purge obs libfdk-aac2 libfdk-aac-dev || error "APT failed to purge OBS!"
  
  sudo rm -f /usr/bin/obs
  sudo rm -f /usr/bin/obs-exec
fi
