#!/bin/bash
# Install Wine
if ! command -v wine || [ "$(cat "${DIRECTORY}/data/status/Wine (x86)" 2>/dev/null)" != 'installed' ];then
  "${DIRECTORY}/manage" install 'Wine (x86)' || error "Wine failed to install somehow!"
fi

ulimit -c unlimited
echo "Note that during this installation, a error may pop up saying \"Gecko\" or \"Mono\" isn't installed. Don't worry, that error is normal. Just click the \"Install\" button!"
read -p "Press [Enter] to continue installaton."
rm -rf $HOME/.config/wechat-prefix
mkdir -p $HOME/.config/wechat-prefix
# Install font stuff so chinese renders
echo "Installing several Wine extensions to allow font rendering..."
BOX86_NOBANNER=1 WINEPREFIX=$HOME/.config/wechat-prefix winetricks corefonts gdiplus riched20 riched30 wenquanyi cjkfonts || error "Winetricks failed to install corefonts gdiplus riched20 riched30 wenquanyi cjkfonts"

# Download reg file to apply fonts
echo "Downloading custom registry file to allow font rendering..."
wget -O $HOME/chn_fonts.reg https://gist.githubusercontent.com/swordfeng/c3fd6b6fcf6dc7d7fa8a/raw/0ad845f98f5a97e7173ff40b5e57b3a163e92465/chn_fonts.reg

echo "Now installing the custom registry file to allow font rendering..."
WINEPREFIX=$HOME/.config/wechat-prefix wine regedit $HOME/chn_fonts.reg

# Install wechat
wget -O $HOME/WeChatSetup.exe https://dldir1.qq.com/weixin/Windows/WeChatSetup.exe

WINEPREFIX=$HOME/.config/wechat-prefix wine $HOME/WeChatSetup.exe
rm -rf $HOME/chn_fonts.reg $HOME/WeChatSetup.exe $HOME/.local/share/applications/wine/Programs/WeChat/UninstallWeChat.desktop $HOME/.local/share/desktop-directories/wine-Programs-WeChat.directory $HOME/.local/share/applications/wine/Programs/WeChat

echo "[Desktop Entry]
Name=WeChat
Exec=env BOX86_NOBANNER=1 env WINEPREFIX=$HOME/.config/wechat-prefix wine $HOME/.config/wechat-prefix/drive_c/Program\ Files/Tencent/WeChat/WeChat.exe
Type=Application
Categories=Network;Multimedia
StartupNotify=true
Comment=WeChat is a Chinese multi-purpose instant messaging, social media and mobile payment app.
Path=$HOME/.config/wechat-prefix/drive_c/Program Files/Tencent/WeChat/
Icon=$HOME/pi-apps/apps/Wechat/icon-64.png" > $HOME/.local/share/applications/WeChat.desktop

