#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

sudo apt purge rpiplay libavahi-compat-libdnssd-dev libplist-dev libssl-dev -y || error 'Failed to remove dependencies'
sudo apt autoremove -y && sudo apt clean || error 'Failed to clean system'