#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

sudo apt-get remove -y minecraft-pi-reborn-native &>/dev/null || true
"${DIRECTORY}/purge-installed" "$(dirname "$0")" || exit 1

sudo apt-get -y autoremove

sudo rm /etc/apt/sources.list.d/mcpi-revival.list
