---
name: App request
description: Submit an app
labels: App Request
body:
  - type: input
    id: app-name
    attributes:
      label: What is the name of the app?
      placeholder: Ex - Zoom, AndroidBuddy
    validations:
      required: true
      
  - type: textarea
    id: host
    attributes:
      label: (Optional) Where does the app hosted?
      placeholder: Ex - Github link, Gitlab link, Sourceforge link
    validations:
      required: false
  
  - type: textarea
    id: about
    attributes:
      label: About the app
      description: What is its main purpose? How it works? 
      placeholder: Tell us about the app here!
    validations:
      required: true
      
  - type: textarea
    id: zip
    attributes:
      label: Upload file
      description: "If you have a deb of the app, or if you've created a zip file for this app, or if you have any other relevant files, upload it here."
      placeholder: "Tips: You can upload files to transfer.sh and paste the link here"
    validations:
      required: false
      
  - type: checkboxes
    id: confirmation
    attributes:
      label: confirmation
      options:
        - label: I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
          required: true
        - label: I have confirmed that this app can run on Raspberry Pi.
          required: true
          required: false
        - label: I have confirmed that this app is not installable with `apt`, or the app is the updated version of APT one.
          required: true
