name: App request
description: Suggest/submit an app to be added to Pi-Apps
labels: ["App Request"]
body:
  - type: checkboxes
    attributes:
      options:
      - label: I searched other app requests and non are about this app.
        required: true
  - type: input
  - type: markdown
    attributes:
      value: |
        "Can this app run on RPi? If so, please provide a link to a tutorial if applicable."
    id: can-run-and-tut
    attributes:
      label: Can this app run on RPi?
      description: Can this app run on RPi? If so, please provide a link to a tutorial if applicable.
      placeholder: "Ex. 'App' runs on rpi great, here is the tutorial on how to install it: https://example.com/tutorial"
    validations:
      required: true
  - type: input
  - type: markdown
    attributes:
      value: |
        "Is this app something many GUI users would find useful?"
    id: is-useful
    attributes:
      label: would many gui users find this app useful?
      description: "Is this app something many GUI users would find useful?"
      placeholder: "Yes because of reason1, reason2 and reason3."
  - type: checkboxes
    attributes:
      options:
        - label: Can you install this app with `sudo apt install`?
          required: true
  - type: textarea
    id: has-zip
    attributes:
      label: If you've created a zip file for this app, upload it here.
      description: If you've created a zip file for this app, upload it here.
      placeholder: 
