name: Bug Report
description:  App failing to install? Is it still around after uninstalling? Let us know!
labels: ["bug"]
body:
  - type: checkboxes
    attributes:
      label: Confirmations
      options:
      - label: I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
        required: true
      - label: I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)
        required: false
      - label: 'IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/'
        required: true
  - type: input
    id: desc
    attributes:
      label: What happened?
      description: Briefly explain what happened.
      placeholder: "Ex. 'App' won't install, 'App' unable to launch after update"
    validations:
      required: true
  - type: textarea
    id: desc-long
    attributes:
      label: Description
      description: A clear and concise description of what the bug is and any personal attempts you made to fix it.
      placeholder: Tell us more!
    validations: 
      required: true
  - type: textarea
    id: os
    attributes:
      label: What are your system specs (run the following command in your terminal)?
      description: ~/pi-apps/api get_device_info
      placeholder: |
        OS: Raspbian GNU/Linux 10 (buster)
        OS architecture: 32-bit
        Last updated Pi-Apps on: 11/04/2022
        Latest Pi-Apps version: 11/04/2022
        Kernel: armv7l 5.15.55-v7l+
        Device model: Raspberry Pi 4 Model B Rev 1.4 
        Cpu name: Cortex-A72
        Ram size: 7.78 GB
        Raspberry Pi OS image version: 2021-01-11
        Language: en_US.UTF-8
      render: bash
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: (Recommended) Error log? Terminal output? Debug messages?
      description: Please provide error log or terminal output, if available.
      placeholder: Paste your terminal output/error log here
      render: bash
    validations:
      required: false

