#!/bin/bash

version=6.14
version2=0.07
install_packages clamav https://github.com/dave-theunsub/clamtk/releases/download/v${version}/clamtk_${version}-1_all.deb || exit 1

#if thunar file manager installed then also install clamtk thunar extension
if command -v thunar >/dev/null ;then
  status "Installing ClamAV Thunar extension because you have Thunar installed..."
  install_packages https://github.com/dave-theunsub/thunar-sendto-clamtk/releases/download/v${version2}/thunar-sendto-clamtk_${version2}-1_all.deb
fi
exit 0

