#!/bin/bash

version=6.18
version2=0.08-2
install_packages clamav https://github.com/dave-theunsub/clamtk/releases/download/v${version}/clamtk_${version}-1_all.deb || exit 1

#if thunar file manager installed then also install clamtk thunar extension
if command -v thunar >/dev/null ;then
  status "Installing ClamAV Thunar extension because you have Thunar installed..."
  deb_minor_version=${version2/${version2%-*}/}
  install_packages https://github.com/dave-theunsub/thunar-sendto-clamtk/releases/download/v${version2}/thunar-sendto-clamtk_${version2%-*}${deb_minor_version:--1}_all.deb
fi
exit 0

