#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

sudo apt purge -y puffin-internet-terminal-demo
sudo apt purge -y puffin-internet-terminal

sudo rm -f /etc/apt/sources.list.d/puffin-internet-terminal.list
