#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

"${DIRECTORY}/pkg-purge" "puffin-internet-terminal-demo puffin-internet-terminal" "$(dirname "$0")" || exit 1

sudo rm -f /etc/apt/sources.list.d/puffin-internet-terminal.list
