#!/bin/bash

#$1 is the command to be run.
#$2 is the title.

#set to 1 to display which terminal is being used
DEBUG=0

if [ -f /usr/bin/lxterminal ];then
  lxterminal --title="$2" -e bash -c "$1"
  [ $DEBUG == 1 ] && echo lxterminal
  
elif [ -f /usr/bin/xfce4-terminal ];then
  xfce4-terminal --title="$2" -x bash -c "$1"
  [ $DEBUG == 1 ] && echo xfce4-terminal
  
elif [ -f /usr/bin/mate-terminal ];then
  #mate-terminal --title="$2" -e "bash -c "\""$1"\"""
  mate-terminal --title="$2" -x bash -c "$1"
  [ $DEBUG == 1 ] && echo mate-terminal
  
elif [ -f /usr/bin/xterm ];then
  xterm -T "$2" -e bash -c "$1"
  [ $DEBUG == 1 ] && echo xterm
  
elif [ -f /usr/bin/konsole ];then
  konsole -p tabtitle="$2" -e bash <(echo "$1")
  [ $DEBUG == 1 ] && echo konsole
  
elif [ -f /usr/bin/terminator ];then
  terminator -T "$2" -x bash -c "$1"
  [ $DEBUG == 1 ] && echo terminator
  
elif [ -f /usr/bin/gnome-terminal ];then
  gnome-terminal --title "$2" -x bash -c "$1"
  [ $DEBUG == 1 ] && echo gnome-terminal
  
elif [ -f /usr/bin/qterminal ];then
  qterminal -e bash <(echo "$1")
  [ $DEBUG == 1 ] && echo qterminal
  
elif [ -f /usr/bin/x-terminal-emulator ];then
  $(readlink -f /usr/bin/x-terminal-emulator) -e bash -c "$1"
  [ $DEBUG == 1 ] && echo x-terminal-emulator
  
else
  echo "Failed to locate any terminal emulators!!!"
  exit 1
fi