#!/bin/bash
rm -f ~/tor.tar.xz
wget -O ~/tor.tar.xz https://phoenixnap.dl.sourceforge.net/project/tor-browser-ports/11.0.1/tor-browser-linux-arm64-11.0.1_en-US.tar.xz || error "Failed to download!"
tar -xf ~/tor.tar.xz || error "Failed to extract!"
rm -f ~/tor.tar.xz
echo "[Desktop Entry]
Type=Application
Name=Tor Browser
GenericName=Web Browser
Comment=Tor Browser is +1 for privacy and −1 for mass surveillance
Categories=Network;WebBrowser;Security;
Exec=$HOME/tor-browser_en-US/Browser/start-tor-browser
X-TorBrowser-ExecShell=./Browser/start-tor-browser --detach
Icon=$(dirname "$0")/icon-64.png
StartupWMClass=Tor Browser" > ~/.local/share/applications/tor.desktop
