#!/bin/bash

version=14.5.8
INSTALL_DIR="$HOME/.local/share"

rm -f /tmp/tor-browser-aarch64.tar.xz
wget -O /tmp/tor-browser-aarch64.tar.xz "https://github.com/ooovlad/tor-mullvad-aarch64/releases/download/${version}/tor-browser-linux-aarch64-${version}.tar.xz" || error "Failed to download Tor Browser ver. $version"

status -n 'Looking for previous installations and remaining user data… '
if [ -d "$INSTALL_DIR"/tor-browser ]; then
  #if data folder exists, prepare to import its user-data
  if [ -d "$INSTALL_DIR"/tor-browser/Browser/TorBrowser/Data/Browser ];then
    mv -f "$INSTALL_DIR"/tor-browser/Browser/TorBrowser/Data/Browser/ "$INSTALL_DIR"/tor-browser.temp/ || error 'Failed to move existing user data to temporary folder'
  fi
  rm -rf "$INSTALL_DIR"/tor-browser/* || error 'Failed to remove old Tor Browser files'
else
  mkdir -p "$INSTALL_DIR"/tor-browser || error 'Failed to create installation directory'
fi
status_green 'Done'

status -n "Extracting Tor Browser to $INSTALL_DIR/tor-browser … "
tar -xpJf /tmp/tor-browser-aarch64.tar.xz -C "$INSTALL_DIR"/tor-browser --strip-components=1 || error 'Failed to extract Tor Browser'
rm -f /tmp/tor-browser-aarch64.tar.xz
status_green 'Done'

#if tor-browser.temp folder exists, import its user-data
if [ -d "$INSTALL_DIR"/tor-browser.temp ];then
  status -n 'Importing existing user data… '
  rm -rf "$INSTALL_DIR"/tor-browser/Browser/TorBrowser/Data/Browser
  mv -f "$INSTALL_DIR"/tor-browser.temp "$INSTALL_DIR"/tor-browser/Browser/TorBrowser/Data/Browser
  rm -rf "$INSTALL_DIR"/tor-browser.temp
  status_green 'Done'
fi

status -n 'Registering Tor Browser as a desktop app for this user… '
cd "$INSTALL_DIR"/tor-browser || error 'Fatal error! Cannot cd to app!'
"$INSTALL_DIR"/tor-browser/start-tor-browser.desktop --register-app || error 'Failed to register a desktop app'
status_green 'Done'
