#!/bin/bash

version=14.5.8
INSTALL_DIR="$HOME/.local/share"

status 'Looking for previous installations and remaining user data…'

#[OLD] if ~/mullvad-browser folder exists (old installdir), prepare to import its user-data
if [ -d ~/mullvad-browser/Browser/MullvadBrowser/Data/Browser ];then
  mv -f ~/mullvad-browser "$INSTALL_DIR"/mullvad-browser.temp
  status_green 'Found user data in ~/mullvad-browser '
fi

#if "$INSTALL_DIR"/mullvad-browser folder exists, prepare to import its user-data
if [ -d "$INSTALL_DIR"/mullvad-browser/Browser/MullvadBrowser/Data/Browser ];then
  mv -f "$INSTALL_DIR"/mullvad-browser "$INSTALL_DIR"/mullvad-browser.temp
  status_green "Found user data in $INSTALL_DIR/mullvad-browser"
fi

status 'Downloading and extracting Mullvad Browser archive…'
rm -f /tmp/mullvad-browser-aarch64.tar.xz
wget -O /tmp/mullvad-browser-aarch64.tar.xz "https://github.com/ooovlad/tor-mullvad-aarch64/releases/download/${version}/mullvad-browser-linux-aarch64-${version}.tar.xz" || error "Failed to download!"
mkdir -p "$INSTALL_DIR"/mullvad-browser
tar -xpJf /tmp/mullvad-browser-aarch64.tar.xz -C "$INSTALL_DIR"/mullvad-browser --strip-components=1 || error "Failed to extract!"
rm -f /tmp/mullvad-browser-aarch64.tar.xz
status_green 'Done'

#if "$INSTALL_DIR"/mullvad-browser.temp folder exists, import its user-data
if [ -d "$INSTALL_DIR"/mullvad-browser.temp ];then
  status -n 'Importing user-data… '
  rm -rf "$INSTALL_DIR"/mullvad-browser/Browser/MullvadBrowser/Data/Browser
  mv -f "$INSTALL_DIR"/mullvad-browser.temp/Browser/MullvadBrowser/Data/Browser "$INSTALL_DIR"/mullvad-browser/Browser/MullvadBrowser/Data && rm -rf "$INSTALL_DIR"/mullvad-browser.temp
  status_green 'Done'
fi

status -n 'Registering Mullvad Browser as a desktop app for this user… '
cd "$INSTALL_DIR"/mullvad-browser || error 'Fatal error! Cannot cd to app!'
"$INSTALL_DIR"/mullvad-browser/start-mullvad-browser.desktop --register-app || error 'Failed to register a desktop app'
status_green 'Done'
