#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}


#download the 2018.3.7 version "tar.gz" file
wget https://download.jetbrains.com/python/pycharm-community-2020.2.3.tar.gz || error "Failed to downloading file. Make sure 'wget' is installed and verify your Internet Network Connection"

#extract and rename pycharm-community folder
tar xvzf pycharm-community-2020.2.3.tar.gz.tar.gz || error "Failed to extract downloaded pycharm-community-2018.3.7 files"
mv pycharm-community-2020.2.3.tar.gz.tar.gz pycharm-community || "Failed to rename pycharm folder "

#move folder to /opt/
sudo mv pycharm-community /opt/pycharm-community || error "Failed moving pycharm-community to /opt/pycharm-community"

#enter pycharm-community folder
cd /opt/pycharm-community || error "Failed to enter discord-electron folder!"

# Get dependencies
"${DIRECTORY}/pkg-install" "pip pip3 openjdk-11-jdk" "$(dirname "$0")" || exit 1


# Installing the software with permissions
cd bin || error "Failed to enter to bin directory"
chmod a+x ./pycharm.sh || error "Failed to run ./pycharm giving permission"

# Deleting tar.gz file
cd ..
cd ..
rm pycharm-community-2020.2.3.tar.gz.tar.gz || error "Failed to delete tar.gz file"
# Done

