#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

wget https://vivaldi.com/download/vivaldi-stable_armhf.deb -O ~/vivaldi_armhf.deb || error 'Failed to download vivaldi!'
sudo apt install --fix-missing -y ~/vivaldi_armhf.deb || error 'Failed to install vivaldi!'
rm ~/vivaldi_armhf.deb
