#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

rm -f ~/vivaldi.deb
wget https://downloads.vivaldi.com/stable/vivaldi-stable_3.8.2259.40-1_arm64.deb -O ~/vivaldi.deb || error 'Failed to download vivaldi!'
sudo apt install --fix-missing -y ~/vivaldi.deb || error 'Failed to install vivaldi!'
rm -f ~/vivaldi.deb
