#!/bin/bash
#https://help.vivaldi.com/desktop/install-update/manual-setup-vivaldi-linux-repositories/
wget -qO- https://repo.vivaldi.com/archive/linux_signing_key.pub | gpg --dearmor | sudo tee /usr/share/keyrings/vivaldi-browser.gpg >/dev/null || exit 1
echo "deb [signed-by=/usr/share/keyrings/vivaldi-browser.gpg arch=$(dpkg --print-architecture)] https://repo.vivaldi.com/archive/deb/ stable main" | sudo tee /etc/apt/sources.list.d/vivaldi-archive.list >/dev/null
wget -O- https://launchpadlibrarian.net/574476800/chromium-codecs-ffmpeg-extra_97.0.4692.56-0ubuntu0.18.04.1_armhf.deb | tail -c+1153 | tar JOx ./usr/lib/chromium-browser/libffmpeg.so > libffmpeg.so.5.0
sudo install -m644 libffmpeg.so.5.0 /opt/vivaldi/
(install_packages vivaldi-stable)
if [ $? != 0 ];then
  #exit cleanly if package failed to install
  sudo rm -f /usr/share/keyrings/vivaldi-browser.gpg /etc/apt/sources.list.d/vivaldi-archive.list
fi
