#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

# Warning
echo -e "\\e[1;91m This is only the engine. 
 To play the game, you must provide/copy ALL the folders of your copy of the game inside the install path.
 Any kind of pirated gamedata is not supported. \\e[39m"
echo $'\n'
read -p Press [Enter] if you own the GTA VC and have its Gamedata or press [Ctrl + C] to cancel and exit.

# Download required assets
cd ~/
wget https://github.com/Jai-JAP/RPi-GTA-re/raw/main/reVC-rel-arm.zip -O ~/reVC.zip || error "Failed to download reVC.zip"
wget https://github.com/Jai-JAP/RPi-GTA-re/raw/main/reVC-gamefiles.zip -O ~/reVC.zip || error "Failed to download reVC-gamefiles.zip"

# Install dependencies and app
package_is_new_enough libglfw3 3.3.2-1
if [[ $? != "0" ]]; then
  install_packages http://deb.debian.org/debian/pool/main/g/glfw3/libglfw3_3.3.2-1_armhf.deb || exit 1
else
  install_packages libglfw3 || exit 1
fi
mkdir -p ${HOME}/Games/GTAVC || error "Failed to create directory ${HOME}/Games/GTAVC"
unzip ~/reVC.zip -d ${HOME}/Games/GTAVC || error "Failed to unzip downloaded ~/reVC.zip to ${HOME}/Games/GTAVC"
unzip ~/reVC-gamefiles.zip -d ${HOME}/Games/GTAVC || error "Failed to unzip downloaded ~/reVC-gamefiles.zip to ${HOME}/Games/GTAVC"

cp ${DIRECTORY}/icon-64.png ${HOME}/Games/GTAVC/reVC.png

echo -e " \\e[1;32m GTAVC succesfully installed at ${HOME}/Games/GTAVC
 Copy all folders from your GTA VC copy (or) installation to this directory. \\e[39m"
 
cat <<EOF >~/.local/share/applications/GTAVC.desktop
[Desktop Entry]
Name=Grand Theft Auto Vice City
Version=1.0
Type=Application
Comment=Grand Theft Auto VC is a 2002 open-world video game that takes place in the middle of the 80's in a fictional place called Vice City.
Exec=${HOME}/Games/GTAVC/reVC
Icon=${HOME}/Games/GTAVC/reVC.png
Path=${HOME}/Games/GTAVC/
Terminal=false
Categories=Game;
EOF

# Cleaning up
rm ~/reVC.zip
rm ~/reVC-gamefiles.zip

exit 0
