#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

rm -f ~/Games/GTAVC/reVC ~/Games/GTAVC/gamecontrollerdb
rm -rf ~/Games/GTAVC/data ~/Games/GTAVC/models ~/Games/GTAVC/neo ~/Games/GTAVC/TEXT
rm -f ~/.local/share/applications/GTAIII.desktop
purge_packages #non-fatal

echo -e " \\e[1;32m GTA VC successfully uninstalled, but your Gamedata and config files are still located at ${HOME}/Games/GTAVC \\e[39m"

exit 0
