#!/bin/bash

install_packages python3 python3-pip python3-dev fonts-powerline fonts-fantasque-sans || exit 1

# install pipx keeping in mind distro issues
# pipx <= 0.16.1 is compatible with 3.7 <= python3 < 3.9
# pipx >= 0.16.1 is compatible with python3 >= 3.7
# some distros lack pipx entirely
# some distros (raspbian bullseye specifically) have incompatible combinations of pipx (0.12.3) and python3 (3.9) versions, necessitating pipx to be installed/upgraded from pip
if package_available pipx && package_is_new_enough pipx 0.16.1 ;then
  install_packages pipx python3-venv || exit 1
elif package_available pipx && ! package_is_new_enough pipx 0.16.1 && ! package_is_new_enough python3 3.9 ;then
  install_packages pipx python3-venv || exit 1
elif package_available pipx && ! package_is_new_enough pipx 0.16.1 && package_is_new_enough python3 3.9 ;then
  install_packages python3-venv || exit 1
  sudo -H python3 -m pip install --upgrade pipx || exit 1
elif package_is_new_enough python3 3.7 ; then
  install_packages python3-venv || exit 1
  sudo -H python3 -m pip install --upgrade pipx || exit 1
elif package_available python3.8 ;then
  install_packages python3.8 python3.8-venv || exit 1
  sudo -H python3.8 -m pip install pipx || exit 1
else
  error "pipx is not available so cannot install powerline-shell to python venv"
fi

sudo PIPX_HOME=/usr/local/pipx PIPX_BIN_DIR=/usr/local/bin pipx install powerline-shell || error "Failed to install powerline shell with pipx"

#Remove powerline-shell function from ~/.bashrc if already there
sed -i '/powerline-shell/d' ~/.bashrc
# Remove powerline-shell function from /etc/bash.bashrc if already there
sudo sed -i '/powerline-shell/d' /etc/bash.bashrc

#Add powerline to /etc/bash.bashrc
echo 'if [ $TERM != linux ] && [[ ! $PROMPT_COMMAND =~ "powerline-shell" ]]; then PROMPT_COMMAND="PS1="\"""\$"(powerline-shell)"\""; $PROMPT_COMMAND" ; fi' | sudo tee -a /etc/bash.bashrc > /dev/null || error "Could not modify /etc/bash.bashrc"
#Also add to users ~/.bashrc . Some terminals (eg: gnome-terminal) overwrite the PROMPT_COMMAND with their own contents after /etc/bash.bashrc so is necessary for them
#The following will only affect the current users install
echo 'if [ $TERM != linux ] && [[ ! $PROMPT_COMMAND =~ "powerline-shell" ]]; then PROMPT_COMMAND="PS1="\"""\$"(powerline-shell)"\""; $PROMPT_COMMAND" ; fi' | tee -a ~/.bashrc > /dev/null || error "Could not modify ~/.bashrc"
