#!/bin/bash

purge_packages || error "Dependencies failed to uninstall"
wget -qO- https://raw.githubusercontent.com/techcoder20/RPI-PowerlineShell-Installer/main/uninstall.sh | bash || error "uninstall.sh failed!"
