#!/bin/bash

# note: do not check exit code from pipx since exit code is set to 1 if not already installed
pipx_uninstall powerline-shell || exit 1
purge_packages || exit 1

#Remove powerline-shell function from ~/.bashrc if already there
sed -i '/powerline-shell/d' ~/.bashrc
# Remove powerline-shell function from /etc/bash.bashrc if already there
sudo sed -i '/powerline-shell/d' /etc/bash.bashrc
