#!/bin/bash

install_packages flatpak || exit 1

flatpak_install librepcb || exit 1

sudo rm -f /var/lib/flatpak/exports/share/applications/org.librepcb.LibrePCB.desktop
echo "[Desktop Entry]
Type=Application
Version=1.0
Terminal=false
Icon=$(dirname "$0")/icon-64.png
Categories=Development;Electronics;
Exec=flatpak run org.librepcb.LibrePCB
Keywords=pcb;circuit;board;Projectmanager;
Name=LibrePCB
Comment=Electronic Design Automation suite" > ~/.local/share/applications/librepcb.desktop || error "Failed to create menu button!"
