#!/bin/bash
# Get dependencies
install_packages flatpak || exit 1
sudo -E flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

flatpak install -y librepcb

echo "[Desktop Entry]
Type=Application
Version=1.0
Terminal=false
Icon=$(dirname "$0")/icon-64.png
Categories=Development;Electronics;
Exec=flatpak run org.librepcb.LibrePCB
Keywords=pcb;circuit;board;Projectmanager;
Name=LibrePCB
Comment=Electronic Design Automation suite" > ~/.local/share/applications/librepcb.desktop || error "Failed to create menu button!"
