#!/bin/bash
#Defining Variables
name=pycharm-community
purge_packages || error "Dependencies failed to uninstall"

echo "Deleting /opt/$name directory"
sudo rm -rf /opt/$name || error "Failed to delete /opt/$name directory"
rm -f ~/.local/share/applications/jetbrains-pycharm-ce.desktop
