#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

#Defining Variables
name=pycharm-community

purge_packages || error "Dependencies failed to uninstall"

echo "Deleting /opt/$name directory"
sudo rm -rf /opt/$name || error "Failed to delete /opt/$name directory"

rm -f ~/.local/share/applications/jetbrains-pycharm-ce.desktop
