#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

echo -n "Removing files... "

rm -f ~/.local/share/applications/*gbmplfifepjenigdepeahbecfkcalfhg*
rm -rf ./zoom-pwa
rm -rf ~/.config/Zoom-PWA

echo Done
