#!/bin/bash

# buster version number
version=1.5-1+3.3
# bullseye version number
version2=1.5-1+3.3
# ubuntu focal version number
version3=1.5-1+3.1

if [[ $(get_codename) == "buster" ]]; then
  use_version="$version"
  release="Raspbian_10"
elif [[ $(get_codename) == "bullseye" ]]; then
  use_version="$version2"
  release="Debian_11"
elif [[ $(get_codename) == "focal" ]]; then
  use_version="$version3"
  release="xUbuntu_20.04"
else
  warning "OS unknown, defaulting to raspbian buster packages"
  use_version="$version"
  release="Raspbian_10"
fi

install_packages https://download.opensuse.org/repositories/home:/IBBoard:/cawbird/${release}/arm64/cawbird_${use_version}_arm64.deb gstreamer1.0-libav || exit 1
