#!/bin/bash

APPDIR=${HOME}/.local/share/applications
WINEDIR=${HOME}/.wine

#Unregistering OCX/DLL files from your wineprefix
BOX86_NOBANNER=1 BOX64_NOBANNER=1 WINEDEBUG=-all wine regsvr32 ${WINEDIR}/drive_c/VARA/OCX/* /u /s # note: some DLL's don't have built-in register/unregister functions and will error

#Removing program files (keeping any VARA.ini settings files)
mv ${WINEDIR}/drive_c/VARA/VARA.ini /tmp/VARA.ini 2>/dev/null
rm -rf ${WINEDIR}/drive_c/VARA/* 2>/dev/null || error 'Could not remove VARA program files.'
mv /tmp/VARA.ini ${WINEDIR}/drive_c/VARA/VARA.ini 2>/dev/null
if [ $(ls -A "${WINEDIR}/drive_c/VARA" | wc -l) -eq 0 ]; then rm -rf "${WINEDIR}/drive_c/VARA" 2>/dev/null; fi #also delete directory if empty

#Removing Desktop Entry
rm ${APPDIR}/VARA/varahf.desktop 2>/dev/null || echo "Could not remove menu button."
if [ $(ls -A "${APPDIR}/VARA" | wc -l) -eq 0 ]; then rm -rf "${APPDIR}/VARA" 2>/dev/null; fi #also delete directory if empty
