#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

rm -rf ~/zoom
rm -f ~/.local/share/applications/zoom.desktop

"${DIRECTORY}/purge-installed" "$(dirname "$0")" || exit 1

if [ -d ~/.zoom ] || [ -f ~/.config/zoomus.conf ];then
  echo "To prevent data loss, Zoom's settings have not been deleted.
Delete them with this command:
rm -rf ~/.zoom ~/.config/zoomus.conf"
fi
