#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

wget https://remarkableapp.github.io/files/remarkable_1.87_all.deb || error 'Failed to Download!'

sudo apt --fix-broken -y install ./remarkable_1.87_all.deb || error 'Failed to install!'
rm remarkable_1.87_all.deb
