#!/bin/bash

install_packages https://remarkableapp.github.io/files/remarkable_1.87_all.deb \
  http://ftp.br.debian.org/debian/pool/main/w/webkitgtk/gir1.2-webkit-3.0_2.4.11-3_arm64.deb \
  http://ftp.br.debian.org/debian/pool/main/w/webkitgtk/libjavascriptcoregtk-3.0-0_2.4.11-3_arm64.deb \
  http://ftp.br.debian.org/debian/pool/main/i/icu/libicu57_57.1-6+deb9u4_arm64.deb \
  http://ftp.br.debian.org/debian/pool/main/w/webkitgtk/libwebkitgtk-3.0-0_2.4.11-3_arm64.deb \
  http://ftp.br.debian.org/debian/pool/main/w/webkitgtk/gir1.2-javascriptcoregtk-3.0_2.4.11-3_arm64.deb

