#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

#downloads
wget https://remarkableapp.github.io/files/remarkable_1.87_all.deb || error 'Failed to Download remarkable_1.87_all'
wget http://ftp.br.debian.org/debian/pool/main/w/webkitgtk/gir1.2-webkit-3.0_2.4.11-3_arm64.deb || error 'Failed to Download gir1.2-webkit-3.0'
wget http://ftp.br.debian.org/debian/pool/main/w/webkitgtk/libjavascriptcoregtk-3.0-0_2.4.11-3_arm64.deb || error 'Failed to Download libwebkitgtk'
wget http://ftp.br.debian.org/debian/pool/main/i/icu/libicu57_57.1-6+deb9u4_arm64.deb || error 'Failed to Download libicu57'
wget http://ftp.br.debian.org/debian/pool/main/w/webkitgtk/libwebkitgtk-3.0-0_2.4.11-3_arm64.deb || error 'Failed to download libwebkitgtk'
wget http://ftp.br.debian.org/debian/pool/main/w/webkitgtk/gir1.2-javascriptcoregtk-3.0_2.4.11-3_arm64.deb || error 'Failed to download gir1.2-javascriptcoregtk'
wget http://ftp.br.debian.org/debian/pool/main/e/enchant/libenchant1c2a_1.6.0-11.1+b1_arm64.deb || error 'Failed to download libenchant1c2a'
wget http://ftp.br.debian.org/debian/pool/main/libj/libjpeg-turbo/libjpeg62-turbo_2.0.6-4_arm64.deb || error 'Failed to download libjpeg62-turbo'


#installation
"${DIRECTORY}/pkg-install" "$(pwd)/gir1.2-webkit-3.0_2.4.11-3_arm64.deb $(pwd)/gir1.2-javascriptcoregtk-3.0_2.4.11-3_arm64.deb $(pwd)/libwebkitgtk-3.0-0_2.4.11-3_arm64.deb $(pwd)/libjavascriptcoregtk-3.0-0_2.4.11-3_arm64.deb $(pwd)/libenchant1c2a_1.6.0-11.1+b1_arm64.deb $(pwd)/libjpeg62-turbo_2.0.6-4_arm64.deb $(pwd)/libicu57_57.1-6+deb9u4_arm64.deb $(pwd)/remarkable_1.87_all.deb" "$(dirname "$0")" || error 'Failed to install libicu57_57.1-6+deb9u4_arm64'

#remove
rm -f remarkable_1.87_all.deb
rm -f gir1.2-webkit-3.0_2.4.11-3_arm64.deb
rm -f libwebkitgtk-3.0-0_2.4.11-3_arm64.deb
rm -f libjavascriptcoregtk-3.0-0_2.4.11-3_arm64.deb
rm -f gir1.2-javascriptcoregtk-3.0_2.4.11-3_arm64.deb
rm -f libicu57_57.1-6+deb9u4_arm64.deb
rm -f libjpeg62-turbo_2.0.6-4_arm64.deb
rm -f libenchant1c2a_1.6.0-11.1+b1_arm64.deb
