#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

rm -f ~/remarkable.deb
wget -O ~/remarkable.deb https://remarkableapp.github.io/files/remarkable_1.87_all.deb || error 'Failed to download remarkable.deb!'

"${DIRECTORY}/pkg-install" "$HOME/remarkable.deb" "$(dirname "$0")" || error "Failed to install ~/remarkable.deb!"
rm -f ~/remarkable.deb
