#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$(dirname "$0")")")"
function error {
  echo -e "\e[31m$1\e[39m"
  exit 1
}

#use the error function often!
#If a certain command is necessary for installation to continue, then add this to the end of it:
# || error 'reason'
#example below:

#Download java and launcher
mkdir ~/Minecraft && cd ~/Minecraft && wget https://www.dropbox.com/s/2602i5d0h4kteex/setupMC.sh && chmod +x setupMC.sh && ./setupMC.sh || error 'Failed to download launcher!'

#Move launcher to /usr/share/
sudo mkdir /usr/share/minecraftjava && sudo mv launcher.jar /usr/share/minecraftjava/launcher.jar 

#Create desktop shortcut
echo "[Desktop Entry]
[Desktop Entry]
Version=1.0
Type=Application
Name=Minecraft Launcher
Comment=3D block based sandbox game
Icon=/home/pi/pi-apps/apps/Minecraft\ \(Experimental\)/icon-64.png
Exec=java -jar /usr/share/minecraftjava/launcher.jar
Categories=Game;" > ~/.local/share/applications/minecraft.desktop

sudo chmod +x ~/.local/share/applications/minecraft.desktop

#Edit launcher profile
echo ''
echo 'This step requires manual work'
echo 'The luancher will now open. Please log in and follow the instructions at https://www.noxxtech.tk/minecraft-install#h.fpnon3xvmuoz'
java -jar /usr/share/minecraftjava/launcher.jar
