#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

echo "Allowing scratch2 package to be uninstallable..."
echo "scratch2 install" | sudo dpkg --set-selections

sudo apt purge scratch2 -y || error "Failed to uninstall scratch2 package"
