#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

rm -f flameshot_armhf.deb
wget -O flameshot_armhf.deb https://osdn.mirror.constant.com/storage/g/r/ra/raspbian-addons/debian/pool/main/f/flameshot/flameshot_0.9.0-1_armhf.deb || error 'Failed to download flameshot deb file'
sudo apt install ./flameshot_armhf.deb -yf || error 'Failed to install flameshot'
rm -f flameshot_armhf.deb

