#!/bin/bash

version=11.0.0
debian_version="$(cat /etc/os-release | grep -om1 '[0-9]*')"
install_packages https://github.com/flameshot-org/flameshot/releases/download/v${version}/flameshot-${version}-1.debian-${debian_version}.armhf.deb || exit 1
