#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

rm -f flameshot_armhf.deb
wget -O flameshot_armhf.deb https://github.com/flameshot-org/flameshot/releases/download/v0.10.0/flameshot-0.10.0.rc1-1.debian-10.armhf.deb || error 'Failed to download flameshot deb file'
sudo apt install ./flameshot_armhf.deb -yf || error 'Failed to install flameshot'
rm -f flameshot_armhf.deb

