#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

# Install snapd first 
"${DIRECTORY}/pkg-install" "snapd" "$(dirname "$0")" || error "Failed installing snapd!"

sudo snap install telegram-desktop || snap install telegram-desktop

# Change menu launcher name 
sed -i s/"Name=Telegram Desktop"/"Name=Telegram"/g /usr/share/applications/snap/telegram-desktop_telegram-desktop.desktop || sudo sed -i s/"Name=Telegram Desktop"/"Name=Telegram"/g /usr/share/applications/snap/telegram-desktop_telegram-desktop.desktop
