#!/bin/bash

function error {
  echo -e "\e[31m$1\e[39m"
  exit 1
}

#curl -fsSL https://pi.vpetkov.net -o ventz-media-pi || error "Failed to download the script!"
#sh ventz-media-pi || error "Failed to run the script!"

sudo cp "$(dirname "$0")/chromium-media-browser.desktop" /usr/share/applications/ || error "failed to create menu button!"
sudo cp "$(dirname "$0")/libwidevinecdm.so" /usr/lib/chromium-browser/ || error "Failed to copy libwidevinecdm.so!"
