#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

sudo rm /usr/lib/chromium-browser/libwidevinecdm.so || error "failed to delete libwidevinecdm.so!"
sudo rm /usr/share/applications/chromium-media-browser.desktop || error "failed to delete menu button!"
