#!/bin/bash
rm -rf ~/All-is-well || error "Failed to first remove ~/All-is-well folder!"
git_clone https://github.com/spectrumgamer75/All-is-well || error "Failed to download!"
cd $HOME/All-is-well/aiw
chmod +x 'aiwrpi.sh'
echo "alias aiw=$HOME/All-is-well/aiw/aiwrpi.sh" >> ~/.bashrc
echo "[Desktop Entry]
Name=All Is Well
GenericName=Update Helper and Fixer
Comment=ALL IS WELL is a bash script that allows users to easily update and upgrade their repositories and packages on linux. It will also fix any broken packages and dependencies.
Exec=$DIRECTORY/etc/terminal-run $HOME/All-is-well/aiw/aiwrpi.sh 'All Is Well'
Icon=$(dirname "$0")/icon-64.png
Terminal=false
StartupNotify=true
Type=Application
Categories=Utility;" > ~/.local/share/applications/aiw.desktop || error "Failed to create menu button!"
