#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

"${DIRECTORY}/purge-installed" "$(dirname "$0")" || exit 1

rm -rf $HOME/Codex || sudo rm -rf $HOME/Codex || error "Failed to remove Codex directory!"
rm -f $HOME/.local/share/applications/codex.desktop || sudo rm -f $HOME/.local/share/applications/codex.desktop || error "Failed remove menu shortcut!"
