#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

#Uninstall NodeJS
sudo apt purge nodejs -y || error "Failed to purge Node.JS!"
sudo apt autoremove -y #who cares if this fails?

#remove /etc/apt/sources.list.d/nodesource.list
sudo rm /etc/apt/sources.list.d/nodesource.list || error "Failed to remove nodesource repo!"

#if your app installs any packages, keep this command here so those packages will be removed.
"${DIRECTORY}/purge-installed" "$(dirname "$0")" || exit 1