#!/bin/bash

# Get dependencies
install_packages python3 python3-pip python3-dev || error "Failed to install dependencies"

cd /tmp
rm -rf /opt/sysmon || sudo rm -rf /opt/sysmon || error "Failed to first remove /opt/sysmon folder!"
rm -rf /tmp/sysmon || sudo rm -rf /tmp/sysmon || error "Failed to first remove /tmp/sysmon folder!"

git_clone https://github.com/t0xic0der/sysmon || error "Failed to clone Sysmon git repository!"
sudo mv -f /tmp/sysmon /opt  || error "Failed to move folder from /tmp to /opt!"
cd /opt/sysmon
sudo pip3 install -r requirements.txt || error "Failed to install requirements with Pip!"

echo "[Unit]
After=network.target
[Service]
ExecStart=sudo python3 /opt/sysmon/main.py -p 6969 -6
[Install]
WantedBy=default.target" | sudo tee /etc/systemd/system/WebStationSYSMON.service >/dev/null

#start the service
sudo systemctl daemon-reload || error "Failed to run systemctl daemon-reload!"
sudo systemctl enable WebStationSYSMON.service || error "Failed to enable sysmon service!"
sudo systemctl start WebStationSYSMON.service || error "Failed to start sysmon service!"
