#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

sudo rm -rf /usr/local/bin/btop || error 'Failed to remove "/usr/local/bin/btop"'
echo -e '\n\e[1;33mHey, just so you know, the "/usr/local/share/btop" directory has not been removed, so all your preferences are still there. If you want, you can delete this directory like this: "sudo rm -rf /usr/local/share/btop".\e[0m\n\nWaiting 10 seconds...'
sleep 10
