#!/bin/bash
install_packages python3 python3-pyqt5 python3-pyqt5.qtwebkit python3-pip python3-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-alsa gstreamer1.0-libav || error "Failed to install dependencies"

cd $HOME
rm -rf quartz-browser-qt5 || sudo rm -rf quartz-browser-qt5 
git_clone https://github.com/ksharindam/quartz-browser-qt5
cd quartz-browser-qt5
pip3 install . || sudo pip3 install . 
