#!/bin/bash

version=2025.09.24
INSTALL_DIR=${INSTALL_DIR:-~/.local/share}

rm -f /tmp/tbb-nightly.tar.xz
wget -O /tmp/tbb-nightly.tar.xz "https://nightlies.tbb.torproject.org/nightly-builds/tor-browser-builds/tbb-nightly.$version/nightly-linux-aarch64/tor-browser-linux-aarch64-tbb-nightly.$version.tar.xz" || error "Failed to download Tor Browser Nightly ver. $version"

status 'Looking for previous installations and remaining user data... '
if [ -d "$INSTALL_DIR"/tor-browser-nightly ]; then
  #if data folder exists, prepare to import its user-data
  if [ -d "$INSTALL_DIR"/tor-browser-nightly/Browser/TorBrowser/Data/Browser ];then
    mv -f "$INSTALL_DIR"/tor-browser-nightly/Browser/TorBrowser/Data/Browser/ "$INSTALL_DIR"/tor-browser-nightly.temp/ || error 'Failed to move existing user data to temporary folder'
  fi
  rm -rf "$INSTALL_DIR"/tor-browser-nightly/* || error 'Failed to remove old Tor Browser files'
else
  mkdir -p "$INSTALL_DIR"/tor-browser-nightly || error 'Failed to create installation directory'
fi
status_green 'Done'

status "Extracting Tor Browser to $INSTALL_DIR/tor-browser-nightly ... "
tar -xpJf /tmp/tbb-nightly.tar.xz -C "$INSTALL_DIR"/tor-browser-nightly --strip-components=1 || error 'Failed to extract Tor Browser'
rm -f /tmp/tbb-nightly.tar.xz
status_green 'Done'

#if tor-browser.temp folder exists, import its user-data
if [ -d "$INSTALL_DIR"/tor-browser-nightly.temp ];then
  status 'Importing existing user data... '
  rm -rf "$INSTALL_DIR"/tor-browser-nightly/Browser/TorBrowser/Data/Browser
  mv -f "$INSTALL_DIR"/tor-browser-nightly.temp "$INSTALL_DIR"/tor-browser-nightly/Browser/TorBrowser/Data/Browser
  rm -rf "$INSTALL_DIR"/tor-browser-nightly.temp
  status_green 'Done'
fi

status 'Registering Tor Browser as a desktop app for this user'
cd "$INSTALL_DIR"/tor-browser-nightly || error 'Fatal error! Cannot cd to app!'
"$INSTALL_DIR"/tor-browser-nightly/start-tor-browser.desktop --register-app || error 'Failed to register a desktop app'
status_green 'Done'
