#!/bin/bash

INSTALL_DIR=${INSTALL_DIR:-~/.local/share}

status 'Unregistering Tor Browser desktop app... '
cd "$INSTALL_DIR"/tor-browser-nightly || error 'Fatal error! Cannot cd to app!'
"$INSTALL_DIR"/tor-browser-nightly/start-tor-browser.desktop --unregister-app || error 'Failed to unregister a desktop app'
status_green 'Done'

status 'Copying user data files to temporary folder...'
if [ -d "$INSTALL_DIR"/tor-browser-nightly/Browser/TorBrowser/Data/Browser ];then
  rm -rf "$INSTALL_DIR"/tor-browser-nightly.temp
  mv -n "$INSTALL_DIR"/tor-browser-nightly/Browser/TorBrowser/Data/Browser "$INSTALL_DIR"/tor-browser-nightly.temp
fi
status_green 'Done'

status 'Removing all browser internals...'
rm -rfv "$INSTALL_DIR"/tor-browser-nightly || error "Cannot remove $INSTALL_DIR/tor-browser-nightly directory"
status_green 'Done'

#move back the temporary folder containing user-data
if [ -d "$INSTALL_DIR"/tor-browser-nightly.temp ];then
  status 'Moving user data files back...'
  mkdir -p "$INSTALL_DIR"/tor-browser-nightly/Browser/TorBrowser/Data
  mv "$INSTALL_DIR"/tor-browser-nightly.temp "$INSTALL_DIR"/tor-browser-nightly/Browser/TorBrowser/Data/Browser
  status_green 'Done'

  #let the user know where configuration is
  echo "Tor Browser has been uninstalled, but user-data like settings and bookmarks remain intact.
To remove these files, run this command:
rm -rf $INSTALL_DIR/tor-browser-nightly"
  
fi