#!/bin/bash

version=1.3.4

if [ "$XDG_SESSION_TYPE" == wayland ];then
  install_packages https://github.com/rustdesk/rustdesk/releases/download/${version}/rustdesk-${version}-aarch64.deb xdg-desktop-portal-wlr || exit 1
else
  install_packages https://github.com/rustdesk/rustdesk/releases/download/${version}/rustdesk-${version}-aarch64.deb || exit 1
fi
