#!/bin/bash

version=1.3.9

if [ "$XDG_SESSION_TYPE" == wayland ];then
  install_packages https://github.com/rustdesk/rustdesk/releases/download/${version}/rustdesk-${version}-armv7-sciter.deb xdg-desktop-portal-wlr || exit 1
else
  install_packages https://github.com/rustdesk/rustdesk/releases/download/${version}/rustdesk-${version}-armv7-sciter.deb || exit 1
fi
