#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

git clone https://github.com/Botspot/Boxy-SVG-RPi || error 'Failed to clone repository!'

tar -xf ~/Boxy-SVG-RPi/BoxySVG-linux-arm64.tar.xz || error 'Failed to extract!'
cp ~/Boxy-SVG-RPi/boxy-svg-arm64.desktop ~/.local/share/applications
