#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

rm ~/.local/share/applications/boxy-svg-arm64.desktop ~/.local/share/applications/boxy-svg-armv7l.desktop
rm -rf ~/BoxySVG-linux-arm64 ~/BoxySVG-linux-armv7l ~/Boxy-SVG-RPi

