#!/bin/bash

version=2021.3.3

# Get dependencies
install_packages openjdk-11-jdk || exit 1
rm -f ideaIC-${version}.tar.gz 2>/dev/null

rm -rf ~/idea_ic 2>/dev/null
mkdir ~/idea_ic || error "Failed to make idea_ic folder!"
cd ~/idea_ic
wget https://download.jetbrains.com/idea/ideaIC-${version}.tar.gz || error "Failed to download!"
tar xf ideaIC-${version}.tar.gz --strip-components=1 || error "Failed to extract!"
rm -f ideaIC-${version}.tar.gz 2>/dev/null
echo "[Desktop Entry]
Type=Application
Version=${version}
Name=IntelliJ IDEA
Path=$HOME/idea_ic/bin
Exec=$HOME/idea_ic/bin/idea.sh
Comment=A fast and lightweight IDE using GTK+
Icon=$HOME/idea_ic/bin/idea.png
Categories=Development;IDE;
StartupNotify=true" > ~/.local/share/applications/intellijidea.desktop
