#!/bin/bash

version=2021.3.3

# Get dependencies
install_packages openjdk-11-jdk || exit 1

sudo rm -rf /opt/ideaIC /opt/ideaIC.tar.gz
sudo mkdir /opt/ideaIC || error "Failed to make idea_ic folder!"
wget https://download.jetbrains.com/idea/ideaIC-${version}.tar.gz /tmp/ideaIC.tar.gz || error "Failed to download!"

cd /opt/ideaIC
sudo tar xf /tmp/ideaIC.tar.gz --strip-components=1 || error "Failed to extract ideaIC.tar.gz!"
rm -f /tmp/ideaIC.tar.gz

echo "[Desktop Entry]
Type=Application
Version=${version}
Name=IntelliJ IDEA
Path=/opt/ideaIC/bin
Exec=bash -c "\""JAVA_HOME=/usr/lib/jvm/java-11-openjdk-armhf PATH=/usr/lib/jvm/java-11-openjdk-armhf/bin/:$PATH /opt/ideaIC/bin/idea.sh"\""
Comment=A fast and lightweight IDE using GTK+
Icon=/opt/ideaIC/bin/idea.png
Categories=Development;IDE;
StartupNotify=true" | sudo tee /usr/share/applications/intellijidea.desktop >/dev/null
