#!/bin/bash

purge_packages || exit 1
sudo rm -rf /opt/ideaIC /usr/share/applications/intellijidea.desktop
# cleanup files leftover from potential failed install
rm -rf  $HOME/fsnotifier-pycharm-rpi  $HOME/fsnotifier-pycharm-rpi.zip
