#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

#if your app installs any packages, keep this command here so those packages will be removed.
purge_packages || error "Dependencies failed to uninstall"
rm -rf ~/idea_ic 2>/dev/null
rm ~/.local/share/applications/intellijidea.desktop

exit 0
