#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

"${DIRECTORY}/purge-installed" "$(dirname "$0")" || exit 1

sudo apt remove minecraft-pi-native mcpil-r -y
sudo apt autoremove -y

sudo mv /etc/apt/sources.list.bak /etc/apt/sources.list
sudo rm /etc/apt/sources.list.d/Alvarito050506_mcpi-devs.list
sudo apt update
