#!/bin/bash
VERSION=arduino-1.8.19

cd ~/.local/share
wget https://downloads.arduino.cc/$VERSION-linuxaarch64.tar.xz || error "failed to download!"
tar -xf $(pwd)/$VERSION-linuxaarch64.tar.xz || error "failed to extract with tar!"
sudo $(pwd)/$VERSION/install.sh || error "failed to run Arduino install script!"
rm -f $HOME/Desktop/arduino-arduinoide.desktop $(pwd)/$VERSION-linuxaarch64.tar.xz
