#!/bin/bash
version=1.8.19

cd ~/.local/share
wget -O $(pwd)/arduino-${version}-linuxaarch64.tar.xz https://downloads.arduino.cc/arduino-${version}-linuxaarch64.tar.xz || error "failed to download!"

tar -xf $(pwd)/arduino-${version}-linuxaarch64.tar.xz || error "failed to extract with tar!"
sudo $(pwd)/arduino-${version}/install.sh || error "failed run Arduino install script!"
rm -f $HOME/Desktop/arduino-arduinoide.desktop $(pwd)/arduino-${version}-linuxaarch64.tar.xz

if package_installed brltty ; then
  echo "Removing brltty package because it makes it impossible to connect to arduino boards..."
  apt_lock_wait
  sudo apt purge -y brltty
fi
