#!/bin/bash

rm -rf ~/.local/share/applications/MiUnlocktool.desktop ~/XiaoMiToolV2
echo "Do you wanna uninstall dependencies installed in install script?"
echo -ne "Type in your answer [y/N]: "
read ans
if [ "$ans" == N ] || [ "$ans" == n ] || [ -z "$ans" ]; then
exit 0
fi
sudo apt purge -y openjfx nautilus android-tools-adb android-tools-fastboot openjdk-11-jdk
echo " "
echo "Successfully uninstalled Mi Unlock Tool!"
exit 0
