#!/bin/bash
echo "Removing dependencies..."
purge_packages || exit 1
echo "Removing $HOME/wor-flasher folder..."
rm -rf ~/wor-flasher || sudo rm -rf ~/wor-flasher || error "Failed to remove ~/wor-flasher folder!"
echo "Removing menu button..."
rm -f ~/.local/share/applications/wor-flasher.desktop
if [ -d ~/wor-flasher-files ];then
  echo -e "\nDuring use, WoR-flasher downloads all files to $HOME/wor-flasher-files\nThis folder exists right now.\nFeel free to delete that folder to save disk space.\n"
fi
