#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}
"${DIRECTORY}/purge-installed" "$(dirname "$0")" || exit 1

if [ -f /opt/tboplayer/setup.sh ];then
  #run uninstall script, saying 'yes' to the first question, and 'no' to the second question
  echo -e "y\nn" | /opt/tboplayer/setup.sh uninstall || error "failed to uninstall!"
fi
exit 0
