#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

install_packages vlc yad imagemagick jq python python3-pip python3-dev || error "Failed to install dependencies"

rm -rf ~/youtubuddy
git clone https://github.com/Botspot/youtubuddy || error 'Failed to clone youtubuddy repository!'
~/youtubuddy/gui install || error "YouTubuddy install procedure exited somehow!"

