#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

git clone https://github.com/Botspot/youtubuddy || error 'Failed to clone youtubuddy repository!'
~/youtubuddy/gui install || error "YouTubuddy install procedure exited somehow!"

