#!/bin/bash

version=processing-1292-4.2

cd ~/.local/share/
rm -rf processing-*
wget "https://github.com/processing/processing4/releases/download/${version}/processing-$(echo ${version} | awk '{n=split($1,A,"-"); print A[n]}')-linux-arm32.tgz" || error "failed to download"
tar -xf processing-*.tgz || error "failed to extract"
rm processing-*.tgz
sudo ~/.local/share/processing*/install.sh
