#!/bin/bash

function error {
	echo -e "\\e[91m$1\\e[39m"
	exit
}

cd ~/.local/share/
wget http://download.processing.org/processing-3.5.3-linux-armv6hf.tgz || error "failed to download"
tar -xf processing-3.5.3-linux-armv6hf.tgz || error "failed to extract"
rm processing-3.5.3-linux-armv6hf.tgz
sudo ~/.local/share/processing*/install.sh
