#!/bin/bash

version=v5.2.0

#Install Depends
install_packages libfuse2 || exit 1

#Download Open-Typer build from repo
wget -O /tmp/Open-Typer.AppImage https://github.com/Open-Typer/Open-Typer/releases/download/${version}/Open-Typer-aarch64.AppImage || error "Failed to download AppImage!"

#Move Open-Typer.AppImage to /opt
sudo mv /tmp/Open-Typer.AppImage /opt || error "Failed to move from /tmp to /opt!"

#Mark Open-Typer.AppImage as executable
sudo chmod +x /opt/Open-Typer.AppImage || error "Failed to mark as executable!"

#Create Menu Button
status "Creating Menu Button"
sudo mkdir -p /usr/local/share/applications
echo "[Desktop Entry]
Name=Open-Typer
Comment=An Open Source spiritual successor to the flash game Line Rider
Icon=$(dirname "$0")/icon-64.png
Exec=/opt/Open-Typer.AppImage %f
Type=Application
Terminal=false
Categories=Utility;" | sudo tee /usr/local/share/applications/Open-Typer.desktop >/dev/null || error "Failed to create menu button!"
