#!/bin/bash

cd $HOME
mkdir -p xdm 
cd xdm
wget -O adoptopenjdk-16-hotspot.deb "https://adoptopenjdk.jfrog.io/ui/api/v1/download?repoKey=deb&path=pool%252Fmain%252Fa%252Fadoptopenjdk-16-hotspot%252Fadoptopenjdk-16-hotspot_16.0.1%252B9-3_armhf.deb"

"${DIRECTORY}/pkg-install" "$(pwd)/adoptopenjdk-16-hotspot.deb ffmpeg" "$(dirname "$0")" || error "Failed installing openjdk!"

wget -O xdm.tar.xz https://github.com/subhra74/xdm/releases/download/7.2.11/xdm-setup-7.2.11.tar.xz || error "Failed to download XDM setup tar file!"
wget https://github.com/ytdl-org/youtube-dl/releases/download/2021.06.06/youtube-dl || error "Failed to download youtube-dl binary!"
tar -xf xdm.tar.xz || error "Failed to extract XDM setup tar file!"
sudo ./install.sh | grep -v "Installation completed" || error "Failed to execute XDM setup script!"
sudo chmod +x ./youtube-dl
sudo mv -f ./youtube-dl /opt/xdman || error "Failed to copy youtube-dl binary!"

# Use system java
sudo sed -i s=/opt/xdman/jre/bin/java=$(command -v java)=g /opt/xdman/xdman || error "Failed to change to system Java runtime in /opt/xdman/xdman!"
sudo sed -i s=/opt/xdman/jre/bin/java=$(command -v java)=g /usr/bin/xdman || error "Failed to change to system Java runtime in /usr/bin/xdman!"

# Fix 'Download failed. Failed to append/convert file parts, please check if the drive is full or write protected'
sudo cp -f $(command -v ffmpeg) /opt/xdman || error "Failed to copy ffmpeg binary!"

# Delete unwanted files after installation
rm -rf $HOME/xdm || error "Failed to remove installation leftovers!"

# Reminder for users to install browser extensiom
echo -e "\nYou may want to install the XDM browser extension. Simply install it from \e[4mXDM Menu -> Tools -> Browser Monitoring\e[0m page."
