#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

"${DIRECTORY}/purge-installed" "$(dirname "$0")"  || error "Failed to purge-installed!"

sudo rm -rf /opt/xdman || error "Failed to remove /opt/xdman/ directpry!"
sudo rm -f /usr/share/applications/xdman.desktop || error "Failed to remove menu shortcut!"
sudo rm -f /usr/bin/xdman || error "Failed to remove /usr/bin/xdman !"
