#!/bin/bash

status "This script helps you setup a Minecraft-Java-Server (for any version)."

# userinput function to display yad prompts to the user
function userinput_func {
    unset uniq_selection
    if [[ "${#@}" == "2" ]];then
        echo -e "$1" |  yad --show-uri --center --image "dialog-information" --borders="20" --title "User Info Prompt" \
        --text-info --fontname="@font@ 11" --wrap --width=800 --height=200 --window-icon="${DIRECTORY}/apps/Minecraft Java Server/icon-64.png" \
        --show-uri \
        --button="$2":0
        output="$2"
    else
        for string in "${@:2}"; do
        uniq_selection+=(FALSE "$string")
        done
        uniq_selection[0]=TRUE
        output=$(
        yad --center \
            --borders="20" \
            --window-icon="${DIRECTORY}/apps/Minecraft Java Server/icon-64.png" \
            --text "$1" \
            --list \
            --radiolist \
            --center \
            --fixed \
            --height="400" \
            --column "" \
            --column "Selection" \
            --print-column=2 \
            --separator='' \
            --button="Ok":0 \
            "${uniq_selection[@]}"
        )
    fi
}

mkdir -p "$HOME/Minecraft-Java-Server"
cd "$HOME/Minecraft-Java-Server" || error "Could not enter Minecraft-Java-Server folder."

# open browser to download the server version of user choice
setsid x-www-browser "https://mcversions.net/" > /dev/null 2>&1 &
# open folder for user to place the downloaded file
xdg-open "$HOME/Minecraft-Java-Server" 2>/dev/null

# tell user to choose java 8, 16, or 17
description="Please use the website which has opened to download your chosen version of the Minecraft Java Server.\
\n\nIn order to run Minecraft, the game requires a specific version of Java.\
\nPlease choose below which version of java the server of your choice should run with.\
\nJava versions can be 8, 16, or 17.\
\n\nAll version of Minecraft before and including Minecraft 1.16.5 should use Java 8.\
\nMinecraft 1.17.X should use java 16 and Minecraft 1.18.X should use java 17."
table=("Java 17" "Java 16" "Java 8")
userinput_func "$description" "${table[@]}"
java_selection="$output"

while [[ ! -a server.jar ]]; do
    description="Please add your server.jar file to the folder opened and press OK.\
    \n\nYou have not added a server.jar."
    table=("OK")
    userinput_func "$description" "${table[@]}"
done

install_packages lsb-release wget gpg || error "Failed to install dependencies"

case "$java_selection" in
    "Java 8"|"Java 17")
        # temurin repo is NOW live
        # add temurin repo for java 8/11/17
        status "Adding Adoptium repository:"

        echo "- public key -> keyring"
        rm -f /tmp/adoptium-public-key /tmp/adoptium-archive-keyring.gpg
        wget -O /tmp/adoptium-public-key https://adoptium.jfrog.io/artifactory/api/security/keypair/default-gpg-key/public
        gpg --no-default-keyring --keyring /tmp/adoptium-keyring.gpg --import /tmp/adoptium-public-key
        rm -f /tmp/adoptium-public-key

        echo " - keyring -> GPG key"
        gpg --no-default-keyring --keyring /tmp/adoptium-keyring.gpg --export --output /tmp/adoptium-archive-keyring.gpg
        rm -f /tmp/adoptium-keyring.gpg

        echo " - Moving GPG key to /usr/share/keyrings"
        sudo mv -f /tmp/adoptium-archive-keyring.gpg /usr/share/keyrings

        echo " - Creating /etc/apt/sources.list.d/adoptium.list"
        echo "deb [signed-by=/usr/share/keyrings/adoptium-archive-keyring.gpg] https://adoptium.jfrog.io/artifactory/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/adoptium.list >/dev/null
        sudo apt update
        ;;
    "Java 16")
        # add old adoptopenjdk for java 16
        status "Adding AdoptOpenJDK repository:"

        echo "- public key -> keyring"

        rm -f /tmp/adoptopenjdk-public-key /tmp/adoptopenjdk-archive-keyring.gpg
        wget -O /tmp/adoptopenjdk-public-key https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
        gpg --no-default-keyring --keyring /tmp/adoptopenjdk-keyring.gpg --import /tmp/adoptopenjdk-public-key
        rm -f /tmp/adoptopenjdk-public-key

        echo " - keyring -> GPG key"
        gpg --no-default-keyring --keyring /tmp/adoptopenjdk-keyring.gpg --export --output /tmp/adoptopenjdk-archive-keyring.gpg 
        rm -f /tmp/adoptopenjdk-keyring.gpg

        echo " - Moving GPG key to /usr/share/keyrings"
        sudo mv -f /tmp/adoptopenjdk-archive-keyring.gpg /usr/share/keyrings

        echo " - Creating /etc/apt/sources.list.d/adoptopenjdk.list"
        echo "deb [signed-by=/usr/share/keyrings/adoptopenjdk-archive-keyring.gpg] https://adoptopenjdk.jfrog.io/adoptopenjdk/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/adoptopenjdk.list >/dev/null
        sudo apt update
        ;;
    *)
        error "No java version selected, exiting the script"
        ;;
esac

case "$arch" in
    "64")
        case "$java_selection" in
            "Java 8")
                (install_packages temurin-8-jdk)
                if [ $? != 0 ];then
                    sudo rm -f /etc/apt/sources.list.d/adoptium.list /usr/share/keyrings/adoptium-archive-keyring.gpg
                    error "Failed to install temurin packages"
                fi
                java_location="/usr/lib/jvm/java-8-temurin-arm64/bin/java"
                ;;
            "Java 16")
                (install_packages adoptopenjdk-16-hotspot-jre)
                if [ $? != 0 ];then
                    sudo rm -f /etc/apt/sources.list.d/adoptium.list /usr/share/keyrings/adoptium-archive-keyring.gpg
                    error "Failed to install adoptopenjdk packages"
                fi
                java_location="/usr/lib/jvm/adoptopenjdk-16-hotspot-jre-arm64/bin/java"
                ;;
            "Java 17")
                (install_packages temurin-17-jdk)
                if [ $? != 0 ];then
                    sudo rm -f /etc/apt/sources.list.d/adoptium.list /usr/share/keyrings/adoptium-archive-keyring.gpg
                    error "Failed to install temurin packages"
                fi
                java_location="/usr/lib/jvm/java-17-temurin-arm64/bin/java"
                ;;
        esac
        ;;
    "32")
        case "$java_selection" in
            "Java 8")
                (install_packages temurin-8-jdk)
                if [ $? != 0 ];then
                    sudo rm -f /etc/apt/sources.list.d/adoptium.list /usr/share/keyrings/adoptium-archive-keyring.gpg
                    error "Failed to install temurin packages"
                fi
                java_location="/usr/lib/jvm/java-8-temurin-armhf/bin/java"
                ;;
            "Java 16")
                (install_packages adoptopenjdk-16-hotspot-jre)
                if [ $? != 0 ];then
                    sudo rm -f /etc/apt/sources.list.d/adoptium.list /usr/share/keyrings/adoptium-archive-keyring.gpg
                    error "Failed to install adoptopenjdk packages"
                fi
                java_location="/usr/lib/jvm/adoptopenjdk-16-hotspot-jre-armhf/bin/java"
                ;;
            "Java 17")
                (install_packages temurin-17-jdk)
                if [ $? != 0 ];then
                    sudo rm -f /etc/apt/sources.list.d/adoptium.list /usr/share/keyrings/adoptium-archive-keyring.gpg
                    error "Failed to install temurin packages"
                fi
                java_location="/usr/lib/jvm/java-17-temurin-armhf/bin/java"
                ;;
        esac
        ;;
    *)
        error "arch variable is not set, can not continue"
        ;;
esac


sh -c "cat > $HOME/Minecraft-Java-Server/start-server.sh << _EOF_
$java_location -jar $HOME/Minecraft-Java-Server/server.jar nogui
_EOF_"
chmod +x "$HOME/Minecraft-Java-Server/start-server.sh"

# sign eula without starting server
echo "eula=true" > eula.txt

mkdir -p "$HOME/.local/share/applications"
tee "$HOME/.local/share/applications/Minecraft-Java-Server.desktop" <<EOF
[Desktop Entry]
Name=Minecraft Java Server
Exec=$HOME/Minecraft-Java-Server/start-server.sh
Path=$HOME/Minecraft-Java-Server
Icon=${DIRECTORY}/apps/Minecraft Java Server/icon-64.png
Type=Application
Categories=Game
Terminal=true
EOF


status "Your IP address is one of the following: 
$(hostname -I | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')"
status "The IP address is used to play on your local network."
