#!/bin/bash

version=v1.3.4

"${DIRECTORY}/manage" install-if-not-installed ArmCord || error "Failed to install dependency: ArmCord"

cd /tmp || error "Could not move to /tmp directory"
rm -f rpi-4b-aarch64.zip
wget "https://github.com/RiiConnect24/RiiTag-RPC/releases/download/${version}/RiiTag-RPC_Rpi4B" || error "Could not download riitag-rpc release"
sudo chmod a+x RiiTag-RPC_Rpi4B
sudo mv RiiTag-RPC_Rpi4B /usr/local/bin/riitag-rpc || error "Could not install riitag-rpc"
