#!/bin/bash

install_packages https://github.com/Pi-Apps-Coders/files/raw/main/lightpad_0.0.8rev1_arm64.deb || exit 1

echo "[Desktop Entry]
Version=1.0
Type=Application
Name=Lightpad
Icon=lightpad
Exec=com.github.libredeb.lightpad
Comment=LightPad is a lightweight, simple and powerful application launcher
Categories=Accessories;Utility;
Terminal=false" > ~/.local/share/applications/lightpad.desktop


