#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

sudo wget https://github.com/libredeb/lightpad/releases/download/v0.0.8/lightpad_0.0.8.rev1_armhf.deb -P ~/ || error "Failed to download lightpad_0.0.8.rev1_armhf.deb!"

sudo apt install -y --fix-missing ~/lightpad_0.0.8.rev1_armhf.deb || error "APT failed to install lightpad_0.0.8.rev1_armhf.deb!"

rm -f ~/lightpad_0.0.8.rev1_armhf.deb 

echo "[Desktop Entry]
Version=1.0
Type=Application
Name=Lightpad
Icon=lightpad
Exec=com.github.libredeb.lightpad
Comment=LightPad is a lightweight, simple and powerful application launcher
Categories=Accessories;Utility;
Terminal=false" > ~/.local/share/applications/lightpad.desktop


