#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}


sudo apt -y purge lightpad || error "Failed to uninstall lightpad"
sudo apt -y autoremove
rm -f ~/.local/share/applications/lightpad.desktop

