#!/bin/bash

git_clone https://github.com/Jai-JAP/pikiss-gui || error 'Failed to clone PiKISS GUI repository!'

install_packages ninja-build gobject-introspection libgee-0.8-dev libgirepository1.0-dev libgtk-3-dev valac libgnome-menu-3-dev || exit 1
sudo pip3 install meson || error 'Failed to install meson from pip'
"${DIRECTORY}/manage" install-if-not-installed piKiss || error "piKiss failed to install somehow!"

cd pikiss-gui || error 'Failed to cd into pikiss-gui folder'

./build.sh || error 'Failed to build PiKISS GUI'
