#!/bin/bash
purge_packages || exit 1

  if [ -e /etc/systemd/system/lokinet.service.d ]; then
     echo "removing systemd override"
     sudo rm -r /etc/systemd/system/lokinet.service.d
  fi
  if [ -e /etc/systemd/system/lokinet.service ]; then
     echo "removing lokinet service"
     sudo rm /etc/systemd/system/lokinet.service
  fi
  if [ -e /etc/systemd/system/lokinet-testnet.service ]; then
     echo "removing lokinet-testnet.service"
     sudo rm /etc/systemd/system/lokinet-testnet.service
  fi
