#!/bin/bash

version=3.4.0
version2=2.26.0
version3=1.43.12

if package_is_new_enough python3-tk 3.12.3 ; then
  install_packages https://github.com/hakandundar34coding/system-monitoring-center/releases/download/v${version}/system-monitoring-center_${version}_all.deb || exit 1
elif package_available gir1.2-gtk-4.0 ; then
  install_packages https://github.com/hakandundar34coding/system-monitoring-center/releases/download/v${version2}/system-monitoring-center_${version2}_all.deb || exit 1
else
  install_packages https://github.com/hakandundar34coding/system-monitoring-center/releases/download/v${version3}/system-monitoring-center_${version3}_all.deb || exit 1
fi
