#!/bin/bash

version=1.10.2

install_packages https://github.com/hakandundar34coding/system-monitoring-center/releases/download/v${version}/system-monitoring-center_${version}_all.deb hwdata || exit 1
