#!/bin/bash

version=1.28.0

install_packages https://github.com/hakandundar34coding/system-monitoring-center/releases/download/v${version}-deb_for_stores/system-monitoring-center_${version}_all.deb || exit 1
