#!/bin/bash
install_packages libpng-dev || exit 1

rm -rf ~/raspi2png
git_clone https://github.com/AndrewFromMelbourne/raspi2png || error "failed to clone repository!"
cd ~/raspi2png || error "failed to enter directory!"

make || error "failed to compile!"
sudo make install || error "sudo make install failed!"
cd ~/
rm -rf ~/raspi2png || error "failed to delete directory!"
