#!/bin/bash
install_packages libpng-dev libraspberrypi-dev || error "User error: Raspi2png requires bcm_host.h, a file which is included in the libraspberrypi-dev package. Unfortunately, your operating system doesn't have that package, so you're out of luck."

rm -rf ~/raspi2png
git_clone https://github.com/AndrewFromMelbourne/raspi2png || error "failed to clone repository!"
cd ~/raspi2png || error "failed to enter directory!"

make || error "failed to compile!"
sudo make install || error "sudo make install failed!"
cd ~/
rm -rf ~/raspi2png || error "failed to delete directory!"
