#!/bin/bash
rm -rf ~/.cache/cool-retro-term
rm -rf ~/cool-retro-term
rm -f ~/.local/share/applications/crt.desktop

purge_packages || error "Dependencies failed to uninstall"

rm -rf ~/.local/share/cool-retro-term ~/cool-retro-term
