#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

rm -rf ~/.cache/cool-retro-term
rm -rf ~/cool-retro-term
rm -f ~/.local/share/applications/crt.desktop

"${DIRECTORY}/purge-installed" "$(dirname "$0")" || exit 1

rm -rf ~/.local/share/cool-retro-term ~/cool-retro-term
