#!/bin/bash
echo "Installing fish..."
echo "Adding repos..."
echo 'deb http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_11/ /' | sudo tee /etc/apt/sources.list.d/shells:fish:release:3.list
curl -fsSL https://download.opensuse.org/repositories/shells:fish:release:3/Debian_11/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/shells_fish_release_3.gpg > /dev/null
echo "Updating repos..."
sudo apt update
echo "installing fish..."
sudo apt install fish
echo "done!"

clear
#Then make menu shortcut
echo "[Desktop Entry]
Version=1.0
Type=Application
Name=Fish Shell
GenericName=fish
Comment=Friendly Interactive Shell
Icon=$(dirname "$0")/icon-64.png
Exec=/usr/bin/env fish
StartupNotify=true
Categories=Tools;" > "$HOME/.local/share/applications/Fish-Shell.desktop"


echo "To run: Menu -> Tools -> Fish Shell"
exit