#!/bin/bash

version=2.17.2

install_packages openjdk-11-jre https://www.worldpainter.net/files/worldpainter_${version}.deb || exit 1

# force java-11
case "$arch" in
  "64")
    echo /usr/lib/jvm/java-11-openjdk-arm64 | sudo tee /opt/worldpainter/.install4j/pref_jre.cfg >/dev/null
    ;;
  "32")
    echo /usr/lib/jvm/java-11-openjdk-armhf | sudo tee /opt/worldpainter/.install4j/pref_jre.cfg >/dev/null
    ;;
  *) error "Failed to detect OS CPU architecture! Something is very wrong." ;;
esac
