#!/bin/bash

version=2.13.1

install_packages openjdk-11-jre https://www.worldpainter.net/files/worldpainter_${version}.deb || exit 1

# remove worldpainter duplicate .desktop file due to bad deb
sudo xdg-desktop-menu uninstall --mode system "/opt/worldpainter/.install4j/install4j_1tsntyi-worldpainter.desktop"

case "$arch" in
"64") 
# force java-11
sudo tee /opt/worldpainter/.install4j/pref_jre.cfg <<EOF
/usr/lib/jvm/java-11-openjdk-arm64
EOF
;;
"32") 
# force java-11
sudo tee /opt/worldpainter/.install4j/pref_jre.cfg <<EOF
/usr/lib/jvm/java-11-openjdk-armhf
EOF
;;
*) error "Failed to detect OS CPU architecture! Something is very wrong." ;;
esac

