#!/bin/bash
purge_packages || exit 1

sudo rm -f ~/.config/autostart/conky.desktop ~/.conky-rings.lua ~/.conkyrc || error "Failed to remove autostart file or .conkyrc or .conky-rings.lua!"

killall conky 2>/dev/null

exit 0
