#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

"${DIRECTORY}/purge-installed" "$(dirname "$0")" || exit 1

sudo rm -f ~/.config/autostart/conky.desktop ~/.conky-rings.lua ~/.conkyrc || error "Failed to remove autostart file or .conkyrc or .conky-rings.lua!"

killall conky 2>/dev/null

exit 0
