#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

#use the error function often!
#If a certain command is necessary for installation to continue, then add this to the end of it:
# || error 'reason'
#example below:

#Download java and launcher
mkdir ~/Minecraft && cd ~/Minecraft && wget https://github.com/mikehooper/Minecraft/raw/main/setupMC.sh && chmod +x setupMC.sh && ./setupMC.sh || error 'Failed to install the launcher!'

#Move launcher to /usr/share/
sudo mkdir /usr/share/minecraftjava && sudo mv launcher.jar /usr/share/minecraftjava/launcher.jar

#Create desktop shortcut
cd ~/.local/share/applications/
echo "[Desktop Entry]
Version=1.0
Type=Application
Name=Minecraft Launcher
Comment=3D block based sandbox game
Icon=$(dirname "$0")/icon-64.png
Exec=env MESA_GL_VERSION_OVERRIDE=3.3 java -jar /usr/share/minecraftjava/launcher.jar
Categories=Game;" > minecraft.desktop
chmod +x minecraft.desktop
cd

mkdir -p ~/.minecraft
echo '{
  "profiles": {
    "(Default)": {
      "name": "(Default)",
      "javaArgs": "-Dorg.lwjgl.librarypath='$HOME'/lwjgl3arm32 -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M"
    }
  },
  "selectedProfile": "(Default)",
  "clientToken": "c4a6f915-4d47-47bf-a8f4-746090e7e576",
  "authenticationDatabase": {},
  "launcherVersion": {
    "name": "1.6.93",
    "format": 21,
    "profilesFormat": 1
  }
}' > $HOME/.minecraft/launcher_profiles.json

sudo rm -rf ~/Minecraft

echo 'Installation is now done! You can open the launcher by going to Menu > Games > Minecraft Launcher'
echo -e "\e[21m\e[5mWARNING:\e[0m\e[97mYou can only play Minecraft versions \e[1m1.13\e[0m and higher with your current configuration! To use lower versions, please follow the instructions at \e[96mhttps://www.noxxtech.tk/minecraft-install#h.fpnon3xvmuoz\e[39m to play versions \e[1m1.12\e[0m and under!"
read -p "Press [Enter] to continue after you've read the above message"
