#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

#install modprobe if not already installed
if ! command -v modprobe >/dev/null;then
  
  if [ -f /usr/bin/apt ];then
    sudo apt update
    sudo apt install -y kmod || echo "Failed to install modprobe."
  else
    error "Failed to find any package manager to install modprobe."
  fi
fi

#install unzip if not already installed
if ! command -v unzip >/dev/null;then
  
  if [ -f /usr/bin/apt ];then
    sudo apt update
    sudo apt install -y unzip || echo "Failed to install unzip."
  else
    error "Failed to find any package manager to install unzip."
  fi
fi

#install svn if not already installed
if ! sudo command -v svn >/dev/null;then
  
  if [ -f /usr/bin/apt ];then
    sudo apt update
    sudo apt install -y subversion || echo "Failed to install subversion."
  else
    error "Failed to find any package manager to install subversion."
  fi
fi

#Run modprobe fuse
sudo modprobe fuse

cd ~

#Download client and assorted java stuff
wget https://github.com/gl91306/lunar/raw/master/lunarclient-2.7.3c-armv7l.AppImage
mkdir -p ~/.minecraft
mkdir -p ~/lunarassets
mv lunarclient-*-armv7l.AppImage ~/lunarassets

if [ ! -d ~/lwjgl3arm64 ]; then
    mkdir ~/lwjgl3arm64
fi
if [ ! -f jdk-16.0.1+9-jre64.tar.gz ]; then
    wget https://github.com/gl91306/lunar/raw/master/jdk-16.0.1%2B9-jre64.gz
fi
if [ ! -f lwjgl3arm64.tar.gz ]; then
    wget https://github.com/mikehooper/Minecraft/raw/main/lwjgl3arm64.tar.gz
fi
if [ ! -d /opt/jdk ]; then
    sudo mkdir /opt/jdk
fi

sudo tar -zxf jdk-16.0.1+9-jre64.tar.gz -C /opt/jdk
tar -zxf lwjgl3arm64.tar.gz -C ~/lwjgl3arm64
sudo update-alternatives --install /usr/bin/java java /opt/jdk/jdk-16.0.1+9-jre64/bin/java 0
sudo update-alternatives --set java /opt/jdk/jdk-16.0.1+9-jre64/bin/java
cd
cd lwjgl3arm64
wget https://github.com/gl91306/lunar/raw/master/libwebp-imageio64.so
cd
wget https://github.com/gl91306/lunar/raw/master/javafx-sdk-17-64.zip
unzip javafx-sdk-17-64.zip -d $HOME/lunarassets
cd

#Change perms of Launcher
sudo chmod +x $HOME/.minecraft/lunarclient-*-aarch64.AppImage

#Then make menu shortcut
echo "[Desktop Entry]
Version=1.0
Type=Application
Name=Minecraft Launcher (64-bit)
Comment=3D block based sandbox game
Icon=$(dirname "$0")/icon-64.png
Exec=env MESA_GL_VERSION_OVERRIDE=3.3 $HOME/.minecraft/lunarclient-2.7.3c-armv7l.AppImage 
Categories=Game;" > ~/.local/share/applications/minecraftjava.desktop
chmod +x ~/.local/share/applications/minecraftjava.desktop
cp ~/.local/share/applications/minecraftjava.desktop ~/Desktop/

echo 'Installation is now done! You can open the launcher by going to Menu > Games > Minecraft Launcher or with the new shortcut on your desktop!'
echo 'Launching Lunar Client...'

#Run launcher and cleanup
$HOME/lunarclient-2.7.3c-aarch64.AppImage
cd
rm -rf jdk-16.0.1+9-jre64.tar.gz
rm -rf javafx-sdk-17-64.zip
rm -rf lwjgl3arm64.tar.gz
cd