#!/bin/bash
install_packages kmod zip unzip libfuse2 lsb-release wget gpg || exit 1

echo
echo "Creating directories"
mkdir -p ~/.minecraft ~/lwjgl3arm32 ~/lwjgl2arm32 ~/lunarassets

#Download client and assorted java stuff
echo "Downloading lunarclient.AppImage"
errors="$(wget -O ~/lunarassets/lunarclient.AppImage 'https://github.com/gl91306/lunar/raw/master/lunarclient-2.8.0-armv7l.AppImage' 2>&1)" || error "Failed to download lunarclient.AppImage\nErrors:\n$errors"
errors="$(chmod +x ~/lunarassets/lunarclient.AppImage 2>&1)" || error "Failed to make lunarclient.AppImage executable!\nErrors:\n$errors"

echo "Downloading lunarclient.png"
errors="$(wget -O ~/lunarassets/lunarclient.png https://github.com/gl91306/lunar/raw/master/lunarclient.png 2>&1)" || error "Failed to download lunarclient.png\nErrors:\n$errors"

# adding temurin JDK from apt repo
status "Adding Adoptium repository:"

echo "- public key -> keyring"
rm -f /tmp/adoptium-public-key /tmp/adoptium-archive-keyring.gpg
wget -O /tmp/adoptium-public-key https://adoptium.jfrog.io/artifactory/api/security/keypair/default-gpg-key/public
gpg --no-default-keyring --keyring /tmp/adoptium-keyring.gpg --import /tmp/adoptium-public-key
rm -f /tmp/adoptium-public-key

echo " - keyring -> GPG key"
gpg --no-default-keyring --keyring /tmp/adoptium-keyring.gpg --export --output /tmp/adoptium-archive-keyring.gpg
rm -f /tmp/adoptium-keyring.gpg

echo " - Moving GPG key to /usr/share/keyrings"
sudo mv -f /tmp/adoptium-archive-keyring.gpg /usr/share/keyrings

echo " - Creating /etc/apt/sources.list.d/adoptium.list"
echo "deb [signed-by=/usr/share/keyrings/adoptium-archive-keyring.gpg] https://adoptium.jfrog.io/artifactory/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/adoptium.list >/dev/null

echo " - Installing temurin-17-jdk"
#try to install temurin-17-jdk; if it fails, remove repository to avoid breaking user's system
(install_packages temurin-17-jdk)
if [ $? != 0 ]; then
  anything_installed_from_repo "https://adoptium.jfrog.io/artifactory/deb"
  if [ $? != 0 ]; then
    # nothing installed from repo, this check is to prevent removing repos which other pi-apps scripts or the user have used successfully
    # safe to remove
    sudo rm -f /etc/apt/sources.list.d/adoptium.list /usr/share/keyrings/adoptium-archive-keyring.gpg
    error "Failed to install temurin packages. Adoptium repository has been removed."
  else
    error "Failed to install temurin packages."
  fi
fi

# this is a hack because Lunar client is coded in such a way as to hardcode this path
# please remove this hack if Lunar client gets an update to fix this functionality and read the JAVA_HOME variable
sudo mkdir -p  /opt/jdk/jdk-17.0.1+12/bin
sudo ln -s /usr/lib/jvm/temurin-17-jdk-armhf/bin/java  /opt/jdk/jdk-17.0.1+12/bin/java

echo "Setting up lwjgl3arm32 folder"
echo "- Downloading lwjgl3arm32.tar.gz"
errors="$(wget -O ~/lwjgl3arm32.tar.gz 'https://github.com/mikehooper/Minecraft/raw/main/lwjgl3arm32.tar.gz' 2>&1)" || error "Failed to download lwjgl3arm32.tar.gz\nErrors:\n$errors"
echo "- Extracting lwjgl3arm32.tar.gz"
tar -zxf ~/lwjgl3arm32.tar.gz -C ~/lwjgl3arm32 || error "Failed to extract lwjgl3arm32.tar.gz"
rm -f ~/lwjgl3arm32.tar.gz
echo "- libwebp-imageio32.so"
errors="$(wget -O ~/lwjgl3arm32/libwebp-imageio32.so 'https://github.com/gl91306/lunar/raw/master/libwebp-imageio32.so' 2>&1)" || error "Failed to download libwebp-imageio32.so\nErrors:\n$errors"
echo "- libgstreamer-lite.so"
errors="$(wget -O ~/lwjgl3arm32/libgstreamer-lite.so 'https://github.com/gl91306/lunar/raw/master/libgstreamer-lite.so' 2>&1)" || error "Failed to download libgstreamer-lite.so\nErrors:\n$errors"
echo "- libjfxmedia.so"
errors="$(wget -O ~/lwjgl3arm32/libjfxmedia.so 'https://github.com/gl91306/lunar/raw/master/libjfxmedia.so' 2>&1)" || error "Failed to download libjfxmedia.so\nErrors:\n$errors"

echo "Setting up lwjgl2arm32 folder"
echo "- Downloading lwjgl2arm32.tar.gz"
errors="$(wget -O ~/lwjgl2arm32.tar.gz 'https://github.com/mikehooper/Minecraft/raw/main/lwjgl2arm32.tar.gz' 2>&1)" || error "Failed to download lwjgl2arm32.tar.gz\nErrors:\n$errors"
echo "- Extracting lwjgl2arm32.tar.gz"
tar -zxf ~/lwjgl2arm32.tar.gz -C ~/lwjgl2arm32 || error "Failed to extract lwjgl2arm32.tar.gz"
rm -f ~/lwjgl2arm32.tar.gz
echo "- libwebp-imageio32.so"
cp ~/lwjgl3arm32/libwebp-imageio32.so ~/lwjgl2arm32
echo "- libgstreamer-lite.so"
cp ~/lwjgl3arm32/libgstreamer-lite.so ~/lwjgl2arm32
echo "- libjfxmedia.so"
cp ~/lwjgl3arm32/libjfxmedia.so ~/lwjgl2arm32
echo "- libopenal.so"
rm -f ~/lwjgl2arm32/libopenal.so
cp ~/lwjgl3arm32/libopenal.so ~/lwjgl2arm32

echo "Downloading javafx-sdk-17.zip"
errors="$(wget -O ~/javafx-sdk-17.zip 'https://github.com/gl91306/lunar/raw/master/javafx-sdk-17.zip' 2>&1)" || error "Failed to download javafx-sdk-17.zip\nErrors:\n$errors"
echo "Extracting javafx-sdk-17.zip"
unzip -oq ~/javafx-sdk-17.zip -d ~/lunarassets || error "Failed to extract javafx-sdk-17.zip"
rm -f ~/javafx-sdk-17.zip

echo "- libjfxwebkit.so"
errors="$(wget -O ~/lunarassets/javafx-sdk-17/lib/libjfxwebkit.so 'https://github.com/gl91306/lunar/raw/master/libjfxwebkit.so' 2>&1)" || error "Failed to download libjfxwebkit.so\nErrors:\n$errors"

#Then make menu shortcut
echo "[Desktop Entry]
Version=1.0
Type=Application
Name=Minecraft Launcher (Lunar)
Comment=3D block based sandbox game
Icon=$(dirname "$0")/icon-64.png
Exec=bash -c "\""sudo modprobe fuse ; JAVA_HOME=/usr/lib/jvm/java-17-temurin-armhf PATH=/usr/lib/jvm/java-17-temurin-armhf/bin/:$PATH MESA_GL_VERSION_OVERRIDE=3.3 $HOME/lunarassets/lunarclient.AppImage --no-sandbox"\""
StartupNotify=true
Categories=Game;" > ~/.local/share/applications/minecraftjava.desktop

echo "This fork of Lunar Client is made by the devs at Pi-Ware, an alternative to Pi-Apps with a focus on games and multi-os support (Arch and Manjaro).
You can find more about Pi-Ware at https://github.com/piware14/pi-ware
You should also contact them for support if a issue arises with the launcher. You can also try the 'Minecraft Java MultiMC5' app in the games section instead.

To run: Menu -> Games -> Minecraft Launcher (Lunar)"
