#!/bin/bash
install_packages kmod zip unzip libfuse2 || exit 1

echo "Creating directories"
mkdir -p ~/.minecraft ~/lwjgl3arm64 ~/lwjgl2arm64 ~/lunarassets
sudo mkdir -p /opt/jdk

#Download client and assorted java stuff
echo "Downloading lunarclient.AppImage"
errors="$(wget -O ~/lunarassets/lunarclient.AppImage 'https://github.com/gl91306/lunar/raw/master/lunarclient-2.8.0-arm64.AppImage' 2>&1)" || error "Failed to download lunarclient.AppImage\nErrors:\n$errors"
errors="$(chmod +x ~/lunarassets/lunarclient.AppImage 2>&1)" || error "Failed to make lunarclient.AppImage executable!\nErrors:\n$errors"

echo "Downloading lunarclient.png"
errors="$(wget -O ~/lunarassets/lunarclient.png https://github.com/gl91306/lunar/raw/master/lunarclient.png 2>&1)" || error "Failed to download lunarclient.png\nErrors:\n$errors"

echo "Downloading jdk-17.tar.gz"
sudo rm -rf /opt/jdk/jdk-17.0.1+12 ~/jdk-17.tar.gz
errors="$(wget -O ~/jdk-17.tar.gz 'https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.1%2B12/OpenJDK17U-jdk_aarch64_linux_hotspot_17.0.1_12.tar.gz' 2>&1)" || error "Failed to download jdk-17.tar.gz\nErrors:\n$errors"

echo "Extracting jdk-17.tar.gz to /opt/jdk"
sudo tar -zxf ~/jdk-17.tar.gz -C /opt/jdk || error "Failed to extract jdk-17.tar.gz"
rm -f ~/jdk-17.tar.gz

echo "Setting up lwjgl3arm64 folder"
echo "- Downloading lwjgl3arm64.tar.gz"
errors="$(wget -O ~/lwjgl3arm64.tar.gz 'https://github.com/mikehooper/Minecraft/raw/main/lwjgl3arm64.tar.gz' 2>&1)" || error "Failed to download lwjgl3arm64.tar.gz\nErrors:\n$errors"
echo "- Extracting lwjgl3arm64.tar.gz"
tar -zxf ~/lwjgl3arm64.tar.gz -C ~/lwjgl3arm64 || error "Failed to extract lwjgl3arm64.tar.gz"
rm -f ~/lwjgl3arm64.tar.gz

echo "Setting up lwjgl2arm64 folder"
echo "- Downloading lwjgl2arm64.tar"
errors="$(wget -O ~/lwjgl2arm64.tar 'https://github.com/gl91306/lunar/raw/master/lwjgl2arm64.tar' 2>&1)" || error "Failed to download lwjgl2arm32.tar.gz\nErrors:\n$errors"
echo "- Extracting lwjgl2arm64.tar"
tar -xf ~/lwjgl2arm64.tar || error "Failed to extract lwjgl2arm64.tar"

echo "Downloading javafx-sdk-17-64.zip"
errors="$(wget -O ~/javafx-sdk-17-64.zip 'https://github.com/gl91306/lunar/raw/master/javafx-sdk-17-64.zip' 2>&1)" || error "Failed to download javafx-sdk-17-64.zip\nErrors:\n$errors"
echo "Extracting javafx-sdk-17-64.zip"
unzip -oq ~/javafx-sdk-17-64.zip -d ~/lunarassets || error "Failed to extract javafx-sdk-17-64.zip"
rm -f ~/javafx-sdk-17-64.zip

echo "Downloading other dependencies"
errors="$(wget -O ~/lwjgl3arm64/libwebp-imageio64.so https://github.com/gl91306/lunar/raw/master/libwebp-imageio64.so 2>&1)" || error "Failed to download libwebp-imageio64.so\nErrors:\n$errors"
cp ~/lwjgl3arm64/libwebp-imageio64.so ~/lwjgl2arm64/libwebp-imageio64.so || error "Failed to copy libwebp-imageio64.so"

enable_module fuse || exit 1

#Then make menu shortcut
echo "[Desktop Entry]
Version=1.0
Type=Application
Name=Minecraft Launcher (Lunar)
Comment=3D block based sandbox game
Icon=$(dirname "$0")/icon-64.png
Exec=bash -c "\""JAVA_HOME=/opt/jdk/jdk-17.0.1+12 PATH=/opt/jdk/jdk-17.0.1+12/bin/:$PATH MESA_GL_VERSION_OVERRIDE=3.3 $HOME/lunarassets/lunarclient.AppImage --no-sandbox"\""
StartupNotify=true
Categories=Game;" > ~/.local/share/applications/minecraftjava.desktop

echo "This fork of Lunar Client is made by the devs at Pi-Ware, an alternative to Pi-Apps with a focus on games and multi-os support (Arch and Manjaro).
You can find more about Pi-Ware at https://github.com/piware14/pi-ware
You should also contact them for support if a issue arises with the launcher. You can also try the 'Minecraft Java MultiMC5' app in the games section instead.

To run: Menu -> Games -> Minecraft Launcher (Lunar)"
