#!/bin/bash

# cleanup any remaing old lunar stuff
echo "Removing old Lunar assets"
sudo rm -rf ~/lwjgl2arm32 ~/lwjgl3arm32 ~/lwjgl3arm64 ~/lwjgl2arm64 /opt/jdk/jdk-17.0.1+12 ~/lunarassets ~/.lunarclient ~/.local/share/applications/minecraftjava.desktop

echo "Removing Lunar Appimage"
rm -rf ~/.local/share/applications/Lunar-Client.desktop ~/.local/bin/lunarclient.AppImage

purge_packages || exit 1
