#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

rm -f ~/.local/share/applications/minecraftjava.desktop
rm -f ~/Desktop/minecraftjava.desktop
rm -rf ~/.lunarclient
rm -rf ~/lunarassets

sudo rm -rf ~/lwjgl2arm32
sudo rm -rf ~/lwjgl3arm32
sudo rm -rf ~/lwjgl3arm64
sudo rm -rf ~/lwjgl2arm64

rm -f ~/.minecraft lunarclient-*.AppImage
