#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$(dirname "$0")")")"
function error {
  echo -e "\\e[31m$1\\e[39m"
  exit 1
}

# Get dependencies
sudo dpkg --add-architecture armhf
"${DIRECTORY}/pkg-install" "curl libx11-6:armhf libxext6:armhf libegl1-mesa:armhf zlib1g:armhf libstdc++6:armhf libgl1-mesa-dri:armhf libasound2:armhf libpulse0:armhf libcom-err2:armhf libgmp10:armhf libp11-kit0:armhf" "$(dirname "$0")" || exit 1

#Download file
cd ~
curl -L https://github.com/ChristopherHX/linux-packaging-scripts/releases/download/ng.appimage/Minecraft_Bedrock_Launcher-arm_aarch64.0.0.619.AppImage --output MCBedrock.AppImage
chmod +x MCBedrock.AppImage
sudo mv MCBedrock.AppImage /usr/bin/MCBedrock.AppImage

#Make Desktop file
echo '[Desktop Entry]
Version=1.1
Type=Application
Name=Minecraft Bedrock Launcher
Comment=A Minecraft: Bedrock Edition
Icon=$(dirname "$0")/icon-64.png
Exec=bash -c "GALLIUM_HUD=simple,fps /usr/bin/MCBedrock.AppImage"
Categories=Game;
Terminal=false
StartupNotify=true' > ~/.local/share/applications/minecraftbedrock.desktop

