#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$(dirname "$0")")")"
function error {
  echo -e "\\e[31m$1\\e[39m"
  exit 1
}

# Get dependencies
"${DIRECTORY}/pkg-install" "flatpak" "$(dirname "$0")" || exit 1

#Add flathub as a source
sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

#Install through flatpak
flatpak install -y flathub io.mrarm.mcpelauncher || error 'Failed to install launcher!'

read -p 'You must reboot for the new Minecraft Bedrock menu launcher to appear. Press Enter to close.'
