#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$(dirname "$0")")")"
function error {
  echo -e "\\e[31m$1\\e[39m"
  exit 1
}

# Get dependencies
"${DIRECTORY}/pkg-install" "curl libx11-6 libxext6 libegl1-mesa zlib1g libstdc++6 libgl1-mesa-dri libasound2 libcom-err2 libgmp10 libp11-kit0" "$(dirname "$0")" || exit 1

#Download file
cd ~
curl -L https://github.com/ChristopherHX/linux-packaging-scripts/releases/download/appimage/Minecraft_Bedrock_Launcher-armhf.0.0.540.AppImage --output MCBedrock.AppImage
chmod +x MCBedrock.AppImage
sudo mv MCBedrock.AppImage /usr/bin/MCBedrock.AppImage

#Make Desktop file
echo '[Desktop Entry]
Version=1.1
Type=Application
Name=Minecraft Bedrock Launcher
Comment=A Minecraft: Bedrock Edition
Icon=/home/pi/pi-apps/apps/Minecraft Bedrock/icon-64.png
Exec=/usr/bin/MCBedrock.AppImage GALLIUM_HUD=simple,fps
Categories=Game;
Terminal=false
StartupNotify=true' > /home/pi/.local/share/applications/minecraftbedrock.desktop

