#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$(dirname "$0")")")"
function error {
  echo -e "\\e[31m$1\\e[39m"
  exit 1
}

sudo rm /opt/MCBedrock.AppImage
rm -rf ~/'.cache/Minecraft Linux Launcher' && rm -rf ~/.cache/mcpelauncher && rm -rf ~/.cache/mcpelauncher-webview && rm -rf ~/.cache/msa && rm -rf ~/.cache/msa-ui-qt && rm -rf ~/.local/share/msa
