#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$(dirname "$0")")")"
function error {
  echo -e "\\e[31m$1\\e[39m"
  exit 1
}

#Remove app
sudo rm /usr/bin/MCBedrock.AppImage

#Remove install folder
sudo rm -r /home/pi/.local/share/mcpelauncher/
