#!/bin/bash

#Allow packages required by this app to be uninstalled
purge_packages || exit 1

sudo rm -f /opt/MCBedrock.AppImage
rm -rf ~/.local/bin/MCBedrock.AppImage ~/'.cache/Minecraft Linux Launcher' ~/.cache/mcpelauncher ~/.cache/mcpelauncher-webview ~/.cache/msa ~/.cache/msa-ui-qt ~/.local/share/msa ~/.local/share/applications/minecraftbedrock.desktop
