#!/bin/bash
purge_packages || error "Dependencies failed to uninstall"

"${DIRECTORY}/manage" uninstall Scrcpy
status -n "Removing other files... "
sudo rm -rf /opt/droidbuddy /usr/share/applications/androidbuddy.desktop #gazlene app install locations

sudo rm -rf /usr/bin/gnirehtet /opt/gnirehtet
rm -rf ~/.local/share/androidbuddy ~/.local/share/applications/androidbuddy.desktop ~/.local/share/icons/androidbuddy.png
status_green Done
