#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

# Get dependencies
"${DIRECTORY}/pkg-install" "python3-pip" "$(dirname "$0")" || exit 1

#Installing dependencies for search argument
pip3 install python-Levenshtein fuzzywuzzy || error "pip3 failed to python-Levenshtein and fuzzywuzzy"

#Downloading papm file
wget https://raw.githubusercontent.com/techcoder20/PiAppsTerminalAdvanced/main/PiAppsTerminalAdvanced.py -O "${DIRECTORY}/PiAppsTerminalAdvanced.py" || error "Failed to download PiAppsTerminalAdvanced.py"

echo "#!/bin/bash
#${DIRECTORY}/gui
python3 ${DIRECTORY}/PiAppsTerminalAdvanced.py"' "$@"' | sudo tee /usr/local/bin/pi-apps >/dev/null
sudo chmod +x /usr/local/bin/pi-apps
