#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

#Removing PiAppsTerminalAdvanced.py
rm "${DIRECTORY}/PiAppsTerminalAdvanced.py"

#Restoring old binary file
echo "#!/bin/bash
${DIRECTORY}/gui" | sudo tee /usr/local/bin/pi-apps >/dev/null

sudo chmod +x /usr/local/bin/pi-apps
