#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

cd ~/Downloads || error "Failed to change directory to $HOME/Downloads!"
git clone https://gitlab.com/bztsrc/usbimager.git
cd usbimager/src/
make deb
cd ..
sudo dpkg -i usbimager_1.0.5-arm64.deb
cd ..
rm -rf usbimager
