#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}


cd Downloads || error 'Failed to change directory!'
wget https://gitlab.com/bztsrc/usbimager/-/blob/binaries/usbimager_1.0.7-armhf.deb || error 'Failed to Download usbimager_1.0.5-armhf.deb!'
sudo dpkg -i usbimager_1.0.7-armhf.deb || error 'Failed to install usbimager_1.0.7-armhf.deb!'
rm -f usbimager_1.0.7-armhf.deb
