#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

rm -rf ~/usbimager

files="/usr/bin/usbimager
/usr/share/man/man8/usbimager.8.gz
/usr/share/icons/hicolor/64x64/apps/usbimager.png
/usr/share/icons/hicolor/128x128/apps/usbimager.png
/usr/share/icons/hicolor/32x32/apps/usbimager.png
/usr/share/icons/hicolor/16x16/apps/usbimager.png
/usr/share/applications/usbimager.desktop"

echo "$files" | sudo xargs rm -f
