#!/bin/bash
if dpkg -l box86 &>/dev/null ;then
  sudo apt purge -y box86
fi

sudo rm -f /etc/apt/sources.list.d/box86.list
echo "Adding box86 repo..."
echo "deb [signed-by=/usr/share/keyrings/box86-archive-keyring.gpg] https://itai-nelken.github.io/weekly-box86-debs/debian/ /" | sudo tee /etc/apt/sources.list.d/box86.list >/dev/null || error "Failed to download /etc/apt/sources.list.d/box86.list"
echo "Adding key..."
curl -fsSL https://itai-nelken.github.io/weekly-box86-debs/debian/KEY.gpg | sudo gpg --dearmor -o /usr/share/keyrings/box86-archive-keyring.gpg || error "Failed to add key to box86 repo!"
echo "Installing box86..."
sudo dpkg --remove box86-no-binfmt-restart 2>/dev/null
install_packages box86 || exit 1

if ! sudo systemctl restart systemd-binfmt ;then
  echo -e "\nWarning: systemd-binfmt failed to restart. Getting debug info..."
  echo "Running command: 'systemctl status systemd-binfmt.service'"
  systemctl status systemd-binfmt.service
  echo "Still exiting with success, but you will have to manually run all x86 applications with box86 as binfmt isn't there to do it for you."
fi
