#!/bin/bash

version=7.12.0

install_packages "https://github.com/dennisameling/Signal-Desktop/releases/download/v${version}/signal-desktop-unofficial_${version}_arm64.deb" || exit 1

#patch menu launcher to not say 'Signal Unofficial'
sudo sed -i 's/^Name=Signal Unofficial$/Name=Signal/g' /usr/share/applications/signal-desktop-unofficial.desktop
