#!/bin/bash

#PACKAGES FOUND IN: https://launchpad.net/~cartes/+archive/ubuntu/ppa/+packages

version=1.0.0-0ubuntu2~focal

install_packages https://launchpad.net/~cartes/+archive/ubuntu/drawing/+files/drawing_${version}_armhf.deb || exit 1

