#!/bin/bash
#PACKAGES FOUND IN: https://launchpad.net/~cartes/+archive/ubuntu/ppa/+packages

install_packages https://launchpad.net/~cartes/+archive/ubuntu/drawing/+files/drawing_0.8.4-0ubuntu1~focal_arm64.deb || exit 1

