#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

if command -v drawing >/dev/null ;then
  sudo apt purge -y drawing || error "apt failed to uninstall the 'drawing' package."
fi
