#!/bin/bash

install_packages https://download.bleachbit.org/bleachbit_4.4.2-0_all_debian11.deb || exit 1

# Move BleachBit to Accessories category
sudo sed -i s/"Categories=System;FileTools;GTK;"/"Categories=Utility"/g /usr/share/applications/bleachbit-root.desktop  || error "Failed to move BleachBit to Accessories category."
