#!/bin/bash

version=4.4.2-0

install_packages https://download.bleachbit.org/bleachbit_${version}_all_debian11.deb || exit 1

# Move BleachBit to Accessories category
sudo sed -i s/"Categories=System;FileTools;GTK;"/"Categories=Utility"/g /usr/share/applications/org.bleachbit.BleachBit.desktop /usr/share/applications/org.bleachbit.BleachBit-root.desktop || :
