#!/bin/bash

install_packages https://download.bleachbit.org/bleachbit_4.4.2-0_all_debian11.deb || exit 1

# Remove extra 'BleachBit as Administrator' menu shortcut
sudo rm -f /usr/share/applications/org.bleachbit.BleachBit.desktop || error "Failed to remove extra menu shortcut."
# Move BleachBit to Accessories category
sudo sed -i s/"Categories=System;FileTools;GTK;"/"Categories=Utility"/g /usr/share/applications/org.bleachbit.BleachBit-root.desktop || error "Failed to move BleachBit to Accessories category."
sudo sed -i s/"BleachBit as Administrator"/"BleachBit"/g /usr/share/applications/org.bleachbit.BleachBit-root.desktop || error "Failed to move rename menu shortcut."
