#!/bin/bash


function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

fiddle_ver="electron-fiddle_0.27.0_arm64.deb"
install_packages https://github.com/electron/fiddle/releases/download/v0.27.2/electron-fiddle_0.27.2_arm64.deb || exit 1
