#!/bin/bash


function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}
fiddle_ver="electron-fiddle_0.27.0_armhf.deb"
install_packages https://github.com/electron/fiddle/releases/download/v0.27.0/electron-fiddle_0.27.0_armhf.deb
rm -rf ${fiddle_ver} || sudo rm -rf ${fiddle_ver}
