#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$(dirname "$0")")")"
function error {
  echo -e "\e[31m$1\e[39m"
  exit 1
}

#use the error function often!
#If a certain command is necessary for installation to continue, then add this to the end of it:
# || error 'reason'
#example below:

#Download java and launcher
rm -rf ~/Minecraft

mkdir ~/Minecraft || error "Failed to create the directory!"
cd ~/Minecraft || error "Failed to enter the directory!"
wget https://www.dropbox.com/s/2602i5d0h4kteex/setupMC.sh  || error 'Failed to download launcher!'
chmod +x setupMC.sh || error "failed to mark as executable!"
./setupMC.sh

#Move launcher to /usr/share/
sudo mkdir /usr/share/minecraftjava && sudo mv launcher.jar /usr/share/minecraftjava/launcher.jar 

#Create desktop shortcut
cd ~/.local/share/applications/
wget https://raw.githubusercontent.com/mobilegmYT/pi-apps-resources/main/Minecraft/minecraft.desktop
cd

sudo chmod +x ~/.local/share/applications/minecraft.desktop

mkdir -p ~/.minecraft
echo '{
  "profiles": {
    "(Default)": {
      "name": "(Default)",
      "javaArgs": "-Dorg.lwjgl.librarypath=/home/pi/lwjgl3arm32 -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M"
    }
  },
  "selectedProfile": "(Default)",
  "clientToken": "c4a6f915-4d47-47bf-a8f4-746090e7e576",
  "authenticationDatabase": {},
  "launcherVersion": {
    "name": "1.6.93",
    "format": 21,
    "profilesFormat": 1
  }
}' > /home/pi/.minecraft/launcher_profiles.json

java -jar /usr/share/minecraftjava/launcher.jar
