#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$(dirname "$0")")")"
function error {
  echo -e "\e[31m$1\e[39m"
  exit 1
}

sudo rm -f ~/.local/share/applications/minecraft.desktop
sudo rm -rf ~/.minecraft
sudo rm -rf ~/Minecraft
sudo rm -rf ~/lwjgl2arm32
sudo rm -rf ~/lwjgl3arm32
sudo rm -rf ~/lwjgl3arm64
sudo rm -rf ~/lwjgl2arm64
sudo rm -rf /usr/share/minecraftjava/
