#!/bin/bash
rm -rf ~/libreoffice-ms-theme
git_clone --depth=1 https://github.com/Botspot/libreoffice-ms-theme || error "Failed to git_clone libreoffice-ms-theme repository!"
~/libreoffice-ms-theme/revert.sh || error "revert.sh failed"
rm -rf ~/libreoffice-ms-theme
echo "Your original settings are now restored. Libreoffice should now behave how it was originally."
