#!/bin/bash

killall legcord &>/dev/null && echo "Closing legcord before uninstalling..."
killall Legcord &>/dev/null && echo "Closing Legcord before uninstalling..."

sudo rm -f /opt/Legcord/legcord-wayland.sh

purge_packages || exit 1
