#!/bin/bash
version=1.6.1
wget -O /tmp/tldr https://github.com/dbrgn/tealdeer/releases/download/v${version}/tealdeer-linux-armv7-musleabihf || error "Failed to download tldr!"
sudo mv /tmp/tldr /usr/bin/ || error "Failed to move binary to /usr/bin/"
sudo chmod +x /usr/bin/tldr
tldr --update
