#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

cd ~/Downloads

wget https://cdn.discordapp.com/attachments/741857430195142668/774969741981777930/tldr
sudo mv tldr /usr/bin/
sudo chmod +x /usr/bin/tldr
tldr --update
