#!/bin/bash
version=1.7.0
wget -O /tmp/tldr https://github.com/tealdeer-rs/tealdeer/releases/download/v${version}/tealdeer-linux-arm-musleabihf || error "Failed to download tldr!"
sudo mv /tmp/tldr /usr/bin/ || error "Failed to move binary to /usr/bin/"
sudo chmod +x /usr/bin/tldr
tldr --update
