#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

tldr --clear-cache &>/dev/null
rm -f /usr/bin/tldr || sudo rm -f /usr/bin/tldr &>/dev/null
