#!/bin/bash

#determine where the Chromium customizations folder is.
if [ -d /etc/chromium.d ];then
  folder=/etc/chromium.d
elif [ -d /etc/chromium-browser/customizations ];then
  folder=/etc/chromium-browser/customizations
else
  error "User error: Cannot find the directory where Chromium keeps its flags! Usually this would be /etc/chromium.d or /etc/chromium-browser/customizations. On your system, neither of these directories exist. Please reach out to Botspot for this to be fixed."
fi

status "Reverting all changes..."
echo "Removing these files:
  - ${folder}/dark_mode
  - ${folder}/site_dark_mode
  - ${folder}/ui_scale
  - ${folder}/apikeys
  - ${folder}/performance_improvements
  - ${folder}/reduce_writes"
sudo rm -f "${folder}/dark_mode" \
  "${folder}/site_dark_mode" \
  "${folder}/ui_scale" \
  "${folder}/apikeys" \
  "${folder}/performance_improvements" \
  "${folder}/reduce_writes"

#clean up old symlinks from reduce_writes script - to avoid errors
if [ -L "$HOME/.config/chromium/Default/Service Worker" ];then
  rm -rf "$HOME/.config/chromium/Default/Service Worker"
fi
if [ -L "$HOME/.cache/chromium" ];then
  rm -rf "$HOME/.cache/chromium"
fi

if pgrep chromium >/dev/null || pgrep chromium-browser >/dev/null ;then
  status "Changes will take effect after you relaunch Chromium."
fi
