name: Test_Build

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  # Now supports a max of 25 inputs up from 10
  #   https://github.blog/changelog/2025-12-04-actions-workflow-dispatch-workflows-now-support-25-inputs/
  workflow_dispatch:
    inputs:
      name:
        description: 'App Name, PR #, or zip URL'
        required: true
        default: ''
      bullseye_64:
        description: 'Build on PiOS Bullseye 64bit'
        required: true
        type: boolean
      bullseye_32:
        description: 'Build on PiOS Bullseye 32bit'
        required: true
        type: boolean
      bookworm_64:
        description: 'Build on PiOS Bookworm 64bit'
        required: true
        type: boolean
      bookworm_32:
        description: 'Build on PiOS Bookworm 32bit'
        required: true
        type: boolean
      trixie_64:
        description: 'Build on PiOS Trixie 64bit'
        required: true
        type: boolean
      trixie_32:
        description: 'Build on PiOS Trixie 32bit'
        required: true
        type: boolean
      l4t_jammy_64:
        description: 'Build on Switchroot Ubuntu Jammy 64bit'
        required: true
        type: boolean
      l4t_noble_64:
        description: 'Build on Switchroot Ubuntu Noble 64bit'
        required: true
        type: boolean
      noble_64:
        description: 'Build on RPi Ubuntu Noble 64bit'
        required: true
        type: boolean
      resolute_64:
        description: 'Build on RPi Ubuntu Resolute 64bit'
        required: true
        type: boolean

run-name: Testing ${{ inputs.name }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  bullseye-32bit:
    runs-on: ubuntu-24.04-arm
    if: ${{ inputs.bullseye_32 }}
    steps:
      - uses: actions/checkout@v4
      - name: Test installing app on bullseye armhf
        uses: theofficialgman/chroot-runner-action@v0
        with:
          base_image: https://downloads.raspberrypi.com/raspios_oldstable_armhf/images/raspios_oldstable_armhf-2025-05-07/2025-05-06-raspios-bullseye-armhf.img.xz
          bind_mount_repository: yes
          image_additional_mb: 20000
          cpu_info: cpuinfo/raspberrypi_4b
          copy_repository_path: /home/runner/pi-apps
          export_github_env: yes
          import_github_env: true
          shell: /bin/bash
          commands: |
            export name="${{ inputs.name }}"
            ./.github/workflows/test_build_commands.sh

  bookworm-32bit:
    runs-on: ubuntu-24.04-arm
    if: ${{ inputs.bookworm_32 }}
    steps:
      - uses: actions/checkout@v4
      - name: Test installing app on bookworm armhf
        uses: theofficialgman/chroot-runner-action@v0
        with:
          base_image: https://downloads.raspberrypi.com/raspios_oldstable_armhf/images/raspios_oldstable_armhf-2026-06-19/2026-06-18-raspios-bookworm-armhf.img.xz
          bind_mount_repository: yes
          image_additional_mb: 20000
          cpu_info: cpuinfo/raspberrypi_4b
          copy_repository_path: /home/runner/pi-apps
          export_github_env: yes
          import_github_env: true
          shell: /bin/bash
          commands: |
            export name="${{ inputs.name }}"
            ./.github/workflows/test_build_commands.sh

  trixie-32bit:
    runs-on: ubuntu-24.04-arm
    if: ${{ inputs.trixie_32 }}
    steps:
      - uses: actions/checkout@v4
      - name: Test installing app on trixie armhf
        uses: theofficialgman/chroot-runner-action@v0
        with:
          base_image: https://downloads.raspberrypi.com/raspios_armhf/images/raspios_armhf-2026-06-19/2026-06-18-raspios-trixie-armhf.img.xz
          bind_mount_repository: yes
          image_additional_mb: 20000
          cpu_info: cpuinfo/raspberrypi_4b
          copy_repository_path: /home/runner/pi-apps
          export_github_env: yes
          import_github_env: true
          shell: /bin/bash
          commands: |
            export name="${{ inputs.name }}"
            ./.github/workflows/test_build_commands.sh

  bullseye-64bit:
    runs-on: ubuntu-24.04-arm
    if: ${{ inputs.bullseye_64 }}
    steps:
      - uses: actions/checkout@v4
      - name: Test installing app on bullseye arm64
        uses: theofficialgman/chroot-runner-action@v0
        with:
          base_image: https://downloads.raspberrypi.com/raspios_oldstable_arm64/images/raspios_oldstable_arm64-2025-05-07/2025-05-06-raspios-bullseye-arm64.img.xz
          bind_mount_repository: yes
          image_additional_mb: 20000
          cpu_info: cpuinfo/raspberrypi_4b
          copy_repository_path: /home/runner/pi-apps
          export_github_env: yes
          import_github_env: true
          shell: /bin/bash
          commands: |
            export name="${{ inputs.name }}"
            ./.github/workflows/test_build_commands.sh

  bookworm-64bit:
    runs-on: ubuntu-24.04-arm
    if: ${{ inputs.bookworm_64 }}
    steps:
      - uses: actions/checkout@v4
      - name: Test installing app on bookworm arm64
        uses: theofficialgman/chroot-runner-action@v0
        with:
          base_image: https://downloads.raspberrypi.com/raspios_oldstable_arm64/images/raspios_oldstable_arm64-2026-06-19/2026-06-18-raspios-bookworm-arm64.img.xz
          bind_mount_repository: yes
          image_additional_mb: 20000
          cpu_info: cpuinfo/raspberrypi_4b
          copy_repository_path: /home/runner/pi-apps
          export_github_env: yes
          import_github_env: true
          shell: /bin/bash
          commands: |
            export name="${{ inputs.name }}"
            ./.github/workflows/test_build_commands.sh

  trixie-64bit:
    runs-on: ubuntu-24.04-arm
    if: ${{ inputs.trixie_64 }}
    steps:
      - uses: actions/checkout@v4
      - name: Test installing app on trixie arm64
        uses: theofficialgman/chroot-runner-action@v0
        with:
          base_image: https://downloads.raspberrypi.com/raspios_arm64/images/raspios_arm64-2026-06-19/2026-06-18-raspios-trixie-arm64.img.xz
          bind_mount_repository: yes
          image_additional_mb: 20000
          cpu_info: cpuinfo/raspberrypi_4b
          copy_repository_path: /home/runner/pi-apps
          export_github_env: yes
          import_github_env: true
          shell: /bin/bash
          commands: |
            export name="${{ inputs.name }}"
            ./.github/workflows/test_build_commands.sh

  l4t-jammy-64bit:
    runs-on: ubuntu-24.04-arm
    if: ${{ inputs.l4t_jammy_64 }}
    steps:
      - uses: actions/checkout@v4
      - name: Test installing app on L4T jammy arm64
        uses: theofficialgman/chroot-runner-action@v0
        with:
          base_image: https://download.switchroot.org/ubuntu-jammy/theofficialgman-ubuntu-jammy-5.1.2-2026-05-13.7z
          # add special arguments for switchroot image format
          bootpartition:
          rootpartition: 1
          bind_mount_repository: yes
          image_additional_mb: 20000
          copy_repository_path: /home/runner/pi-apps
          export_github_env: yes
          import_github_env: true
          shell: /bin/bash
          commands: |
            export name="${{ inputs.name }}"
            ./.github/workflows/test_build_commands.sh

  l4t-noble-64bit:
    runs-on: ubuntu-24.04-arm
    if: ${{ inputs.l4t_noble_64 }}
    steps:
      - uses: actions/checkout@v4
      - name: Test installing app on L4T noble arm64
        uses: theofficialgman/chroot-runner-action@v0
        with:
          base_image: https://download.switchroot.org/ubuntu-noble/theofficialgman-kubuntu-noble-5.1.2-2026-05-13.7z
          # add special arguments for switchroot image format
          bootpartition:
          rootpartition: 1
          bind_mount_repository: yes
          image_additional_mb: 20000
          copy_repository_path: /home/runner/pi-apps
          export_github_env: yes
          import_github_env: true
          shell: /bin/bash
          commands: |
            export name="${{ inputs.name }}"
            ./.github/workflows/test_build_commands.sh

  noble-64bit:
    runs-on: ubuntu-24.04-arm
    if: ${{ inputs.noble_64 }}
    steps:
      - uses: actions/checkout@v4
      - name: Test installing app on noble arm64
        uses: theofficialgman/chroot-runner-action@v0
        with:
          base_image: https://cdimage.ubuntu.com/ubuntu/releases/24.04/release/ubuntu-24.04.4-preinstalled-desktop-arm64+raspi.img.xz
          bind_mount_repository: yes
          image_additional_mb: 20000
          cpu_info: cpuinfo/raspberrypi_4b
          copy_repository_path: /home/runner/pi-apps
          export_github_env: yes
          import_github_env: true
          shell: /bin/bash
          commands: |
            export name="${{ inputs.name }}"
            ./.github/workflows/test_build_commands.sh

  resolute-64bit:
    runs-on: ubuntu-24.04-arm
    if: ${{ inputs.resolute_64 }}
    steps:
      - uses: actions/checkout@v4
      - name: Test installing app on resolute arm64
        uses: theofficialgman/chroot-runner-action@v0
        with:
          base_image: https://cdimage.ubuntu.com/ubuntu/releases/26.04/release/ubuntu-26.04-preinstalled-desktop-arm64+raspi.img.xz
          bind_mount_repository: yes
          image_additional_mb: 20000
          cpu_info: cpuinfo/raspberrypi_4b
          copy_repository_path: /home/runner/pi-apps
          export_github_env: yes
          import_github_env: true
          shell: /bin/bash
          commands: |
            export name="${{ inputs.name }}"
            ./.github/workflows/test_build_commands.sh
