#!/bin/bash

#package found in: https://linux.wps.cn/

version=11.1.0.11711

if package_is_new_enough firejail 0.9.58 ;then
  firejail_package="firejail"
else
  firejail_package="http://ports.ubuntu.com/pool/universe/f/firejail/firejail_0.9.62-3ubuntu0.1_arm64.deb"
fi

# download wps office with custom command
rm -f /tmp/wps-office.deb
wget --header="Referer: https://linux.wps.cn/" "https://wps-linux-personal.wpscdn.cn/wps/download/ep/Linux2019/$(echo $version | sed 's/.*\.//g')/wps-office_${version}_arm64.deb" -c -O /tmp/wps-office.deb || exit 1

install_packages "$firejail_package" /tmp/wps-office.deb || exit 1
rm -f /tmp/wps-office.deb

#Prevent application from connecting to the internet
sudo sed -i 's|^Exec=|Exec=firejail --net=none --noblacklist=~/.local/share/Kingsoft --noblacklist=~/.config/Kingsoft |g' /usr/share/applications/wps*.desktop
