#!/bin/bash

version="v0.15.0"

BIN=/usr/local/bin/en-croissant
ICON=/usr/local/share/icons/en-croissant.png
DESKTOP=$HOME/.local/share/applications/en-croissant.desktop

if [ "$arch" == "64" ]; then
  RUST_TARGET="aarch64-unknown-linux-gnu"
elif [ "$arch" == "32" ]; then
  RUST_TARGET="armv7-unknown-linux-gnueabihf"
else
  error "Unsupported architecture: $arch"
fi

"${DIRECTORY}/manage" install-if-not-installed Node.js || error "Failed to install Node.js! This is necessary to compile En Croissant."

# install the stupidly large amount of required packages
install_packages \
build-essential \
clang \
lld \
pkg-config \
libssl-dev \
libgtk-3-dev \
libwebkit2gtk-4.1-dev \
libayatana-appindicator3-dev \
librsvg2-dev \
libxdo-dev \
libglib2.0-dev \
libgdk-pixbuf-2.0-dev \
libpango1.0-dev \
libatk1.0-dev \
libcairo2-dev \
libsoup-3.0-dev \
libjavascriptcoregtk-4.1-dev \
ca-certificates \
sccache || exit 1

# install pnpm if missing
#initialize npm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" || error "failed to source nvm.sh"

npm install -g pnpm || error "NPM failed to install pnpm, which is necessary for En Croissant"

status "Checking Rust compiler for compatibility"

# simplified version checking
if package_is_new_enough rustc 1.77.2; then
  echo "Rust compiler available in the package repositories is new enough, installing from package repositories"
  install_packages cargo rustc
else
  echo "Rust compiler is too old in available package repositories, installing latest version via rustup"
  status "Installing newer Rust toolchain"
  wget -O /tmp/rustup-init.sh https://sh.rustup.rs || error "Failed to download rust init script"
  chmod +x /tmp/rustup-init.sh || error "Failed to make rust init script executable"
  /tmp/rustup-init.sh -y || error "Failed to run rust init script"
  . "$HOME/.cargo/env" || error "Failed to run source rust environment"
  rm /tmp/rustup-init.sh
fi

# ensure correct rust target
rustup target add "$RUST_TARGET"

# build optimisation
RUSTC_WRAPPER=$(command -v sccache)
export RUSTC_WRAPPER
SCCACHE_DIR="$HOME/.cache/sccache"
export SCCACHE_DIR
CARGO_BUILD_JOBS=$(nproc)
export CARGO_BUILD_JOBS
export RUSTFLAGS="-C link-arg=-fuse-ld=lld"

# build in /tmp
cd /tmp
rm -rf en-croissant-build
mkdir en-croissant-build
cd en-croissant-build

git clone --depth 1 --branch "$version" https://github.com/franciscoBSalgueiro/en-croissant.git || error "clone failed"

cd en-croissant

pnpm install || error "pnpm install failed"

pnpm build || error "build failed"

# install binary
sudo install src-tauri/target/release/en-croissant "$BIN"

# install icon
sudo mkdir -p /usr/local/share/icons
sudo cp src-tauri/icons/icon.png "$ICON"

# create desktop entry
mkdir -p "$HOME/.local/share/applications"

cat <<EOF > "$DESKTOP"
[Desktop Entry]
Name=En Croissant
Comment=The Ultimate Chess Toolkit
Exec=/usr/local/bin/en-croissant
Icon=/usr/local/share/icons/en-croissant.png
Terminal=false
Type=Application
Categories=Game;BoardGame;
StartupNotify=true
EOF

chmod +x "$DESKTOP"

# cleanup
cd ~/
rm -rf /tmp/en-croissant-build
