#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$(dirname "$0")")")"
function error {
  echo -e "\e[31m$1\e[39m"
  exit 1
}

#if your app installs any packages, keep this command here so those packages will be removed.
"${DIRECTORY}/purge-installed" "$(dirname "$0")" || exit 1

rm -f ~/.config/autostart/conky.desktop ~/.conkyrc || error "Failed to remove autostart file or .conkyrc!"

killall conky 2>/dev/null
