#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

# Get dependencies
"${DIRECTORY}/pkg-install" "python3-tk python3-pil python3-pil.imagetk" "$(dirname "$0")" || exit 1

rm -rf ~/CommanderPi
git clone https://github.com/Jack477/CommanderPi || error "failed to download repository!"
cd CommanderPi || error "failed to enter repository!"
chmod +x install.sh || error "failed to mark install.sh as executable!"
./install.sh || error "failed to run install.sh!"
