#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}
"${DIRECTORY}/purge-installed" "$(dirname "$0")" || exit 1

rm -rf ~/CommanderPi || sudo rm -rf ~/CommanderPi || error "failed to remove ~/CommanderPi folder!"
sudo rm -f /usr/share/applications/commanderpi.desktop ~/Desktop/commanderpi.desktop || error "failed to remove menu button!"
