#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

cd ~/Downloads

wget https://aka.ms/linux-arm64-deb || error 'Failed to download linux-arm64-deb!'
sudo dpkg -i linux-arm64-deb || error 'Failed to install linux-arm64-deb!'
rm -f linux-arm64-deb
cd
