#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

rm -f ~/code.deb
wget -O ~/code.deb https://aka.ms/linux-armhf-deb || error 'Failed to download linux-armhf-deb!'
"${DIRECTORY}/pkg-install" "$HOME/code.deb" "$(dirname "$0")" || error 'Failed to install code.deb!'
rm -f ~/code.deb
