#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

cd ~
find ./MultiMC/install -mindepth 1 ! -regex '^./MultiMC/install/instances\(/.*\)?' -delete
sudo rm -rf ~/MultiMC/src
sudo rm -rf ~/MultiMC/build
sudo rm -rf ~/.local/share/applications/MultiMC.desktop

"${DIRECTORY}/purge-installed" "$(dirname "$0")" || exit 1
